### ISSUE TITLE
Is this project open for accepting contributions at the moment?

### ISSUE THREAD

**Issue by ScorpioCPH** [NVIDIA/k8s-device-plugin#1]
@flx42 Hi, happy to find this project, this is a wonderful project!

I have try it on my local, and it works well.

I am just wondering is this project open for accepting contributions at the moment?

**Comment by flx42** [comment]
Yes it does, I updated the README. What do you have in mind?

**Comment by ScorpioCPH** [comment]
@flx42 LGTM, I will test it first and maybe send some PR for `FIXME`.

**Comment by ScorpioCPH** [comment]
Close.
