### ISSUE TITLE
K8s upgraded to 1.12.4 and GPU nodes gives nvidia.com/gpu:     0

### ISSUE THREAD

**Issue by binudba** [NVIDIA/k8s-device-plugin#100]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._
---

### 1. Issue or feature description
After upgrading K8s cluster to 1.12.4 all GPU worker nodes shows nvidia.com/gpu:     0
Jobs were running are shows pending status

### 2. Steps to reproduce the issue
Cuda toolkit 10.0 installed on nodes

# kubectl describe node | grep -i gpu
 nvidia.com/gpu:     0
 nvidia.com/gpu:     0
  nvidia.com/gpu  0            0
 nvidia.com/gpu:     0
 nvidia.com/gpu:     0
  nvidia.com/gpu  0            0
 nvidia.com/gpu:     0
 nvidia.com/gpu:     0
  nvidia.com/gpu  0            0
 nvidia.com/gpu:     0
 nvidia.com/gpu:     0
  nvidia.com/gpu  0            0
### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Common error checking:
 - [ ] The output of `nvidia-smi -a` on your host

==============NVSMI LOG==============

Timestamp                           : Wed Mar  6 19:34:26 2019
Driver Version                      : 410.72
CUDA Version                        : 10.0

Attached GPUs                       : 1
GPU 00000000:84:00.0
    Product Name                    : Tesla V100-PCIE-16GB
    Product Brand                   : Tesla
    Display Mode                    : Enabled
    Display Active                  : Disabled
    Persistence Mode                : Disabled
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 4000
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : 0324917053075
    GPU UUID                        : GPU-1f2eba5a-54f6-7a53-978b-9ab84bd291c0
    Minor Number                    : 0
    VBIOS Version                   : 88.00.1A.00.03
    MultiGPU Board                  : No
    Board ID                        : 0x8400
    GPU Part Number                 : 900-2G500-0300-030
    Inforom Version
        Image Version               : G500.0200.00.03
        OEM Object                  : 1.1
        ECC Object                  : 5.0
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization mode         : None
    IBMNPU
        Relaxed Ordering Mode       : N/A
    PCI
        Bus                         : 0x84
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x1DB410DE
        Bus Id                      : 00000000:84:00.0
        Sub System Id               : 0x121410DE
        GPU Link Info
            PCIe Generation
                Max                 : 3
                Current             : 3
            Link Width
                Max                 : 16x
                Current             : 16x
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays since reset         : 0
        Tx Throughput               : 0 KB/s
        Rx Throughput               : 0 KB/s
    Fan Speed                       : N/A
    Performance State               : P0
    Clocks Throttle Reasons
        Idle                        : Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Not Active
        HW Slowdown                 : Not Active
            HW Thermal Slowdown     : Not Active
            HW Power Brake Slowdown : Not Active
        Sync Boost                  : Not Active
        SW Thermal Slowdown         : Not Active
        Display Clock Setting       : Not Active
    FB Memory Usage
        Total                       : 16130 MiB
        Used                        : 0 MiB
        Free                        : 16130 MiB
    BAR1 Memory Usage
        Total                       : 16384 MiB
        Used                        : 2 MiB
        Free                        : 16382 MiB
    Compute Mode                    : Default
    Utilization
        Gpu                         : 0 %
        Memory                      : 0 %
        Encoder                     : 0 %
        Decoder                     : 0 %
    Encoder Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    FBC Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    Ecc Mode
        Current                     : Enabled
        Pending                     : Enabled
    ECC Errors
        Volatile
            Single Bit            
                Device Memory       : 0
                Register File       : 0
                L1 Cache            : 0
                L2 Cache            : 0
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : 0
            Double Bit            
                Device Memory       : 0
                Register File       : 0
                L1 Cache            : 0
                L2 Cache            : 0
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : 0
                Total               : 0
        Aggregate
            Single Bit            
                Device Memory       : 0
                Register File       : 0
                L1 Cache            : 0
                L2 Cache            : 0
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : 0
            Double Bit            
                Device Memory       : 0
                Register File       : 0
                L1 Cache            : 0
                L2 Cache            : 0
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : 0
                Total               : 0
    Retired Pages
        Single Bit ECC              : 0
        Double Bit ECC              : 0
        Pending                     : No
    Temperature
        GPU Current Temp            : 49 C
        GPU Shutdown Temp           : 90 C
        GPU Slowdown Temp           : 87 C
        GPU Max Operating Temp      : 83 C
        Memory Current Temp         : 47 C
        Memory Max Operating Temp   : 85 C
    Power Readings
        Power Management            : Supported
        Power Draw                  : 31.62 W
        Power Limit                 : 250.00 W
        Default Power Limit         : 250.00 W
        Enforced Power Limit        : 250.00 W
        Min Power Limit             : 100.00 W
        Max Power Limit             : 250.00 W
    Clocks
        Graphics                    : 135 MHz
        SM                          : 135 MHz
        Memory                      : 877 MHz
        Video                       : 555 MHz
    Applications Clocks
        Graphics                    : 1245 MHz
        Memory                      : 877 MHz
    Default Applications Clocks
        Graphics                    : 1245 MHz
        Memory                      : 877 MHz
    Max Clocks
        Graphics                    : 1380 MHz
        SM                          : 1380 MHz
        Memory                      : 877 MHz
        Video                       : 1237 MHz
    Max Customer Boost Clocks
        Graphics                    : 1380 MHz
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes                       : None
 - [ ] Your docker configuration file (e.g: `/etc/docker/daemon.json`)
# cat /etc/docker/daemon.json
{
    "runtimes": {
        "nvidia": {
            "path": "nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}
 - [ ] The k8s-device-plugin container logs
# kubectl logs -n kube-system nvidia-device-plugin-daemonset-1.12-48vt5 
2019/03/06 18:41:56 Loading NVML
2019/03/06 18:41:56 Failed to initialize NVML: could not load NVML library.
2019/03/06 18:41:56 If this is a GPU node, did you set the docker default runtime to `nvidia`?
2019/03/06 18:41:56 You can check the prerequisites at: https://github.com/NVIDIA/k8s-device-plugin#prerequisites
2019/03/06 18:41:56 You can learn how to set the runtime at: https://github.com/NVIDIA/k8s-device-plugin#quick-start
 - [ ] The kubelet logs on the node (e.g: `sudo journalctl -r -u kubelet`)
Mar 06 18:41:56 dbslp1561.uhc.com kubelet[2765]: 2019-03-06 18:41:56.491 [INFO][7131] network.go 31: Setting the host side veth name to calib10344c622d ContainerID="48cc15a954e5988779bba6afd2c4ba5d9ce247a2d2101d42afd33ee1554061a6" Namespace="kube-system" Pod="nvidia-device-plugin-daemonset-1.12-tpz8v" WorkloadEndpoint="dbslp1561.uhc.com-k8s-nvidia--device--plugin--daemonset--1.12--tpz8v-eth0"
Mar 06 18:41:56 dbslp1561.uhc.com kubelet[2765]: 2019-03-06 18:41:56.492 [INFO][7131] network.go 326: Disabling IPv4 forwarding ContainerID="48cc15a954e5988779bba6afd2c4ba5d9ce247a2d2101d42afd33ee1554061a6" Namespace="kube-system" Pod="nvidia-device-plugin-daemonset-1.12-tpz8v" WorkloadEndpoint="dbslp1561.uhc.com-k8s-nvidia--device--plugin--daemonset--1.12--tpz8v-eth0"
Mar 06 18:41:56 dbslp1561.uhc.com kubelet[2765]: 2019-03-06 18:41:56.516 [INFO][7131] k8s.go 294: Added Mac, interface name, and active container ID to endpoint ContainerID="48cc15a954e5988779bba6afd2c4ba5d9ce247a2d2101d42afd33ee1554061a6" Namespace="kube-system" Pod="nvidia-device-plugin-daemonset-1.12-tpz8v" WorkloadEndpoint="dbslp1561.uhc.com-k8s-nvidia--device--plugin--daemonset--1.12--tpz8v-eth0" endpoint=&v3.WorkloadEndpoint{TypeMeta:v1.TypeMeta{Kind:"WorkloadEndpoint", APIVersion:"projectcalico.org/v3"}, ObjectMeta:v1.ObjectMeta{Name:"dbslp1561.uhc.com-k8s-nvidia--device--plugin--daemonset--1.12--tpz8v-eth0", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"8442b3ac-403f-11e9-a357-3863bb3b77fc", ResourceVersion:"24444889", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63687494515, loc:(*time.Location)(0x1ec6320)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"controller-revision-hash":"68f76d744", "name":"nvidia-device-plugin-ds", "pod-template-generation":"1", "projectcalico.org/namespace":"kube-system", "projectcalico.org/orchestrator":"k8s"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:v3.WorkloadEndpointSpec{Orchestrator:"k8s", Workload:"", Node:"dbslp1561.uhc.com", ContainerID:"48cc15a954e5988779bba6afd2c4ba5d9ce247a2d2101d42afd33ee1554061a6", Pod:"nvidia-device-plugin-daemonset-1.12-tpz8v", Endpoint:"eth0", IPNetworks:[]string{"10.244.6.64/32"}, IPNATs:[]v3.IPNAT(nil), IPv4Gateway:"", IPv6Gateway:"", Profiles:[]string{"kns.kube-system"}, InterfaceName:"calib10344c622d", MAC:"62:ac:58:cc:5b:c5", Ports:[]v3.EndpointPort(nil)}}
Mar 06 18:41:56 dbslp1561.uhc.com kubelet[2765]: 2019-03-06 18:41:56.523 [INFO][7131] k8s.go 302: Wrote updated endpoint to datastore ContainerID="48cc15a954e5988779bba6afd2c4ba5d9ce247a2d2101d42afd33ee1554061a6" Namespace="kube-system" Pod="nvidia-device-plugin-daemonset-1.12-tpz8v" WorkloadEndpoint="dbslp1561.uhc.com-k8s-nvidia--device--plugin--daemonset--1.12--tpz8v-eth0"

Additional information that might help better understand your environment and reproduce the bug:
 - [ ] Docker version from `docker version`
# docker version
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:26:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

 - [ ] Docker command, image and tag used
 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
# nvidia-container-cli -V
version: 1.0.0
build date: 2018-09-20T20:25+0000
build revision: 881c88e2e5bb682c9bb14e68bd165cfb64563bb1
build compiler: gcc 4.8.5 20150623 (Red Hat 4.8.5-28)
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections

 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))

**Comment by binudba** [comment]
This has been resolved. docker daemon.json file had invalid entries.

**Comment by A-BenMao** [comment]
> 此问题已解决。docker daemon.json文件包含无效条目。

Excuse me, what does the invalid entry mean? I have encountered this problem，thanks

**Comment by klueska** [comment]
He did not have the default runtime set to `nvidia` in his `daemon.json` file, i.e.:
```
{
    "default-runtime": "nvidia",
    ...
}
```
