### ISSUE TITLE
Nvidia Device plugin for k8s v1.13.4

### ISSUE THREAD

**Issue by vinilvadakkepurakkal** [NVIDIA/k8s-device-plugin#101]
I would like to know, is there is any new  Nvidia-device-plugin for Kubernetes version v1.13.4 ?. How can I use the Nvidia GPU resource in Kubernetes version v1.13.4?

Any guidance in this would be of great help

**Comment by kairen** [comment]
@vinilvadakkepurakkal I think nvidia-device-plugin v1.12 can be performed successfully.

**Comment by vinilvadakkepurakkal** [comment]
@kairen i tried it, however, I didn't work for me.

**Comment by kairen** [comment]
Do you have any logs for NVIDIA device plugin Pod?

**Comment by vinilvadakkepurakkal** [comment]
Pod is not getting created.
root@master1:~# kubectl get nodes
NAME            STATUS   ROLES    AGE   VERSION
master2   Ready    master1   18h   v1.13.4
master3   Ready    master1   18h   v1.13.4
master1   Ready    master1   18h   v1.13.4


root@master1:~# docker images | grep nvidia/k8s-device-plugin
nvidia/k8s-device-plugin                        1.11                    01db6f81e668        7 months ago        63.1MB
root@master1:~#
root@master1:~# kubectl create -f nvidia-device-plugin.yml
daemonset.extensions/nvidia-device-plugin-daemonset created
root@master1:~#


root@master1:~# kubectl get pods -n kube-system
NAME                                    READY   STATUS    RESTARTS   AGE
coredns-86c58d9df4-pjxcp                1/1     Running   0          18h
coredns-86c58d9df4-thtq8                1/1     Running   0          18h
etcd-master2                      1/1     Running   0          18h
etcd-master3                      1/1     Running   0          18h
etcd-master1                      1/1     Running   0          18h
kube-apiserver-master2            1/1     Running   0          18h
kube-apiserver-master3            1/1     Running   0          18h
kube-apiserver-master1            1/1     Running   0          18h
kube-controller-manager-master2   1/1     Running   0          18h
kube-controller-manager-master3   1/1     Running   1          18h
kube-controller-manager-master1   1/1     Running   1          18h
kube-proxy-4c28w                        1/1     Running   0          18h
kube-proxy-4fzb7                        1/1     Running   0          18h
kube-proxy-ch8vv                        1/1     Running   0          18h
kube-scheduler-master2            1/1     Running   0          18h
kube-scheduler-master3            1/1     Running   1          18h
kube-scheduler-master1            1/1     Running   1          18h
weave-net-2nr7z                         2/2     Running   1          18h
weave-net-5jk7t                         2/2     Running   1          18h
weave-net-jp8vz                         2/2     Running   0          18h


i just patched it and it worked !!

kubectl patch daemonset nvidia-device-plugin-daemonset --namespace kube-system   -p '{ "spec": { "template": { "spec": { "tolerations": [ { "operator": "Exists" } ] } } } }'
