### ISSUE TITLE
Support for Registering GPU Resources by Model Name (e.g., nvidia.com/A100)

### ISSUE THREAD

**Issue by antonaleks** [NVIDIA/k8s-device-plugin#1024]
Hello,
I would like to request a feature that allows the NVIDIA device plugin to register GPU resources in Kubernetes using the specific model name of the GPU, such as nvidia.com/A100, instead of the generic nvidia.com/gpu. This feature would be particularly useful for environments with heterogeneous GPU models, where scheduling based on specific GPU capabilities is required.

**Use Case:**

- In clusters with multiple GPU models, it is often necessary to schedule workloads on specific GPU types to optimize performance and resource utilization.
- By registering resources with model-specific names, users can more easily request the exact GPU type needed for their workloads.
- 
**Proposed Solution:**
- Modify the device plugin to detect the GPU model using NVML and register resources with names based on the model, e.g., nvidia.com/A100.
- Provide a configuration option to enable or disable this feature, allowing users to choose between generic and model-specific resource names.

**Possible Implementation:**
https://github.com/NVIDIA/k8s-device-plugin/blob/main/internal/rm/rm.go#L132
```
deviceCount, err := nvml.DeviceGetCount()
if err != nil {
    return fmt.Errorf("failed to get device count: %v", err)
}

for i := 0; i < deviceCount; i++ {
    device, err := nvml.DeviceGetHandleByIndex(i)
    if err != nil {
        return fmt.Errorf("failed to get device handle: %v", err)
    }

    model, err := nvml.DeviceGetName(device)
    if err != nil {
        return fmt.Errorf("failed to get device name: %v", err)
    }

    // Register resource with the model name
    resourceName := "nvidia.com/" + strings.ToLower(model)
    _ = config.Resources.AddGPUResource("*", resourceName)
}
```
and example of pod

```
apiVersion: v1
kind: Pod
metadata:
  name: a100-gpu-pod
spec:
  containers:
  - name: gpu-container
    image: nvidia/cuda:11.0-base
    resources:
      limits:
        nvidia.com/a100: 1  # Request a specific GPU model
```

**Benefits:**

- Improved scheduling flexibility and resource utilization in mixed GPU environments.
- Simplified workload specifications by allowing direct requests for specific GPU models.

Thank you for considering this feature request. I believe it would greatly enhance the usability of the NVIDIA device plugin in diverse GPU environments.

**Comment by antonaleks** [comment]
Also it will be usefull to make config like this https://github.com/NVIDIA/gpu-operator/blob/main/assets/state-mig-manager/0400_configmap.yaml for mig manager

**Comment by klueska** [comment]
Please see the following thread for an explanation of why this feature does not exist (and why it will likely never exist):
https://github.com/NVIDIA/k8s-device-plugin/issues/424#issuecomment-1647438332
