### ISSUE TITLE
What the maim purpose of using k8s device plugin instead of nvidia-docker2 as default runtime?

### ISSUE THREAD

**Issue by dimorinny** [NVIDIA/k8s-device-plugin#103]
Hello, guys. It's not an issue. Just an question.
Now, I'm trying to run gpu accelerated android emulators with tesla p40.

But I've faced with OpenGL rendering errors inside emulators. Mostly, that errors about allocating frame buffers.

I've tried to run emulators as pods in kubernetes cluster.

But I haven't used device plugin. I've created gpu accelerated xorg and share X11 socket between containers. Also, I'm using nvidia-docker2 runtime as default runtime for all docker containers.

I found, that frequency of frame buffer allocating errors depends on emulators count, that use shared GPU card. (for example, everything work great with 3 emulators, but I have a lot of errors, when I have, 6 emulators).

**The question:** Is it secure to share GPU between containers without using device plugin? Or I must create limits for every container?

Thanks.

**Comment by pan87232494** [comment]
> Hello, guys. It's not an issue. Just an question.
> Now, I'm trying to run gpu accelerated android emulators with tesla p40.
> 
> But I've faced with OpenGL rendering errors inside emulators. Mostly, that errors about allocating frame buffers.
> 
> I've tried to run emulators as pods in kubernetes cluster.
> 
> But I haven't used device plugin. I've created gpu accelerated xorg and share X11 socket between containers. Also, I'm using nvidia-docker2 runtime as default runtime for all docker containers.
> 
> I found, that frequency of frame buffer allocating errors depends on emulators count, that use shared GPU card. (for example, everything work great with 3 emulators, but I have a lot of errors, when I have, 6 emulators).
> 
> **The question:** Is it secure to share GPU between containers without using device plugin? Or I must create limits for every container?
> 
> Thanks.

Hi, I have same question here,  can you share your info with me. thanks
