### ISSUE TITLE
CrashLoopBackOff when running nvidia-device-plugin-daemonset

### ISSUE THREAD

**Issue by fl8858** [NVIDIA/k8s-device-plugin#105]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._
---

### 1. Issue or feature description
I deployed the latest Kubernetes (1.13) through juju cs:bundle/canonical-kubernetes-435.  The cluster ran well. However, when running nvidia-device-plugin-daemonset on a kubernetes worker with 2 GeForce GTX 1080 Ti, I got the error message that it couldn't detect cuda-capable device. Not sure if this is because the installed Nvidia driver version 418 doesn't support 1080?

  Warning  Failed     3m27s                   kubelet, node1     Error: failed to start container "nvidia-device-plugin-ctr": Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --utility --pid=28514 /var/lib/docker/overlay2/bc7a6cfad6a3e3d56a7a09c436b3d8278a3636d4cf9e76add99265e84d1bc622/merged]\\\\nnvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\\\n\\\"\"": unknown
  Warning  BackOff    2m27s (x10 over 4m41s)  kubelet, node1     Back-off restarting failed container

### 2. Steps to reproduce the issue
2.1) Install k8s on MAAS using Juju GUI, assign kubernetes worker to a server with 2 GPUs
2.2) run the following command:
kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/1.0.0-beta/nvidia-device-plugin.yml
2.3) Got the above error when running
kubectl get pods -n kube-system
kubectl describe pod nvidia-device-plugin-daemonset-8krm6 -n kube-system

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Common error checking:
 - x[ ] The output of `nvidia-smi -a` on your host
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

 - [x ] Your docker configuration file (e.g: `/etc/docker/daemon.json`)
{"runtimes": {"nvidia": {"path": "nvidia-container-runtime", "runtimeArgs": []}}, "default-runtime": "nvidia"}ubuntu@node1:/usr/lib/nvidia

 - [ ] The k8s-device-plugin container logs
 - [ ] The kubelet logs on the node (e.g: `sudo journalctl -r -u kubelet`)
-- No entries --

Additional information that might help better understand your environment and reproduce the bug:
 - [x ] Docker version from `docker version`
18.09.3
 - [ ] Docker command, image and tag used
 - [x ] Kernel version from `uname -a`
 4.15.0-46-generic
 - [x ] Any relevant kernel output lines from `dmesg
[dmesg_output.txt](https://github.com/NVIDIA/k8s-device-plugin/files/3010460/dmesg_output.txt)
`
 - [x ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
[nvidia_package_version.txt](https://github.com/NVIDIA/k8s-device-plugin/files/3010475/nvidia_package_version.txt)

 - [ x] NVIDIA container library version from `nvidia-container-cli -V`
version: 1.0.2
build date: 2019-03-26T03:58+00:00
build revision: ff40da533db929bf515aca59ba4c701a65a35e6b
build compiler: x86_64-linux-gnu-gcc-7 7.3.0
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections

 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))

**Comment by RenaudWasTaken** [comment]
[X] The output of nvidia-smi -a on your host
> NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

try to run `sudo nvidia-container-cli -k -d /dev/tty info` and then `nvidia-smi` if that doesn't solve your problem, reinstall the driver.

**Comment by fl8858** [comment]
Thanks for the response. It seems to be an issue with Kubernetes-worker #472 juju charm. After installing the charm, all my GPU nodes have the similar issue. Once restart the node, the issue is gone. 

In addition, I also made the following changes bases on this post: 
https://bugs.launchpad.net/charm-kubernetes-worker/+bug/1812894. 
Still, it works only after restarting the server.

Thanks again for the great help!
