### ISSUE TITLE
the minimal driver version is incorrect

### ISSUE THREAD

**Issue by ptonelli** [NVIDIA/k8s-device-plugin#108]
### 1. Issue or feature description

The minimal nvidia driver version requested is 361.93. 

### 2. Steps to reproduce the issue

Using drivers version 375.* , the pod crashes with : "undefined symbol: nvmlDeviceGetPciInfo_v3"

### 3. Solution

Using 384.81 works

Upgrading the documentation would be great.

**Comment by RenaudWasTaken** [comment]
Hello!

Thanks for the report, I will update the documentation accordingly!
