### ISSUE TITLE
Could not register device plugin:unknown service v1beta1.Registration

### ISSUE THREAD

**Issue by sorowakers** [NVIDIA/k8s-device-plugin#109]
Issue
 - Could not detect GPU resource on kubernetes cluster
- When i try to run (on GPU Node) ` docker run --security-opt=no-new-privileges --cap-drop=ALL --network=none -it -v /var/lib/kubelet/device-plugins:/var/lib /kubelet/device-plugins nvidia/k8s-device-plugin:1.0.0-beta` i got
`2019/04/05 04:02:20 Starting to serve on /var/lib/kubelet/device-plugins/nvidia.sock
2019/04/05 04:02:20 Could not register device plugin: rpc error: code = Unimplemented desc = unknown service v1beta1.Registration
2019/04/05 04:02:20 Could not contact Kubelet, retrying. Did you enable the device plugin feature gate?
2019/04/05 04:02:20 You can check the prerequisites at: https://github.com/NVIDIA/k8s-device-plugin#prerequisites
2019/04/05 04:02:20 You can learn how to set the runtime at: https://github.com/NVIDIA/k8s-device-plugin#quick-start`

Information:
 - Using Nvidia DGX as a GPU Worker and Virtual Machine as a Master
 - Both nodes installed using kubeadm, kubectl, kubelet : 1.10.11+nvidia
 - Followed the installation instruction on: https://docs.nvidia.com/datacenter/kubernetes/kubernetes-install-guide/index.html
 - Using k8s-device-plugin:1.0.0-beta 
 - nvidia-smi on gpu node:

`$nvidia-smi
Fri Apr  5 10:59:24 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-DGXS...  On   | 00000000:07:00.0 Off |                    0 |
| N/A   35C    P0    40W / 300W |     27MiB / 32478MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-DGXS...  On   | 00000000:08:00.0 Off |                    0 |
| N/A   34C    P0    38W / 300W |      0MiB / 32478MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-DGXS...  On   | 00000000:0E:00.0 Off |                    0 |
| N/A   34C    P0    39W / 300W |      0MiB / 32478MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-DGXS...  On   | 00000000:0F:00.0 Off |                    0 |
| N/A   34C    P0    39W / 300W |      0MiB / 32478MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2206      G   /usr/lib/xorg/Xorg                             9MiB |
|    0      2242      G   /usr/bin/gnome-shell                          15MiB |
+-----------------------------------------------------------------------------+`

Docker daemon on GPU Node:
`$ cat /etc/docker/daemon.json
{
    "default-runtime": "nvidia",
    "runtimes": {
        "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}`

Kubelet on GPU Node: (ps ax | grep kubelet)
`/usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --cluster-dns=10.96.0.10 --cluster-domain=cluster.local --authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt --cadvisor-port=0 --rotate-certificates=true --cert-dir=/var/lib/kubelet/pki --feature-gates=DevicePlugins=true --resolv-conf=/run/systemd/resolve/resolv.conf`

`$ kubectl describe daemonset.apps/nvidia-device-plugin-daemonset -n kube-system  
Name:           nvidia-device-plugin-daemonset                                                       
Selector:       name=nvidia-device-plugin-ds                                                         
Node-Selector:  <none>                                                                               
Labels:         name=nvidia-device-plugin-ds                                                         
Annotations:    <none>                                                                               
Desired Number of Nodes Scheduled: 2                                                                 
Current Number of Nodes Scheduled: 2                                                                 
Number of Nodes Scheduled with Up-to-date Pods: 2                                                    
Number of Nodes Scheduled with Available Pods: 2                                                     
Number of Nodes Misscheduled: 0                                                                      
Pods Status:  2 Running / 0 Waiting / 0 Succeeded / 0 Failed                                         
Pod Template:                                                                                        
  Labels:       name=nvidia-device-plugin-ds                                                         
  Annotations:  scheduler.alpha.kubernetes.io/critical-pod=                                          
  Containers:                                                                                        
   nvidia-device-plugin-ctr:                                                                         
    Image:        nvidia/k8s-device-plugin:1.0.0-beta                                                
    Port:         <none>                                                                             
    Host Port:    <none>                                                                             
    Environment:  <none>                                                                             
    Mounts:                                                                                          
      /var/lib/kubelet/device-plugins from device-plugin (rw)                                        
  Volumes:                                                                                           
   device-plugin:                                                                                    
    Type:          HostPath (bare host directory volume)                                             
    Path:          /var/lib/kubelet/device-plugins                                                   
    HostPathType:                                                                                    
Events:            <none>`

**Comment by RenaudWasTaken** [comment]
Sorry the v1.0.0-beta is only compatible with version 1.11+
Before that you need to use the v1.10 plugin (see the other branches).
