### ISSUE TITLE
nvidia-device-plugin container CrashLoopBackOff error

### ISSUE THREAD

**Issue by WanLinghao** [NVIDIA/k8s-device-plugin#11]
I deployed device-plugin container on k8s via the guide.
However I got container CrashLoopBackOff  error:
```
NAME                                   READY     STATUS             RESTARTS   AGE
nvidia-device-plugin-daemonset-zb8xn   0/1       CrashLoopBackOff   6          9m
```
And when I run 

> docker run -it -v /var/lib/kubelet/device-plugins:/var/lib/kubelet/device-plugins nvidia/k8s-device-plugin:1.8

I got error like this:
```
2017/11/29 01:54:30 Loading NVML
2017/11/29 01:54:30 could not load NVML library
```

But I am pretty sure that I have installed NVML library.
So did I miss anything here? 
How to check if I installed NVML library?

**Comment by flx42** [comment]
You need to setup our runtime as the default runtime, as described here:
https://github.com/NVIDIA/k8s-device-plugin#nvidia-device-plugin-for-kubernetes
We have a patch inflight to improve this error message.

**Comment by WanLinghao** [comment]
@flx42 
I tried as you said. Run command like this:

>  docker run --runtime=nvidia -it -v  /var/lib/kubelet/device-plugins:/var/lib/kubelet/device-plugins nvidia/k8s-device-plugin:1.8 

got error: 
```
2017/11/29 06:41:10 Loading NVML
2017/11/29 06:41:10 Starting to serve on /var/lib/kubelet/device-plugins/nvidia.sock
2017/11/29 06:41:10 Fatal: nvml: Not Supported
panic: Fatal: nvml: Not Supported


goroutine 3 [running]:
log.Panicln(0xc4200256f8, 0x2, 0x2)
	/usr/local/go/src/log/log.go:340 +0xc0
main.check(0xd3b800, 0xc420010060)
	/go/src/nvidia-device-plugin/main.go:20 +0x9c
main.watchXIDs(0xd42e80, 0xc420054040, 0xc420082050, 0x1, 0x1, 0xc4201d2000)
	/go/src/nvidia-device-plugin/nvidia.go:43 +0x86
created by main.(*NvidiaDevicePlugin).healthcheck
	/go/src/nvidia-device-plugin/server.go:183 +0xdf
```

**Comment by flx42** [comment]
What's your GPU? You can get that with the output of `nvidia-smi`.

**Comment by WanLinghao** [comment]
@flx42 
GeForce GT 730 
and the whole picture like this:
```
Wed Nov 29 14:57:37 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.81                 Driver Version: 384.81                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 730      Off  | 00000000:01:00.0 N/A |                  N/A |
| 40%   34C    P0    N/A /  N/A |    342MiB /  2000MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+
```

**Comment by flx42** [comment]
Yeah, this GPU is too old to run the device plugin. Some NVML functions will return "Not supported".

**Comment by WanLinghao** [comment]
@flx42 
Ok, thanks~
by the way, is this plugin a alpha model which  pictured by the document below:
https://github.com/NVIDIA/k8s-device-plugin

**Comment by flx42** [comment]
Device plugin is still an alpha feature in Kubernetes indeed. The vendor implementation itself (this repository) is quite straightforward so I wouldn't call it alpha (since I wouldn't know what the path to beta and GA would be).

**Comment by WanLinghao** [comment]
@flx42 
forget  alpha, so it does be a k8s device plugin model?

**Comment by flx42** [comment]
I don't understand your question, sorry.

**Comment by WanLinghao** [comment]
@flx42 
Since the guide of this project gives little information about what the plugin does.
So all I want to know is how this plugin interact with k8s, 
on another way ,what's the difference between with this plugin and without this plugin

**Comment by flx42** [comment]
For the interaction with Kubernetes, you should look at the Device Manager doc:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resource-management/device-plugin.md
This code is an implementation of a Device Plugin (per the document above) for enabling access to NVIDIA GPUs in containers started by Kubernetes.

**Comment by ScorpioCPH** [comment]
@WanLinghao Hi, this repository is a client side implementation of DP, and k8s just implements the server side. They are totally different scope but should work together :)

**Comment by RenaudWasTaken** [comment]
Current behavior now marks your GPU unhealthy instead of crashing

**Comment by RenaudWasTaken** [comment]
I suppose this can be closed now?

**Comment by WanLinghao** [comment]
@flx42 Hello, I noticed that the GPU must meet the demands as blow:
```
    NVIDIA GPU with Architecture > Fermi (2.1)
    NVIDIA drivers ~= 361.93 (untested on older versions)
```
ref:https://github.com/nvidia/nvidia-docker/wiki/Installation-(version-2.0)#prerequisites

My GPU is Geforce GT 730 and the driver version is 384.130, it doesn't work with error:
`2018/11/22 11:17:25 Warning: GPU-6e5aa18f-ba28-e70b-57cc-95f1be4b178b is too old to support healthchecking: nvml: Not Supported. Marking it unhealthy.`

So I am wondering if it is  Architecture the wrong part.
But  I don't know how to figure out the Architecture of my GPU after a lot of trials.
Do you have any clue about how to get the Architecture of nvidia GPU? Thanks
