### ISSUE TITLE
After setup config to crio, crio can not stop container anymore.

### ISSUE THREAD

**Issue by stefenson** [NVIDIA/k8s-device-plugin#1108]
Hello there, I found a Fatal Error in **```nvidia-ctk```**.
After run the config command as README says:
```
nvidia-ctk runtime configure --runtime=crio --set-as-default --config=/etc/crio/crio.conf.d/99-nvidia.conf
```
I get the config file as the example says.
Then I restart my crio service
```
systemctl restart crio
```
Everything looks like peaceful.
But when I restart some deploys or delete some pods in k8s, the process will stuck in **```Terminating```**.
![Image](https://github.com/user-attachments/assets/4b0ef9e0-f51c-44cd-bb7d-9ca6b1b0d043)

Check the crio log, there shows ```stop container failed.```
![Image](https://github.com/user-attachments/assets/e34c66d6-956d-4495-a8ba-874d09c94da1)

**Whatever, when I remove the config file and restart crio, everything returns to normal.**

I have no idea whether this plugin makes this happen or just crio has some bugs.
Could you please give me some bug fix solution?

Addition info:
```
OS: Ubuntu 24.04.1 LTS amd64
CRIO version: 1.24.6
NVIDIA Container Tookit CLI version: 1.17.1
NVIDIA Container Runtime version: 1.17.1
NVIDIA-SMI: 550.120
Graphic Card: GeForce RTX 4090
```
nvidia-ctk generate config file is:
![Image](https://github.com/user-attachments/assets/7c57dc37-9e93-425b-9291-3d7f0f9d5a8d)

And after setup nvidia config to crio, every time I use exec enter the container, the shell will loop print ```ERRO[xxxx] permission denied``` like this:
![Image](https://github.com/user-attachments/assets/84a8b05a-2773-4fac-8862-f3b4e7852397)

**Comment by stefenson** [comment]
I solved this by myself.

The main fault is here:
```
[crio.runtime]
    default_runtime = "nvidia"
```
This config changes the crio default user to "nvidia" not root, so the permission blocks all the action that crio wants to do.

I try to delete this config, and crio returns to normal, however the new container can not use nvidia plugin anymore.

So, now the question becomes why root can not use nvidia driver in container?

Any ideas?

**Comment by chipzoller** [comment]
This isn't a question for the device plugin but for the [container toolkit](https://github.com/NVIDIA/nvidia-container-toolkit).

**Comment by stefenson** [comment]
> This isn't a question for the device plugin but for the [container toolkit](https://github.com/NVIDIA/nvidia-container-toolkit). Additionally, it really helps readability and searchability when not posting screenshots of text/terminal output.

OK, I will contact with NVIDIA/nvidia-container-toolkit group.

Thank you very much.
