### ISSUE TITLE
k8s-device-plugin reports that a gpu is unhealthy, why it becomes healthy after i restart my k8s-device-plugin?

### ISSUE THREAD

**Issue by tingzhang-ming** [NVIDIA/k8s-device-plugin#111]
k8s-device-plugin reports that a gpu is unhealthy, then i restart my k8s-device-plugin pod, this gpu becomes healthy immediatedly.

so i want to ask is that gpu really unhealthy? because i do not restart any gpu in my machine, i just rerunning the k8s-device-plugin code.

**Comment by RenaudWasTaken** [comment]
- The device plugin marks GPUs unhealthy when they generate DBE (Double Bit Errors).
- When you restart the GPU we don't perform (yet) any checks and assume your GPU is healty
- You can use `DP_DISABLE_HEALTHCHECKS=all` to disable the health checks

**Comment by lxxin** [comment]
interesting
