### ISSUE TITLE
Docker will run the cuda-vector-add example, but the container will not run from OpenShift.

### ISSUE THREAD

**Issue by robbaronbu** [NVIDIA/k8s-device-plugin#113]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._
---

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Common error checking:
 - [ ] The output of `nvidia-smi -a` on your host
 - [ ] Your docker configuration file (e.g: `/etc/docker/daemon.json`)
 - [ ] The k8s-device-plugin container logs
 - [ ] The kubelet logs on the node (e.g: `sudo journalctl -r -u kubelet`)

Additional information that might help better understand your environment and reproduce the bug:
 - [ ] Docker version from `docker version`
 - [ ] Docker command, image and tag used
 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))

**Comment by robbaronbu** [comment]
I have 2 installations of OpenShift (RedHat's Kubernetes distribution).  One is on x86 and the other is on Power9.  They have been set up with the same instructions, however the x86 can run cuda-vector-add example from both docker and from openshift, while the Power9 can the same example from docker, but not from OpenShift.

**Comment by zvonkok** [comment]
@robbaronbu Can you check if you have followed all steps from this doc: https://github.com/zvonkok/origin-ci-gpu/blob/release-3.11/doc/How%20to%20use%20GPUs%20with%20DevicePlugin%20in%20OpenShift%203.11%20.pdf

**Comment by robbaronbu** [comment]
@zvonkok  - Yes, that is the document that I followed for both the x86 and the Power9 cluster.

**Comment by vijaydurai79** [comment]
> @robbaronbu Can you check if you have followed all steps from this doc: https://github.com/zvonkok/origin-ci-gpu/blob/release-3.11/doc/How%20to%20use%20GPUs%20with%20DevicePlugin%20in%20OpenShift%203.11%20.pdf

Thanks for the doc. Very useful for x86 platform.

**Comment by RenaudWasTaken** [comment]
Hello!

Looking a bit more at your pod spec it isn't requesting any GPUs :)
Please follow the readme or @zvonkok's documentation.

Feel free to reopen an issue if you hit the same or another error, I'll make sure to be more active!
