### ISSUE TITLE
Warning  FailedScheduling  40s (x2 over 40s)  default-scheduler  0/2 nodes are available: 1 Insufficient nvidia.com/gpu, 1 node(s) were unschedulable.

### ISSUE THREAD

**Issue by Niuxiaotong** [NVIDIA/k8s-device-plugin#119]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._
---

### 1. Issue or feature description
First:
when  kubectl apply -f gpu-job.yaml 
，pod in Pending and then kubectl describe pod gpu-gtx-1050
Events:
 Warning FailedScheduling  40s (x2 over 40s)  default-scheduler  0/2 nodes are available: 1 Insufficient nvidia.com/gpu, 1 node(s) were unschedulable.
Second:
https://github.com/NVIDIA/k8s-device-plugin
1、install nvidia-docker2、nvidia-docker-runtime;
2、deploy k8s-device-plugin
3、kubectl describe nodes then, appear gpu resources
4、gpu-job.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: gpu-gtx-1050
spec:
  containers:
    - name: cuda-container
      image: nvidia/cuda:9.0-devel
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 2 GPUs
        requests:
          nvidia.com/gpu: 1
  nodeSelector:
    accelerator: gtx-1050

### 2. Steps to reproduce the issue
[root@comput3 device-plugins]# journalctl -r -u kubelet
E0604 15:51:53.763503   15104 kuberuntime_manager.go:749] container start failed: CreateContainerConfigError: endpoint not found in cache for a registe
Jun 04 15:51:40 comput3 kubelet[15104]: E0604 15:51:40.764492   15104 pod_workers.go:190] Error syncing pod f1cd0bbd-85cd-11e9-94bf-ac1f6bac1d10 ("gpu-pod_default(f1cd0bbd-85cd-11e9-94bf-ac1f
any help ,i will appreaciate it!
### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Common error checking:
 - [x] The output of `nvidia-smi -a` on your host
 - [x] Your docker configuration file (e.g: `/etc/docker/daemon.json`)
 - [x] The k8s-device-plugin container logs
 - [x] The kubelet logs on the node (e.g: `sudo journalctl -r -u kubelet`)

Additional information that might help better understand your environment and reproduce the bug:
 - [x] Docker version from `docker version`
 - [x] Docker command, image and tag used
 - [x] Kernel version from `uname -a`
 - [x] Any relevant kernel output lines from `dmesg`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [x] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))

**Comment by RenaudWasTaken** [comment]
Hello!

Please reopen an issue with the issue template filled correctly :)
