### ISSUE TITLE
How to leverage the cuda lib on host machine without install cuda in docker image

### ISSUE THREAD

**Issue by Cherishty** [NVIDIA/k8s-device-plugin#121]
### 1. Issue or feature description
When training tensorflow model inner a k8s pod, how to leverage(mount) the cuda lib on `host machine` **without** install cuda in docker image

I try to install **nvidia-driver**, **cuda** and **cudnn** on `HOST machine`,  then mount this **hostpath** via k8s volume.
In this case, the image may only install the python+tensorflow-gpu lib, and config the corresponding `LD_LIBRARY_PATH`, but **NO** need to install(or based on) cuda anymore, which is too heavy, and lose the  for the  flexibility.

In this case:

- `nvidia-smi` return the right value inner container (which means docker runtime and device-plugin daemonset do work)

- `LD_LIBRARY_PATH` is set correctly as 

> /usr/local/cuda-9.0/lib64:/usr/lib64/nvidia
where are the libs of cuda and nvidia driver (especially libcuda.so.1) located in

- 'nvcc -V' return the right value inner container (which means mounted cuda can be recognized inner container)

However: when running python tensor_mnist.py(which will train model leverage GPU). **the error raises** as

> E tensorflow/stream_executor/cuda/cuda_driver.cc:397] failed call to cuInit: CUDA_ERROR_UNKNOWN

We do need this behavior to simplify the image size and enhance flexibility.
Much of appreciate for any suggestion or clues !!! 

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Common error checking:
 - [X] The output of `nvidia-smi -a` on your host
 - [X] Your docker configuration file (e.g: `/etc/docker/daemon.json`)
 - [X] The k8s-device-plugin container logs
 - [X] The kubelet logs on the node (e.g: `sudo journalctl -r -u kubelet`)

Additional information that might help better understand your environment and reproduce the bug:
 - [X] Docker version from `docker version`: 18.09.6
 - [X] Docker command, image and tag used: self build python3.6 and Tensorflow-gpu
 - [X] Kernel version from `uname -a`: 3.10.0-957.1.3.el7.x86_64
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [X] NVIDIA container library version from `nvidia-container-cli -V`: version: 1.0.2
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))

**Comment by xcnick** [comment]
I have the same problem，the solution is add some envs in dockerfile:
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

Don't even need to mount /usr/local/cuda in container.
Give it a try.

**Comment by Cherishty** [comment]
It works! Much of appreciate for your help! @xcnick

**Comment by elezar** [comment]
Hi @srstrickland. What is the value of `NVIDIA_DRIVER_CAPABILITIES` in the container? I would assume that this should at least include `compute` for a TensorFlow image.

Note that the toolkit is only designed to mount driver libraries and the expectation is that runtime libraries or other components of the SDK such as CUDNN / CUBLAS are included in the container. This is the reason that it is required to mount these libraries from the host if they are not present.

Note, one of the things that libnvidia-container does under the hood is to update the ldcache in the container. As such, ensuring that the mounted folder is in the ldcache path should remove the need to set the `LD_LIBRARY_PATH` as the cache would be updated accordingly.

**Comment by srstrickland** [comment]
@elezar thanks for the prompt response!  The logs above were based on using the `all` sledgehammer for `NVIDIA_DRIVER_CAPABILITIES`, which was an easier starting point.  I am now using `compute,utility` and get the same result.  Just confirmed that for tensorflow, it seems only `compute` is necessary.

It makes sense that the toolkit only handles the driver libs, and that other runtime libs have to be mounted; just wanted to check with the experts 😄 .  The [tensorflow docs](https://www.tensorflow.org/install/gpu#software_requirements) are pretty clear that more than just the drivers are needed to leverage the GPU.

Good to know about possibly not needing `LD_LIBRARY_PATH`; I will experiment with that.

Thanks again for the help!
