### ISSUE TITLE
container CrashLoopBackOff error

### ISSUE THREAD

**Issue by pynchon-sjtu** [NVIDIA/k8s-device-plugin#13]
Hi, everyone.
I've got the CrashLoopBackOff error too:
> NAME                                   READY     STATUS             RESTARTS   AGE
> nvidia-device-plugin-daemonset-csjxw   0/1       CrashLoopBackOff   12         39m

However, when i ran the container on the node with nvidia:
`docker run --runtime=nvidia -it -v /var/lib/kubelet/device-plugins:/var/lib/kubelet/device-plugins nvidia/k8s-device-plugin:1.8`
It shows that the device plugin is registered succeessfully, isn't it?
> 2017/12/08 06:41:44 Loading NVML
> 2017/12/08 06:41:45 Starting to serve on /var/lib/kubelet/device-plugins/nvidia.sock
> 2017/12/08 06:41:45 Registered device plugin with Kubelet

And the kubelet has started with --feature-gates=DevicePlugins=true.

By the way, my Nividia is GeForce GTX 1070. 
Why this error came out?

**Comment by flx42** [comment]
What's the log of your daemonset? `kubectl logs nvidia-device-plugin-daemonset-csjxw`

**Comment by flx42** [comment]
I think it's because you didn't set the `nvidia` runtime as the default runtime. You will probably get an error if you do your `docker run` without the `--runtime=nvidia`.
You can add `"default-runtime": "nvidia",` to `/etc/docker/daemon.json`.

**Comment by pynchon-sjtu** [comment]
> I think it's because you didn't set the nvidia runtime as the default runtime. You will probably get an error if you do your docker run without the --runtime=nvidia.
> You can add "default-runtime": "nvidia", to /etc/docker/daemon.json.
yeah, it works! Thanks a lot!

**Comment by pynchon-sjtu** [comment]
> I think it's because you didn't set the nvidia runtime as the default runtime. You will probably get an error if you do your docker run without the --runtime=nvidia.
> You can add "default-runtime": "nvidia", to /etc/docker/daemon.json.

Yeah, it works! Thanks a lot!
