### ISSUE TITLE
Relicensing to Apache2

### ISSUE THREAD

**Issue by RenaudWasTaken** [NVIDIA/k8s-device-plugin#130]
Hello everyone!

We'll be relicensing this repository from BSD3 to an Apache2 License.
This will allow us to move away from the CLA model to a DCO model.

As part of that process, we have two options:

Ask our contributors to approve that change
1. Rollback that change
2. We also think that it's good practice to ask our contributors before we rollback their changes!

So far I've noticed that the following two contributors would need to be contacted:

https://github.com/NVIDIA/k8s-device-plugin/commits?author=ScorpioCPH
https://github.com/NVIDIA/k8s-device-plugin/commits?author=dvavili
https://github.com/NVIDIA/k8s-device-plugin/commits?author=mkumatag

@ScorpioCPH @dvavili @mkumatag are you fine with us relicensing this repository?
Thanks!

**Comment by mkumatag** [comment]
I'm fine converting the license but why you want to roll back the changes?

**Comment by RenaudWasTaken** [comment]
Ah sorry if that wasn't clear, rolling back the changes is the alternative if you don't answer :)

**Comment by dvavili** [comment]
Yes, I'm ok with it.

Thanks, Divya
