### ISSUE TITLE
If NVIDIA k8s-device-plugin support multiple cards the same time

### ISSUE THREAD

**Issue by yechnlin** [NVIDIA/k8s-device-plugin#133]
###  Issue or feature description
1. can NVIDIA k8s-device-plugin support multiple cards the same time?
    for example, **Nvidia GeForce GTX 1080** and **Nvidia GeForce GTX 1060** are ready on one host, if **nvidia.com/gpu** total resource = **Nvidia GeForce GTX 1080** + **Nvidia GeForce GTX 1060** ?

2. if NVIDIA k8s-device-plugin support multiple cards the same time, can pod specified which card it will use?
    for example, the pod only wanna use **Nvidia GeForce GTX 1080**, if yes, how can we specify it?

**Comment by yechnlin** [comment]
@RenaudWasTaken @flx42 can you help to check my questions?

**Comment by Ethyling** [comment]
Hey,

>     1. can NVIDIA k8s-device-plugin support multiple cards the same time?
>        for example, **Nvidia GeForce GTX 1080** and **Nvidia GeForce GTX 1060** are ready on one host, if **nvidia.com/gpu** total resource = **Nvidia GeForce GTX 1080** + **Nvidia GeForce GTX 1060** ?

Yes

>     2. if NVIDIA k8s-device-plugin support multiple cards the same time, can pod specified which card it will use?
>        for example, the pod only wanna use **Nvidia GeForce GTX 1080**, if yes, how can we specify it?

No, but you can hack using environment variables, see: https://github.com/NVIDIA/nvidia-container-runtime#environment-variables-oci-spec

**Comment by klueska** [comment]
> > 2. if NVIDIA k8s-device-plugin support multiple cards the same time, can pod specified which card it will use?
> >    for example, the pod only wanna use **Nvidia GeForce GTX 1080**, if yes, how can we specify it?
> > ```
> 
> No, but you can hack using environment variables, see: https://github.com/NVIDIA/nvidia-container-runtime#environment-variables-oci-spec

I don't think the environment variable hack will give him exactly what he wants either. There is no way for the device plugin (or an environment variable) to currently control which GPUs are handed out to a container by the kubelet's devicemanager.

**Comment by yechnlin** [comment]
> I don't think the environment variable hack will give him exactly what he wants either. There is no way for the device plugin (or an environment variable) to currently control which GPUs are handed out to a container by the kubelet's devicemanager.

I agree with you.

So for a pod which wanna use GPU resource, kubelet's devicemanager will allocate a random free resource via device plugin from `Nvidia GeForce GTX 1060` or `Nvidia GeForce GTX 1080`, for kubelet's devicemanager, it just care the free resource, but not taking care of the device.

Above is my understanding, is it right?

thanks. :)
