### ISSUE TITLE
what's the difference between v1.8 and v1.9?

### ISSUE THREAD

**Issue by pineking** [NVIDIA/k8s-device-plugin#14]
I mean:
Does k8s-device-plugin:v1.8 only work for kubernetes:v1.8.x , 
k8s-device-plugin:v1.9 -> kubernetes:v1.9.x? 

could we use k8s-device-plugin:v1.9 for kubernetes:v1.8.x?

**Comment by RenaudWasTaken** [comment]
Hello @pineking !

Unfortunately during the 1.9 development, the device plugin API changed and is no longer compatible with the 1.8 version.

You'll have to use:
- k8s-device-plugin:v1.9 for Kubernetes 1.9
- k8s-device-plugin:v1.8 for Kubernetes 1.8

Will update the README to have a section displaying this :)
