### ISSUE TITLE
nvidia/k8s-device-plugin:1.0.0-beta3 image is missing from docker hub

### ISSUE THREAD

**Issue by jucrouzet** [NVIDIA/k8s-device-plugin#140]
$ docker pull nvidia/k8s-device-plugin:1.0.0-beta3
Error response from daemon: manifest for nvidia/k8s-device-plugin:1.0.0-beta3 not found: manifest unknown: manifest unknown

**Comment by jucrouzet** [comment]
When I build it, i get : 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8414d7]

goroutine 1 [running]:
main.getDevices(0xc4200c3e38, 0x1, 0x1)
	/go/src/nvidia-device-plugin/nvidia.go:49 +0x177
main.main()
	/go/src/nvidia-device-plugin/main.go:42 +0x111

**Comment by RenaudWasTaken** [comment]
I just restarted the pipeline, the image should be there in a few minutes or so.
@klueska looks like nvml has a Segfaults on here: https://github.com/NVIDIA/k8s-device-plugin/blob/0b12465110bae6f516510001e6c29d9e697252dd/nvidia.go#L49

**Comment by rockrush** [comment]
@jucrouzet @RenaudWasTaken  Pull request #141 fixes the problem(hopefully), please try and verify.

**Comment by klueska** [comment]
@RenaudWasTaken I left a comment on https://github.com/NVIDIA/k8s-device-plugin/pull/141

If d.CPUAffinity is Nil then we should just not set the Topology field of the device at all.

When is it the case that d.CPUAffinity is not set, such that this occurs?

**Comment by zplizzi** [comment]
I'm getting the same error.

I installed the plugin as recommended on the main Readme.md with
`kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/1.0.0-beta3/nvidia-device-plugin.yml`

Here's the logs for the pod running on an AWS p3.2xlarge instance:

```bash
% kubectl logs -n kube-system nvidia-device-plugin-daemonset-4h5pl
2019/10/11 19:06:30 Loading NVML
2019/10/11 19:06:30 Fetching devices.
2019/10/11 19:06:30 Shutdown of NVML returned: <nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8414d7]

goroutine 1 [running]:
main.getDevices(0xc42006fe38, 0x1, 0x1)
        /go/src/nvidia-device-plugin/nvidia.go:49 +0x177
main.main()
        /go/src/nvidia-device-plugin/main.go:42 +0x111
```

Is there a recommended version to install instead that should work?

**Comment by zplizzi** [comment]
Dropping back to the previous version seems to work. Uninstalled broken version with

`kubectl delete daemonset nvidia-device-plugin-daemonset -n kube-system`

and installed previous version (beta instead of beta3) with

`kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/1.0.0-beta/nvidia-device-plugin.yml`

**Comment by klueska** [comment]
No release has been made with this fix in it yet.

**Comment by klueska** [comment]
Fix released: https://github.com/NVIDIA/k8s-device-plugin/releases/tag/1.0.0-beta4
