### ISSUE TITLE
deploying 1.0.0-beta3 daemonset to AWS EKS w/ 1.14.6 doesn't work

### ISSUE THREAD

**Issue by philvarner** [NVIDIA/k8s-device-plugin#142]
### 1. Issue or feature description

deploying latest daemonset (nvidia-device-plugin.yml) to AWS EKS w/ 1.14.6 doesn't work. When I deploy this, I see no GPUs available with `kubectl get nodes -o=custom-columns=NAME:.metadata.name,GPUs:.status.capacity.'nvidia\.com/gpu'`  

When I use the v1.12 branch, I can see the GPUs. 

I also noticed this file `extensions-v1beta1-nvidia-device-plugin.yml` had recently been added, 
but there's no documentation as to what it's for.

### 2. Steps to reproduce the issue

1. Create an AWS EKS nodegroup with GPUs (p2.xlarge).
2. run `kubectl create -f nvidia-device-plugin.yml` with the file in the 1.0.0-beta3 tag.
3. Run `kubectl get nodes -o=custom-columns=NAME:.metadata.name,GPUs:.status.capacity.'nvidia\.com/gpu'` to see that the GPUs are visible.  They never are, even after a wait.

**Comment by calclavia** [comment]
I have a similar issue here. I notice the dameon crashes with some null pointer memory error, and if I revert back to v1.11 it works.

**Comment by klueska** [comment]
This should be fixed by https://github.com/NVIDIA/k8s-device-plugin/pull/141, but no new release has been published, it looks like.

**Comment by klueska** [comment]
Fix released: https://github.com/NVIDIA/k8s-device-plugin/releases/tag/1.0.0-beta4

**Comment by philvarner** [comment]
Worked for me!
