### ISSUE TITLE
Requirements for k8s-device-plugin

### ISSUE THREAD

**Issue by Kaka1127** [NVIDIA/k8s-device-plugin#144]
Would anyone be clarified the software requirements for each k8s-device-plugin version as below?
  - k8s-device-plugin
  - K8s
  - docker-ce
  - nvidia-docker2
  - nvidia-container-toolkit
 -  nvidia-driver

My understanding are below.

| Software | Version ||
|:-----------|:------------|:------------|
| k8s-device-plugin |   v1.12 | 1.0.0-beta4 |
|  K8s | 1.12 | >=1.16 |
| docker-ce | 18.06 | 19.03 |
| nvidia-docker2 | nvidia-docker2=2.0.0+docker18.06.3-3 | Not Support |
| nvidia-container-toolkit | Not Support | 1.0.x |
| nvidia-driver | >=361.93 | >=361.93 |

Best regards.
Kaka

**Comment by RenaudWasTaken** [comment]
Sorry for the late answer, hope this helps:
- K8s >= 1.12
- k8s-device-plugin >= 1.0.0-beta
- Docker > 18.06.X
- nvidia-docker2 >2.1.0
