### ISSUE TITLE
How to disable the specified GPU in the pod in kubernetes? 

### ISSUE THREAD

**Issue by kuaiwenwu** [NVIDIA/k8s-device-plugin#146]
How to disable the specified GPU in the pod in kubernetes? For example, I assigned three GPUs to a pod. I want to trigger to disable the first card and how to implement it.

**Comment by RenaudWasTaken** [comment]
Hello!

This is currently not supported and we don't really have a plan to support it.
Can you tell us more about the context of this request?

**Comment by RenaudWasTaken** [comment]
Actually re-reading your question, you might want to take a look at the CUDA_VISIBLE_DEVICES environment variable that controls what devices a specific CUDA process can see:
https://devblogs.nvidia.com/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/
