### ISSUE TITLE
Access cross-node GPU from a pod

### ISSUE THREAD

**Issue by jobvarkey** [NVIDIA/k8s-device-plugin#147]
Hello,

I have a 6 worker nodes (bare metal servers) on-prem kubernetes cluster and each node has two Nvidia GPUs. I have the requirement for running AIML pods that needs more than two GPUs. The pod goes into pending state with waiting for resources when given more than 2 GPUs.

Is there a way to access cross-node GPUs from a pod?
Any help/advise is greatly appreciated.

Thanks,
Job Varkey

**Comment by RenaudWasTaken** [comment]
Hello!

This is normal Kubernetes resources, if your pod requests more CPU resources than available on any single node in your cluster it will never get scheduled.

In your case, if you need more than 2 GPUs, the trick is to create multiple pods (3) each requesting the maximum amount of GPUs available on a single node (2).

Hope this helps!

**Comment by jobvarkey** [comment]
Thanks for the response..
