### ISSUE TITLE
device-plugin crashes but failed quitting

### ISSUE THREAD

**Issue by xial-thu** [NVIDIA/k8s-device-plugin#152]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._
---

### 1. Issue or feature description
device-plugin pod crashes but failed quitting

### 2. Steps to reproduce the issue
cannot reproduce

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

docker image version: nvidia/k8s-device-plugin:1.0.0-beta4

I noticed that pods will use the same GPUs even though device-plugin is running. I've started 2 pods, each of which requests 4 GPU.

![image](https://user-images.githubusercontent.com/24671561/72125438-8c044f80-33a3-11ea-9bfc-24c0ddee83a9.png)

The logs of device-plugin pod showed:

>2019/12/11 09:29:28 Loading NVML
2019/12/11 09:29:28 Fetching devices.
2019/12/11 09:29:28 Starting FS watcher.
2019/12/11 09:29:28 Starting OS watcher.
2019/12/11 09:29:28 Starting GRPC server
2019/12/11 09:29:28 Starting to serve on /var/lib/kubelet/device-plugins/nvidia.sock
2019/12/11 09:29:28 Registered device plugin with Kubelet
2019/12/11 13:47:57 GRPC server crashed with error: accept unix /var/lib/kubelet/device-plugins/nvidia.sock: accept4: too many open files in system
2019/12/11 13:49:33 Starting GRPC server
2019/12/11 13:58:43 GRPC server crashed with error: accept unix /var/lib/kubelet/device-plugins/nvidia.sock: use of closed network connection
2019/12/11 14:00:18 Starting GRPC server
2019/12/11 14:07:24 GRPC server crashed with error: accept unix /var/lib/kubelet/device-plugins/nvidia.sock: use of closed network connection
2019/12/11 14:10:23 Starting GRPC server
2019/12/11 14:21:43 GRPC server crashed with error: accept unix /var/lib/kubelet/device-plugins/nvidia.sock: use of closed network connection
2019/12/11 14:24:00 Starting GRPC server
2019/12/11 14:32:59 GRPC server crashed with error: accept unix /var/lib/kubelet/device-plugins/nvidia.sock: use of closed network connection
2019/12/11 14:35:56 Starting GRPC server
2019/12/11 14:47:14 GRPC server crashed with error: accept unix /var/lib/kubelet/device-plugins/nvidia.sock: use of closed network connection
2019/12/11 14:50:42 Starting GRPC server
2019/12/11 15:10:04 GRPC server crashed with error: accept unix /var/lib/kubelet/device-plugins/nvidia.sock: use of closed network connection
2019/12/11 15:16:23 GRPC server has repeatedly crashed recently. Quitting

Device-plugin is still running. And it seems grpc cannot recover from "too many open files in system" error.

Then I deleted the pod but it stuck on Terminating.

> nvidia-device-plugin-daemonset-4lxm8         1/1     Terminating   1          30d

Related issue is https://github.com/grpc/grpc/issues/16058. That bug has been fixed already. I'll be nice if updating grpc can solve this problem. Also I'm confused why pod will be stuck on terminating?

**Comment by RenaudWasTaken** [comment]
Sorry for answering this late, I'll keep this open for now, we've been rewriting some parts of the device plugin and will consider updating gRPC in the next release :)
