### ISSUE TITLE
Orphaned pods with "OutOfnvidia.com/gpu" status

### ISSUE THREAD

**Issue by logicbomb421** [NVIDIA/k8s-device-plugin#153]
### 1. Issue or feature description

We have a set of pods running on a GKE cluster that need GPUs. We have initialized the cluster with GPU resources by following the [GKE documentation on how to do so](https://cloud.google.com/kubernetes-engine/docs/how-to/gpus).  Our current design requires us to only schedule one gpu-workload on a single node, as we only have one GPU attached to each. We have the cluster autoscaler turned on, that will allow node growth between 0 and our GCP project GPU quota. We are also using preemptable nodes/GPUs.

For the most part, everything is scheduling as expected. Occasionally, however, we will notice a replica of a deployment end up with a status of `OutOfnvidia.com/gpu`. The actual deployment will have the correct number of replicas, because a new one will spin up and (seemingly) take the place of the replica that started reporting `OutOfnvidia.com/gpu`. This leaves two pods on a node with a single GPU:

- one that is running fine, and
- one that is unschedulable due to `OutOfnvidia.com/gpu`

The pod that is sitting unschedulable shows the following event:

```
Node didn't have enough resource: nvidia.com/gpu, requested: 1, used: 0, capacity: 0
```

`capacity:0` here seems a bit odd to me, as even if we couldn't schedule anything, we should still see the device, no?

### 2. Steps to reproduce the issue

I cannot deduce a pattern in this issue that lets me reproduce it. The only thing I have done that sometimes seems to cause the issue is manually scaling the deployment replica count up or down.

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Common error checking:
 - [x] The output of `nvidia-smi -a` on your host

```
Sat Jan 25 01:10:35 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P0    38W / 250W |   2553MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     17563      C   python                                      2543MiB |
+-----------------------------------------------------------------------------+
```

 - [x] Your docker configuration file (e.g: `/etc/docker/daemon.json`)

```
{
	"disable-legacy-registry": true,
	"live-restore": true,
	"storage-driver": "overlay2"
}
```

(This seems odd to me because it is _not_ what is listed in the README in this repository, however it _is_ what GCP seems to need to do to make things work?)

 - [x] The k8s-device-plugin container logs

```
I0125 00:08:08.805603       1 nvidia_gpu.go:41] device-plugin started
I0125 00:08:49.405514       1 manager.go:83] Found Nvidia GPU "nvidia0"
I0125 00:08:49.405565       1 manager.go:179] will use alpha API
I0125 00:08:49.405572       1 manager.go:193] starting device-plugin server at: /device-plugin/nvidiaGPU-1579910929.sock
I0125 00:08:49.405773       1 manager.go:222] device-plugin server started serving
I0125 00:08:49.406328       1 manager.go:226] falling back to v1beta1 API
I0125 00:08:49.410234       1 manager.go:234] device-plugin registered with the kubelet
I0125 00:08:49.506190       1 beta_plugin.go:39] device-plugin: ListAndWatch start
I0125 00:08:49.506219       1 beta_plugin.go:47] ListAndWatch: send devices &ListAndWatchResponse{Devices:[&Device{ID:nvidia0,Health:Healthy,}],}
```

 - [x] The kubelet logs on the node (e.g: `sudo journalctl -r -u kubelet`)

[kublet.log](https://github.com/NVIDIA/k8s-device-plugin/files/4111504/kublet.log)

(Interestingly after looking through these, I'm only finding the pod name for the final replica that stays running. The other replicas don't seem to ever be mentioned in here?) 

Additional information that might help better understand your environment and reproduce the bug:
 - [x] Docker version from `docker version`

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.10.3
 Git commit:   f5ec1e2
 Built:        Mon Aug 26 22:42:10 2019
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.10.3
 Git commit:   f5ec1e2
 Built:        Mon Aug 26 22:42:10 2019
 OS/Arch:      linux/amd64
 Experimental: false
```

 - [ ] Docker command, image and tag used
 - [x] Kernel version from `uname -a`

```
Linux gke-production-01-gpu-pool-highmem-p1-6b59ae7c-39mz 4.14.138+ #1 SMP Mon Aug 26 22:41:20 PDT 2019 x86_64 Intel(R) Xeon(R) CPU @ 2.20GHz GenuineIntel GNU/Linux
```

 - [ ] Any relevant kernel output lines from `dmesg`

I'm not sure what would be relevant here, there are >400 lines or so. I'll be happy to provide this if anyone has specifics they need to see.

 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))

<hr/>

Please let me know if I can provide any additional information. Thanks for any help!

**Comment by klueska** [comment]
If you are running on GKE, then you are not using Nvidia's k8s-device-plugin. GKE has its own device  plugin implementation as described here: https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/#deploying-nvidia-gpu-device-plugin
