### ISSUE TITLE
limits and requests not working

### ISSUE THREAD

**Issue by dahvid** [NVIDIA/k8s-device-plugin#154]
This applies up to k8s version 1.15.2, I have not tested it on more recent versions.

### 1. Issue or feature description
You cannot set a range of GPU’s to schedule to.  For example, if a Pod wants to run on at least 1 GPU but as many as 3.  For a normal resource you would set.

        resources:
          limits:
            nvidia.com/gpu: 3
          requests:
               nvidia.com/gpu:1

Doing this currently results in the error message:

The Job "multi-gpu-test-0" is invalid: spec.template.spec.containers[0].resources.requests: Invalid value: "1": must be equal to nvidia.com/gpu limit

This limitation is mentioned in the documentation, but it means that we cannot launch Jobs that dynamically request and receive different GPU resources.

**Comment by RenaudWasTaken** [comment]
Hello!

This is an issue with Kubernetes, you definitely should open an issue on that repo :)
