### ISSUE TITLE
Is there any k8s-device-plugin image for ARM64 processor

### ISSUE THREAD

**Issue by rshiva777** [NVIDIA/k8s-device-plugin#155]
I am not able to install the device plugins in ARM64 architecture kubernetes node.

**Comment by rshiva777** [comment]
I am trying to install the plugins on jetson board (ARM64 Bit). But i am getting the below error

**Events:**
  Type     Reason     Age                     From                     Message
  ----     ------     ----                    ----                     -------
  Normal   Scheduled  9m19s                   default-scheduler        Successfully assigned kube-system/nvidia-device-plugin-daemonset-4vt2t to nvidia-desktop
  Normal   Pulling    7m6s (x4 over 9m17s)    kubelet, nvidia-desktop  Pulling image "nvidia/k8s-device-plugin:1.0.0-beta4"
  Warning  Failed     7m1s (x4 over 8m58s)    kubelet, nvidia-desktop  Failed to pull image "nvidia/k8s-device-plugin:1.0.0-beta4": rpc error: code = Unknown desc = no matching manifest for linux/arm64/v8 in the manifest list entries
  Warning  Failed     7m1s (x4 over 8m58s)    kubelet, nvidia-desktop  Error: ErrImagePull
  Warning  Failed     6m48s (x6 over 8m57s)   kubelet, nvidia-desktop  Error: ImagePullBackOff
  Normal   BackOff    4m10s (x17 over 8m57s)  kubelet, nvidia-desktop  Back-off pulling image "nvidia/k8s-device-plugin:1.0.0-beta4"

**In logs i am able to see the below info:**
root@node3:~/fccl# kubectl logs -f nvidia-device-plugin-daemonset-4vt2t  -n kube-system
Error from server (BadRequest): container "nvidia-device-plugin-ctr" in pod "nvidia-device-plugin-daemonset-4vt2t" is waiting to start: image can't be pulled

**Comment by RenaudWasTaken** [comment]
Hello!

There are no device plugins for the Jetson platform. This is part of our roadmap but won't land until we are done with our work at the runtime level.

**Comment by indukuri-varma** [comment]
Hello,

Is there device plugins for the Jetson platform available now?im facing the same issue as above

**Comment by krinsang** [comment]
> Hello,
> 
> Is there k8s-device plugins for the Jetson platform available now?I'm facing the same issue as above

bump

**Comment by elezar** [comment]
Hi @krinsang. The jetson platform is not yet supported, although we are working at getting support for this in the future. We're not quite ready to publish a timeline though.
