### ISSUE TITLE
Docker Container nvidia/k8s-device-plugin:1.9 Reporting Error

### ISSUE THREAD

**Issue by nautilusshell** [NVIDIA/k8s-device-plugin#156]
### 1. Issue or feature description
I have done steps by [Quick-Start](https://github.com/NVIDIA/k8s-device-plugin#quick-start), but when I tried to start the test case, it keeps reporting error. And there is also no GPU message from the output of command "kubectl describe node gpu_node_name".       

> 2020/02/09 00:20:15 Starting to serve on /var/lib/kubelet/device-plugins/nvidia.sock
2020/02/09 00:20:15 Could not register device plugin: rpc error: code = Unimplemented desc = unknown service deviceplugin.Registration
2020/02/09 00:20:15 Could not contact Kubelet, retrying. Did you enable the device plugin feature gate?
2020/02/09 00:20:15 You can check the prerequisites at: https://github.com/NVIDIA/k8s-device-plugin#prerequisites
2020/02/09 00:20:15 You can learn how to set the runtime at: https://github.com/NVIDIA/k8s-device-plugin#quick-start
 
### 2. Steps to reproduce the issue
- exec shell cmd
       docker run --security-opt=no-new-privileges --cap-drop=ALL --network=none -it -v /var/lib/kubelet/device-plugins:/var/lib/kubelet/device-plugins nvidia/k8s-device-plugin:1.9
- check the output

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

- outputs of `nvidia-docker run --rm dlws/cuda nvidia-smi`

               +-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.48.02    Driver Version: 440.48.02    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:0B:00.0 Off |                    0 |
| N/A   35C    P0    27W / 250W |      0MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

- outputs of `nvidia-docker run --rm dlws/cuda nvidia-smi`
      `    
 +-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.48.02    Driver Version: 440.48.02    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:0B:00.0 Off |                    0 |
| N/A   35C    P0    27W / 250W |      0MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
`

- contents of /etc/docker/daemon.json
   `
{          
    "default-runtime": "nvidia",              
    "registry-mirrors": ["https://registry.docker-cn.com"],           
    "runtimes": {        
        "nvidia": {      
            "path": "nvidia-container-runtime",           
            "runtimeArgs": []           
        }       
    }     
}           
`
- docker version: 19.03.2   
- kubernetes version: 1.15.2

**Comment by RenaudWasTaken** [comment]
Hello!

We can probably start by running the latest tag: `1.0.0-beta4`
