### ISSUE TITLE
k8s1.15.2 && nvidia 2080ti graphics card limit GPU number invalid?

### ISSUE THREAD

**Issue by kuaiwenwu** [NVIDIA/k8s-device-plugin#161]
The version of k8s is: v1.15.2
My nvidia-plugin version is: nvidia / k8s-device-plugin: 1.0.0-beta

Symptom:
Recently, I installed a new GPU server with 6 GPUs of nvidia 2080ti. After installing the driver and adding the k8s node, the number of GPUs allocated by my bert-A application released at this time is 2, but I enter nvidia in my container -smi found that there are 6 graphics cards available, which looks like a limited failure, but I re-released a Bert-B and the number of container allocations for a test was set to 5, at this time, the prompt is pending, which really limits the server GPU. Number, but now enter Bert-B and specify nvidia-smi and find that 6 graphics cards are also available. I am worried that there will be conflicts when using later programs. Is there a bug and how to solve it?
Details are as follows:

[root@bert-A simba-bert]# nvidia-smi 
Thu Apr  2 15:25:19 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64       Driver Version: 440.64       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:1A:00.0 Off |                  N/A |
| 27%   24C    P8    22W / 250W |    862MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:1B:00.0 Off |                  N/A |
| 27%   24C    P8     9W / 250W |    862MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  Off  | 00000000:3E:00.0 Off |                  N/A |
| 27%   24C    P8    21W / 250W |      0MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  Off  | 00000000:88:00.0 Off |                  N/A |
| 26%   24C    P8     2W / 250W |      0MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce RTX 208...  Off  | 00000000:89:00.0 Off |                  N/A |
| 27%   24C    P8    18W / 250W |      0MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce RTX 208...  Off  | 00000000:B1:00.0 Off |                  N/A |
| 27%   24C    P8    14W / 250W |      0MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

[root@bert-b simba-bert]# nvidia-smi 
Thu Apr  2 16:25:19 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64       Driver Version: 440.64       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:1A:00.0 Off |                  N/A |
| 27%   24C    P8    22W / 250W |    862MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:1B:00.0 Off |                  N/A |
| 27%   24C    P8     9W / 250W |    862MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  Off  | 00000000:3E:00.0 Off |                  N/A |
| 27%   24C    P8    21W / 250W |      0MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  Off  | 00000000:88:00.0 Off |                  N/A |
| 26%   24C    P8     2W / 250W |      0MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce RTX 208...  Off  | 00000000:89:00.0 Off |                  N/A |
| 27%   24C    P8    18W / 250W |      0MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce RTX 208...  Off  | 00000000:B1:00.0 Off |                  N/A |
| 27%   24C    P8    14W / 250W |      0MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

**Comment by RenaudWasTaken** [comment]
> Recently, I installed a new GPU server with 6 GPUs of nvidia 2080ti. After installing the driver and adding the k8s node, the number of GPUs allocated by my bert-A application released at this time is 2, but I enter nvidia in my container -smi found that there are 6 graphics cards available, which looks like a limited failure

Pretty sure your pod isn't requesting any GPUs, see an example below: 
```
apiVersion: v1
kind: Pod
metadata:
  name: cuda-vector-add
spec:
  restartPolicy: OnFailure
  containers:
    - name: cuda-vector-add
      # https://github.com/kubernetes/kubernetes/blob/v1.7.11/test/images/nvidia-cuda/Dockerfile
      image: "k8s.gcr.io/cuda-vector-add:v0.1"
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
```

Can you paste your pod spec?

**Comment by kuaiwenwu** [comment]
I found that other GPU project pods on my k8s are limited and normal. I also compared the deployment configuration of bert-a. It ’s all strange.


[root@SH-IDC-PRD-K8S-ANSIBLE0001 ~]# kubectl describe pods bert-A
Name:           simba-bert-676c77f4f9-tcxvd
Namespace:      default
Priority:       0
Node:           10.20.0.40/10.20.0.40
Start Time:     Thu, 02 Apr 2020 16:40:51 +0800
Labels:         app=simba-bert
                pod-template-hash=676c77f4f9
                version=master
Annotations:    <none>
Status:         Running
IP:             172.20.7.12
Controlled By:  ReplicaSet/simba-bert-676c77f4f9
Containers:
  simba-bert:
    Container ID:   docker://0c08b2db8f3fb6868dfd7960bff2a1152ebfb8cc737edc82635509c68ed65a55
    Image:          idc-registry.ihomefnt.com:15000/python-simba-bert:v9
    Image ID:       docker-pullable://x.x.x.x:15000/python-simba-bert@sha256:362daf5d40ddb2b4a22d7cd855fd49983719f536554a16a16cf7289525e9c91d
    Ports:          80/TCP, 9999/TCP, 5080/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP
    State:          Running
      Started:      Thu, 02 Apr 2020 16:40:53 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:             2
      memory:          6Gi
      nvidia.com/gpu:  2
    Requests:
      cpu:             200m
      memory:          6Gi
      nvidia.com/gpu:  2
    Environment:
      HOST_IP:       (v1:spec.nodeName)
      runningMode:  docker
      tm_memory:    2000m 6Gi
      app_name:     simba-bert
    Mounts:
      /etc/localtime from time (rw)
      /opt/ihome/simba-bert/logs from log-simba-bert (rw)
      /opt/ihome/simba-bert/service_model from models-simba-bert (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-x4drp (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  models-simba-bert:
    Type:      NFS (an NFS mount that lasts the lifetime of a pod)
    Server:    10.20.20.166
    Path:      /fuxi-models/simba-bert-prd/service_model
    ReadOnly:  false
  log-simba-bert:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/ihome/logs/simba-bert
    HostPathType:  
  time:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/localtime
    HostPathType:  
  default-token-x4drp:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-x4drp
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From                 Message
  ----    ------     ----  ----                 -------
  Normal  Scheduled  11m   default-scheduler    Successfully assigned default/simba-bert-676c77f4f9-tcxvd to 10.20.0.40
  Normal  Pulling    11m   kubelet, 10.20.0.40  Pulling image "idc-registry.ihomefnt.com:15000/python-simba-bert:v9"
  Normal  Pulled     11m   kubelet, 10.20.0.40  Successfully pulled image "idc-registry.ihomefnt.com:15000/python-simba-bert:v9"
  Normal  Created    11m   kubelet, 10.20.0.40  Created container simba-bert
  Normal  Started    11m   kubelet, 10.20.0.40  Started container simba-bert

**Comment by kuaiwenwu** [comment]
I used a pod to test the GPU and found that there was no problem.
So why ca n’t I limit bert-a? This should not be related to the mirror environment, right?
Here are the pods I tested and their configuration and status
cat gpu-test.yaml:
```python
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    #- name: cuda-container
    #  image: nvidia/cuda:9.0-devel
    #  resources:
    #    limits:
    #      nvidia.com/gpu: 2 # requesting 2 GPUs
    - name: digits-container
      image: nvidia/digits:6.0
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 2 GPUs
```
```python
root@gpu-pod:/# nvidia-smi 
Thu Apr  2 09:25:32 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64       Driver Version: 440.64       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:1A:00.0 Off |                  N/A |
| 27%   27C    P2    66W / 250W |   1021MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

**Comment by kuaiwenwu** [comment]
> > Recently, I installed a new GPU server with 6 GPUs of nvidia 2080ti. After installing the driver and adding the k8s node, the number of GPUs allocated by my bert-A application released at this time is 2, but I enter nvidia in my container -smi found that there are 6 graphics cards available, which looks like a limited failure
> 
> Pretty sure your pod isn't requesting any GPUs, see an example below:
> 
> ```
> apiVersion: v1
> kind: Pod
> metadata:
>   name: cuda-vector-add
> spec:
>   restartPolicy: OnFailure
>   containers:
>     - name: cuda-vector-add
>       # https://github.com/kubernetes/kubernetes/blob/v1.7.11/test/images/nvidia-cuda/Dockerfile
>       image: "k8s.gcr.io/cuda-vector-add:v0.1"
>       resources:
>         limits:
>           nvidia.com/gpu: 1 # requesting 1 GPU
> ```
> 
> Can you paste your pod spec?

Could you please read my reply, thank you？

**Comment by kuaiwenwu** [comment]
I kept testing and found that the deployment increased
```shell
securityContext:
  privileged: true
```
There will be NVIDIA SMI, six video cards

If you remove this field, you can only see the limited number of graphics cards,

Is this NVIDIA plugin related

**Comment by RenaudWasTaken** [comment]
This is the expected behavior, see: https://github.com/NVIDIA/nvidia-docker/issues/764
