### ISSUE TITLE
Reuse the first gpu when there are multiple gpu training tasks

### ISSUE THREAD

**Issue by alwaysdark** [NVIDIA/k8s-device-plugin#163]
Run the training task using kubeflow's tfjob.

![image](https://user-images.githubusercontent.com/27042739/79197628-a9dec600-7e64-11ea-81ac-014697c10f2b.png)
![image](https://user-images.githubusercontent.com/27042739/79197743-ddb9eb80-7e64-11ea-8a13-4c145badd803.png)

When I run a gpu training task everything works fine,

When I run multiple gpu training tasks, each task tries to use the first gpu,until the first gpu is full.
The result is the training task report an OOM exception

**Comment by alwaysdark** [comment]
![微信图片_20200414154703](https://user-images.githubusercontent.com/27042739/79199219-3ee2be80-7e67-11ea-8585-18df19c2d089.png)
![微信图片_20200414154712](https://user-images.githubusercontent.com/27042739/79199225-40ac8200-7e67-11ea-80c2-3c6b7de32ca3.png)

**Comment by dpressel** [comment]
I am having this same issue with both PyTorch Elastic and Kubeflow's PyTorchJob CRDs.  When I schedule multi-worker jobs via those CRDs to Kubernetes, the workers to be scheduled onto the same devices:

The last column contains the PIDs allocated to the GPU, and both are from successive scheduling via the ElasticJob operator
```
research2 | 04  | GeForce GTX 1080 Ti | NO   | /usr/bin/python3.6 /usr/bin/python3.6 | 12687 16510
research2 | 05  | GeForce GTX 1080 Ti | NO   | /usr/bin/python3.6 /usr/bin/python3.6 | 12679 16484
research2 | 06  | GeForce GTX 1080 Ti | NO   | /usr/bin/python3.6 /usr/bin/python3.6 | 12685 16481
research2 | 07  | GeForce GTX 1080 Ti | NO   | /usr/bin/python3.6 /usr/bin/python3.6 | 12677 16498
research2 | 08  | GeForce GTX 1080 Ti | NO   | /usr/bin/python3.6 /usr/bin/python3.6 | 12682 16508
research2 | 0B  | GeForce GTX 1080 Ti | NO   | /usr/bin/python3.6 /usr/bin/python3.6 | 12691 16441
research2 | 0C  | GeForce GTX 1080 Ti | NO   | /usr/bin/python3.6 /usr/bin/python3.6 | 12689 16571
research2 | 0D  | GeForce GTX 1080 Ti | NO   | /usr/bin/python3.6 /usr/bin/python3.6 | 12683 16490
```
I was hoping that if we updated to the latest version of `k8s-device-plugin` the issue would be resolved but this occurs even on 0.7.1.

The k8s docs (and other tickets in this tracker) seem to claim this isnt possible so I assume that there is a bug:_ https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/

"Containers (and Pods) do not share GPUs. There's no overcommitting of GPUs."

**Comment by dpressel** [comment]
In my case it appears I was able to fix by setting `nvidia.com/gpu`:

```
            resources:
              limits:
                nvidia.com/gpu: 1
```

**Comment by klueska** [comment]
@dpressel how were you requesting the GPUs before, if not via:
```
            resources:
              limits:
                nvidia.com/gpu: 1
```

If you don't set this at all, and your job lands on a node with GPUs, it will consume all of them by default

**Comment by dpressel** [comment]
we were using code to generate the kubernetes request via the API and it was erroneously setting the limit to `0`, which did not try to take all GPUs on the machine (there are 10 as I mentioned), but did allow scheduling to the same 8 workers again
