### ISSUE TITLE
Can I disable the device plugin pod for an individual node?

### ISSUE THREAD

**Issue by dredwilliams** [NVIDIA/k8s-device-plugin#17]
I have a mixed cluster -- some nodes with GPUs, some without.  The plugins start up nicely on the GPU nodes, but not so much on the nodes without GPUs (obviously).

The implementation uses a DaemonSet, so each node gets a pod ... but the pod on the non-GPU node is in CrashLoopBackOff -- I assume because of the lack of GPU.  My question is whether I can set a flag/label/something to tell the pod running on the non-GPU node to just stop trying?  I'd rather not just leave it there continually trying to restart ...

**Comment by flx42** [comment]
@RenaudWasTaken didn't we say that we should do an infinite loop in this case?

**Comment by dredwilliams** [comment]
Just to see if it would make a difference, I installed the drivers, cuda libs, and container runtime on the non-GPU nodes.  The error changed to:  "nvidia-container-cli: initialization error: cuda error: unknown error"

@flx42 I'd suggest an infinite sleep ... we don't want to consume CPU resources unnecessarily.

Thanks!

**Comment by flx42** [comment]
Sure sure, that's what I meant. Like this: https://github.com/NVIDIA/k8s-device-plugin/blob/v1.9/main.go#L26

**Comment by dredwilliams** [comment]
Unless I'm mistaken, that error message is coming from the container runtime when it's trying to set up before it runs the plugin.  This might need to be a mod to the nvidia-container runtime?

**Comment by flx42** [comment]
No, you just shouldn't install the runtime and the driver on a non-GPU node.
And then we will just need to modify this line:
https://github.com/NVIDIA/k8s-device-plugin/blob/v1.9/main.go#L19

**Comment by dredwilliams** [comment]
@flx42 I replaced the exit() with the select {} as you suggested and it now behaves nicely.  Thanks!

**Comment by RenaudWasTaken** [comment]
@dredwilliams thanks for reporting this! Fixed in the latest version :)
Images will pushed to the Docker Hub shortly
