### ISSUE TITLE
Following the QuickStart but my pod is stuck in pending state

### ISSUE THREAD

**Issue by dwschulze** [NVIDIA/k8s-device-plugin#176]
I've followed the QuickStart instructions down to the Docs section on my two nodes.  I took the .yaml shown in the Running GPU Jobs section and ran it from the master with

`kubectl apply -f nvidia.cuda.yaml`

I had modified the .yaml to set `nvidia.com/gpu: 1` because I only have one gpu on each of my nodes.  However my pod stays in the pending state:

```
$ kubectl get pods
NAME      READY   STATUS    RESTARTS   AGE
gpu-pod   0/2     Pending   0          24h
```

I've verified that cuda binaries run on both nodes.

Are there other steps I need to take to get this plugin to execute gpu jobs?  Is it necessary to execute any of the steps below the Docs section such as the `With Docker Build` section because [Option 2 fails](https://github.com/NVIDIA/k8s-device-plugin/issues/175)?

It's not clear what the steps below the Docs section are for.

I'm running on Ubuntu 18.04 with kubernetes 1.18.2.  

$ nvidia-smi
Sun May 31 10:54:58 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 440.82       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P6000        Off  | 00000000:09:00.0 Off |                  Off |
| 26%   23C    P8     8W / 250W |      0MiB / 24449MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by dwschulze** [comment]
Running `kubectl describe nodes` shows that I have 0 gpus allocatable, which would explain why my pods don't get out of pending state.  The plugin is not recognizing my gpus.

**Comment by klueska** [comment]
You seem to have followed all of the instructions correctly, and your driver seems to be working properly, since you can run `nvidia-smi` on the host.

Can you verify your `nvidia-docker2` installation by running the following:
```
docker run nvidia/cuda nvidia-smi
```

**Comment by dwschulze** [comment]
Did you mean `nvidia-docker run nvidia/cuda nvidia-smi` ?

```
$ docker run nvidia/cuda nvidia-smi
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"nvidia-smi\": executable file not found in $PATH": unknown.
```

```
$ nvidia-docker run nvidia/cuda nvidia-smi
Mon Jun  8 16:24:29 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.59       Driver Version: 440.59       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P6000        Off  | 00000000:09:00.0 Off |                  Off |
| 26%   18C    P8     9W / 250W |      0MiB / 24449MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

What about driver version, kubernetes version, and plugin version?  I'm using the latest drivers (4.40) and kubernetes version 1.18.3, and whatever version of the plugin the create daemonset command installs.  Other people have reported version compatibility problems.

**Comment by klueska** [comment]
No, I meant just:
```
docker run nvidia/cuda nvidia-smi
```

Assuming you followed the instructions in the QuickStart to make `nvidia` the default runtime for docker, then you shouldn't need to use the `nvidia-docker` wrapper script (`docker` alone will work). In fact it's required to work in order for Kubernetes support to work.

```
You will need to enable the nvidia runtime as your default runtime on your node. We will be editing the docker daemon config file which is usually present at /etc/docker/daemon.json:

{
    "default-runtime": "nvidia",  <---- This is the important line
    "runtimes": {
        "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}
```

**Comment by dwschulze** [comment]
The directory /etc/docker got overwritten when I was reinstalling things
this morning.  I made the changes you showed in /etc/docker/daemon.json,
restarted kubelet on the nodes and created the daemonset again on the
master.  Running kubectl describe nodes still shows 0 for Capacity and
Allocatable for gpus.  I tried the docker command on the node again and
this is what I get:

$ docker run nvidia/cuda nvidia-smi
docker: Error response from daemon: OCI runtime create failed:
container_linux.go:349: starting container process caused "exec:
\"nvidia-smi\": executable file not found in $PATH": unknown.
ERRO[0000] error waiting for container: context canceled


I'm running the latest versions of the driver and kubernetes.  Is this
maybe a versioning problem?

**Comment by klueska** [comment]
Did you also restart docker after making that change to `daemon.json`?

**Comment by klueska** [comment]
Shouldn't be a versioning problem. 

Until you get the following to work, nothing will work under Kubernetes:
```
$ docker run nvidia/cuda nvidia-smi
docker: Error response from daemon: OCI runtime create failed:
container_linux.go:349: starting container process caused "exec:
\"nvidia-smi\": executable file not found in $PATH": unknown.
ERRO[0000] error waiting for container: context canceled
```

**Comment by dwschulze** [comment]
Restarting docker allows the docker command to run, and kubectl describe
nodes shows 1 gpu Allocatable.  When I try to  run the examples from this
page:

https://docs.nvidia.com/datacenter/kubernetes/kubernetes-upstream/index.html

(have to clone the git repo and branch -- urls on that page are bad) all
pods are in pending state.  Nothing will run.  This is where I was last
week.

What should I try next?

**Comment by klueska** [comment]
Which examples from there are you running?

Most of that site seems to be more about how to deploy Kubernetes in general, with only a very short section about the plugin with a single example:
```
kubectl create -f https://github.com/NVIDIA/k8s-device-plugin/blob/examples/workloads/deployment.yml
```

**Comment by dwschulze** [comment]
That one fails to deploy.  I’ve cloned the repo and checkout the examples branch and when I run deployment.yml from my file system it creates a deployment with 32 replicas that all stay in the pending state.  I’m not sure what is supposed to happen when you request more replicas than you have available nodes, but I would expect one of those 32 pods to run.  The application itself just sleeps for 100 seconds, and I assume that is to give you a chance to run 
kubectl exec -it gpu-pod nvidia-smi

 

where you would use the pod name of a running pod from the replica set.

 

For me all 32 just stay in the pending state.  Same if I run the pod.yml example.

 

That is why I wonder if I’ve got some kind of version mismatch.  There do seem to be some (undocumented) version requirements between the driver, plugin, and Kubernetes.

**Comment by dwschulze** [comment]
Two things I've noticed.

Creating/deleting the plugin daemonset creates / deletes the file /var/lib/kubelet/device-plugins/nvidia.sock on the nodes.

The [nvidia-device-plugin.yml](https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/1.0.0-beta6/nvidia-device-plugin.yml) contains

```
      containers:
      - image: nvidia/k8s-device-plugin:1.0.0-beta6

```
There is no nvidia/k8s-device-plugin docker image on my master node.  There is also no docker container running on my master node with nvid in the name.  I haven't used a daemonset before.  Should I be able to see a docker imager or container with that name?

**Comment by klueska** [comment]
There shouldn't be any plugins on your master -- it only runs on worker nodes.

**Comment by dwschulze** [comment]
> There shouldn't be any plugins on your master -- it only runs on worker nodes.

Oh, they're on the nodes:

nvidia/k8s-device-plugin    1.0.0-beta6         c0fa7866a301        6 weeks ago         64.2MB

Also, which version of the CUDA developer libraries do I need to work with the source code?

**Comment by dwschulze** [comment]
I got the source code by cloning this github page.  The build instructions say:

 

Without Docker

Build

$ C_INCLUDE_PATH=/usr/local/cuda/include LIBRARY_PATH=/usr/local/cuda/lib64 go build

 

 

So they expect you to have cuda libraries installed, but they don’t say which version of cuda.

**Comment by weilinqwe** [comment]
i had the same problem.
the device-plugin pod log is
```
2020/06/29 03:51:41 Loading NVML
2020/06/29 03:51:41 Failed to initialize NVML: could not load NVML library.
2020/06/29 03:51:41 If this is a GPU node, did you set the docker default runtime to `nvidia`?
2020/06/29 03:51:41 You can check the prerequisites at: https://github.com/NVIDIA/k8s-device-plugin#prerequisites
2020/06/29 03:51:41 You can learn how to set the runtime at: https://github.com/NVIDIA/k8s-device-plugin#quick-start
```

but my docker version is 19.03, no need to set docker runtime to nvidia runtime, just add --gpus in docker command,  for example:
```
#### Test nvidia-smi with the latest official CUDA image
docker run --gpus all nvidia/cuda:10.0-base nvidia-smi
```
how can i add --gpus in device-plugin yaml file?

**Comment by rlantz-cfa** [comment]
Similar issue here:  I'm using EKS (Kubernetes v 1.16.8), and it's creating the nodegroup with the correct AMI.  That is, the Amazon EKS-optimized accelerated AMI as described [here](https://docs.aws.amazon.com/eks/latest/userguide/gpu-ami.html) 

The instructions there use the 1.0 beta version of your DS, but I've tried deploying it with both Helm 3, and `kubectl ... v0.6.0 ...`.  For whatever reason the scheduler is not recognizing the GPU on the host.  

FWIW, I have to run `sudo docker` on the host to get the above command to work, but when I do (e.g. `sudo docker run <image-tag> python /tmp/test.py`) it works as expected.  Maybe there's an issue with the AMI?

```+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:1E.0 Off |                    0 |
| N/A   32C    P0    25W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

tensor([[0.4713, 0.7497, 0.5766],
        [0.3508, 0.8708, 0.7834]], device='cuda:0') 
```

As suggested in the AWS docs, when I run `kubectl get nodes "-o=custom-columns=NAME:.metadata.name,GPU:.status.allocatable.nvidia\.com/gpu"`  I get `<None>` for GPU.  Do I need something in my node groups to make sure the `nvidia.com/gpu` label is present?  

If I try to run a pod (spec below) I get: `Warning  FailedScheduling  7s    default-scheduler  0/3 nodes are available: 2 node(s) didn't match node selector, 3 Insufficient nvidia.com/gpu`

The phrase `Insufficient nvidia.com/gpu` seems important here, but I'm not sure what combination of label or annotation to 

```apiVersion: v1
kind: Pod
# some stuff redacted...
metadata:
  name: pytorch-test
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: <label-name>
            operator: In
            values: 
              - <affinity-tag>
  tolerations:
  - key: "nontraining"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"
  restartPolicy: OnFailure
  containers:
  - name: pytorch-nvidia
    image: <image-tag>
    command: ["python", "/tmp/test.py"]
    resources:
      limits:
        nvidia.com/gpu: 1 # requesting 1 GPU
```

When I describe the node it shows the following labels and annotations:
```
Labels:             alpha.eksctl.io/cluster-name=<cluster-name>
                    alpha.eksctl.io/instance-id=<id>
                    alpha.eksctl.io/nodegroup-name=<nodegroup-name>
                    beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=p3.2xlarge
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=us-east-2
                    failure-domain.beta.kubernetes.io/zone=us-east-2b
                    <label>=<label>
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=<host-name>
                    kubernetes.io/os=linux
                    nvidia.com/gpu=true
Annotations:        node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
```

**Comment by rlantz-cfa** [comment]
Quick follow up for anyone who happens on this thread... for me the issue was that I had a special taint on the node group that prevented the daemonset from be scheduled there.  To resolve I just added a toleration to that spec like below, and the DS works like a charm with the default AWS accelerated AMI.  
```
spec:
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
  - key: <custom-label>
    operator: Exists
    effect: NoSchedule
```

**Comment by tuvovan** [comment]
any update on this?

**Comment by RakeshRaj97** [comment]
Facing same issue. Any update on this?

**Comment by mike2194** [comment]
@RakeshRaj97 , @tuvovan , et.al

I was able to solve the same issue by following the instructions here:
https://josephb.org/blog/containerd-nvidia/
and installing [Nvidia GPU Operator](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/getting-started.html)

I'm running k0s, so containerd runtime paths are non-standard (and containerd.service is not running, but is started by the k0s controller).

here's the contents of my `/etc/k0s/containerd.toml`

```toml
# If you wish to override the config, remove the first line and replace this file with your custom configuration.
# For reference see https://github.com/containerd/containerd/blob/main/docs/man/containerd-config.toml.5.md
imports = ["/run/k0s/containerd-cri.toml"]
version = 2

root = "/var/lib/k0s/containerd"
state = "/run/k0s/containerd"
address = "/run/k0s/containerd.sock"
config = "/etc/k0s/containerd.toml"

[grpc]
  address = "/run/k0s/containerd.sock"

#
# NOTE: GPU runtime configs effectively override k0s/system settings.
#       Runtime plugin configs must therefore be imported **after** defaults, runtime paths, socket address, etc.
#       Contents of `nvidia.toml` were copied from file `/etc/containerd/config.toml` which I believe was updated by install script from package `nvidia-container-runtime`.
imports = ["/etc/k0s/containerd.d/nvidia.toml"]
```

### RTFM:  [k0s Docs :: Runtime](https://docs.k0sproject.io/v1.31.1+k0s.0/runtime/#using-nvidia-container-runtime) made apparent the solution's fix
