### ISSUE TITLE
Does "nvidia.com/gpu" resource support ResourceQuota in kubernetes 1.8 or 1.9?

### ISSUE THREAD

**Issue by JinsYin** [NVIDIA/k8s-device-plugin#18]
Currently `alpha.kubernetes.io/nvidia-gpu` resource does not support ResourceQuota because it is an alpha resource. `nvidia.com/gpu` support?

**Comment by RenaudWasTaken** [comment]
Hello!

This is currently being handled in kubernetes/kubernetes
The feature is not available in 1.8 or 1.9 but it should be in for 1.10 where we hope to graduate the device plugin to beta.

**Comment by JinsYin** [comment]
Thanks so much @RenaudWasTaken

**Comment by pineking** [comment]
@JinsYin see this PR https://github.com/kubernetes/kubernetes/pull/57302

**Comment by JinsYin** [comment]
Thx @pineking
