### ISSUE TITLE
Supporting Multi-Instance GPUs (MIG)

### ISSUE THREAD

**Issue by klueska** [NVIDIA/k8s-device-plugin#180]
Now that [CUDA 11 has been released](https://devblogs.nvidia.com/cuda-11-features-revealed/), I wanted to create a common place for discussing the work involved to add Multi-Instance GPU support to Kubernetes. I will close this issue once the implementation has been finalized and a release of the plugin with MIG support has been released. Any and all comments are welcome.

Relevant documents:
[What Is a Multi-Instance GPU (MIG)?](https://blogs.nvidia.com/blog/2020/05/14/multi-instance-gpus/)
[Supporting MIG in the NVIDIA Container Toolkit](https://docs.google.com/document/d/13LyeFxuWLSwDjCXKx7RyWWRZEAqA-mghtK3GRPvGv1s)
[Challenges Supporting MIG in Kubernetes](https://docs.google.com/document/d/1Dxx5MwG_GiBeKOuMNwv4QbO8OqA7XFdzn7fzzI7AQDg)
[Supporting MIG in Kubernetes](https://docs.google.com/document/d/1mdgMQ8g7WmaI_XVVRrCvHPFPOMCm5LQD5JefgAh6N8g)
[Steps to Enable MIG Support in Kubernetes](https://docs.google.com/document/d/1bshSIcWNYRZGfywgwRHa07C0qRyOYKxWYxClbeJM-WM)

Link to the latest beta release:
https://github.com/NVIDIA/k8s-device-plugin/tree/v0.7.0-rc.1

**Comment by klueska** [comment]
A beta release of the plugin containing MIG support has now been released:
https://github.com/NVIDIA/k8s-device-plugin/tree/v0.7.0-rc.1

As part of this, we added support for deploying the plugin via helm, including the ability to set the MIG `strategy` you wish to use in your deployment. Details about the various MIG strategies and how they work can be found at the link below:
[Supporting Multi-Instance GPUs (MIG) in Kubernetes](https://docs.google.com/document/d/1bshSIcWNYRZGfywgwRHa07C0qRyOYKxWYxClbeJM-WM).

A beta version of MIG Support for [`gpu-feature-discovery`](https://github.com/NVIDIA/gpu-feature-discovery) should be available very soon.

**Comment by klueska** [comment]
Regarding the questions from https://github.com/NVIDIA/k8s-device-plugin/issues/180#issuecomment-642014373, the [`v0.7.0-rc.1`](https://github.com/NVIDIA/k8s-device-plugin/tree/v0.7.0-rc.1) release has opted for the following:

> 1) How useful do people find exposing all 4 strategies listed in [Supporting Multi-Instance GPUs (MIG) in Kubernetes](https://docs.google.com/document/d/1mdgMQ8g7WmaI_XVVRrCvHPFPOMCm5LQD5JefgAh6N8g).
> 2) Could we get away with having just 2 strategies (i.e. **single** and **mixed**), where **mixed** refers to what is currently called **mixed-fully-qualified**.

We have decided to only support 2 strategies: **single** and **mixed**. These two strategies solve the use cases for 95% of the users out there. We can revisit supporting the **mixed-memory-qualified** and **mixed-fractionally-qualified** strategies in the future if demand for them arises again.

> 3) How do people feel about the way MIG devices are being passed back over the plugin API via environment variables of the form `NVIDIA_VISIBLE_DEVICES_*`.
>
>    This leverages an alpha feature in the NVIDIA container toolkit that allows one to merge all of these back into a single `NVIDIA_VISIBLE_DEVICES` variable.
>
>    This makes it easy to have each resource type in the **mixed** strategies to add devices to the `NVIDIA_VISIBLE_DEVICES` environment variable, but it also means that there is no easy way to _override_ this variable via a webhook or other means to prevent people from bypassing the `k8s-device-plugin` altogether.

We have decided not leverage the use of this "merging" environment variable feature.

However, this comes with some weirdness / limitations when running under the `mixed` strategy:
1) Only **one** device type can be requested by a container at a time. If more than one device type is requested, it is __undefined__ which one the container will actually get access to. For example, a container cannot request *both* an `nvidia.com/gpu` and an `nvidia.com/mig-3g.20gb` at the same time. However, it can request multiple instances of the same resource type (e.g. `nvidia.com/gpu: 2` or `nvidia.com/mig-3g.20gb: 2`) without problems.
2) If you do happen to request multiple resource types, kubernetes will still allocate / bill all of the resources to your container. You just wont be able to see / access any of them except one.

In practice, this shouldn't be a problem because CUDA wouldn't be able to leverage more than one of these resource types at a time anyway. That said, we plan to fix this problem by the time the full `v0.7.0` release of this plugin becomes available. So stay tuned.

**Comment by klueska** [comment]
The following document has updated instructions deploying / testing MIG support on K8s:
[Steps to Enable MIG Support in Kubernetes](https://docs.google.com/document/d/1bshSIcWNYRZGfywgwRHa07C0qRyOYKxWYxClbeJM-WM/edit#heading=h.jw5js7865egx)

**Comment by klueska** [comment]
A new pre-release including support for gpu-feature-discovery is now out:
https://github.com/NVIDIA/k8s-device-plugin/tree/v0.7.0-rc.2
https://github.com/NVIDIA/gpu-feature-discovery/tree/v0.2.0-rc.1

Details on how to use this have been update here:
https://docs.google.com/document/d/1bshSIcWNYRZGfywgwRHa07C0qRyOYKxWYxClbeJM-WM/edit#heading=h.jw5js7865egx

**Comment by Addyvan** [comment]
@klueska Where is the best place for submitting issues specifically relating to MIG functionality?

**Comment by klueska** [comment]
If they are specific to the plugin, feel free to open an issue on this project. There are also other K8s components with MIG features being built for them that may be more appropriate depending on the issue:

Anything around labeling nodes with MIG-related properties:
https://github.com/NVIDIA/gpu-feature-discovery
 
Anything around configuring GPUs on a node into a set of distinct MIG devices (which the plugin can later pickup):
https://github.com/NVIDIA/gpu-operator

Work on the former is available now, while work on the latter is currently ongoing.

The major challenge in the Operator at the moment is around support for „live“ switching of a GPU into/out of MIG mode. Right now we require a full node reboot, but are exploring other less invasive means of accomplishing this.

Once in MIG mode it’s fairly easy to partition the GPUs into different MIG devices, but even this requires a full node cordone / drain at the moment because there is no notion of „device-level“ cordoning / draining that leaves the device healthy and accessible.

Anyway, feel free to file an issue on the project that seems most appropriate for your issue.

**Comment by Jeffwan** [comment]
@klueska 

> Right now we require a full node reboot,

I see in the design doc you mentioned it needs to cut any GPU connections to switch into/out of MIG mode. Seems you just remove device plugin and gpu feature discovery and restart kubelet. Does machine really need to be restarted? 

Another question is once the A100 is in MIG mode, GIs and CIs can be configured dynamically. I assume user needs to remove and reinstall device plugin and gpu feature discovery right? In this case, I think we don't need to reboot machine or kubelet? 

In AWS, most user use ASG to manage their kubernetes node groups. I feel like there's no good ways to reboot the machines. Technically, user can either put the instance to standby or suspend the health check process but seems to complicated and manual.  So any suggestions on daily operation? I think user can write some bootstrap scripts to turn on/off MIG and configure profile, GI CI, if they like to switch over, just create another ASG with different bootstrap scripts.

**Comment by klueska** [comment]
Hi @Jeffwan 

> I see in the design doc you mentioned it needs to cut any GPU connections to switch into/out of MIG mode. Seems you just remove device plugin and gpu feature discovery and restart kubelet. Does machine really need to be restarted?

If you are running in a VM (i.e. using GPU pass through virtualization), then the VM really does need to be restarted. If you are running on bare-metal then you can technically just remove all connections to the GPU and issue a GPU reset. However, enumerating all of the services that have connections to the GPU can sometimes be tricky. In the K8s stack you only have the plugin, GFD, and the kubelet itself. There may be other services running on the machine (e.g. nvidia-persistenced) that also need to be stopped and started somehow.

In theory, it _is_ possible to enumerate all of these, stop them, put the GPU into MIG mode, and restart them all. However, since a reboot is required in the VM case anyway (and the fact that this is a very infrequent operation), we've been tending to recommend a reboot in all cases.

> Another question is once the A100 is in MIG mode, GIs and CIs can be configured dynamically. I assume user needs to remove and reinstall device plugin and gpu feature discovery right? In this case, I think we don't need to reboot machine or kubelet?

That is correct. You don't need to reboot in this case. You don't need to remove and reinstall the device plugin or GFD either. GFD will automatically pick up the change after a delay of about 10 seconds. The plugin will need to be reinitialized, but you don't technically need to restart it. Sending it a SIGHUP signal should be enough (i.e. `kubectl exec <plugin-pod-id> -- kill -SIGHUP 1`).

> In AWS, most user use ASG to manage their kubernetes node groups. I feel like there's no good ways to reboot the machines. Technically, user can either put the instance to standby or suspend the health check process but seems to complicated and manual. So any suggestions on daily operation?

This is definitely a case of running in a VM (so requires a reboot in all cases). I haven't personally looked into this, but I know NVIDIA is still working with Amazon to figure out the best way to support MIG on AWS. I will make sure they are aware of this issue with using ASGs and see what their suggestions are.

The good news is that the next generation of GPUs is being designed to *not* require a GPU reset to be put into MIG mode. Unfortunately, we will have to live with it for the A100 series, but this problem should go away in future generations.

**Comment by Jeffwan** [comment]
@klueska 

Thanks for response. This is very helpful. A follow up question on the GIs and CIs changes. Let's assume we use profile1 and some pods are using resources advertised by latest device plugin. At the same time, devops make the change and use a different profile. As you said, the plugin will need to be reinitialized. previous resources might not be available after revitalization, what's the behavior on the pods side? I assume the CUDA application may get some signals if there's a reinitialization? If so, I think the best practice here would be user clean up pods with old profile on the node -> use different profile -> reschedule the pods with new advertised resources?

**Comment by klueska** [comment]
The current recommendation for setting up MIG on a GPU (that is already in MIG mode) involves:

* Drain the GPU of any currently running jobs (using a taint of some sort)
* Perform the reconfiguration
* Restart the device plugin (either duty-cycle it or send it a SIGHUP signal)
* Remove the taint

Unfortunately, there are no device-level taints, so setting up MIG on a GPU will likely require draining the whole node of jobs, and not just an individual GPU. This is likely OK in practice, since this should be a fairly infrequent operation. However, it would be nice to have support for something like device-level taints in the future.

**Comment by klueska** [comment]
We are currently looking to put together an operator to ensure the order of these operations is honored during reconfiguration (but we are still in the early design phase). I've seen recently that some third-party vendors put one together already (https://github.com/riskfuel/k8s-mig-operator), but there is no officially sponsored one from NVIDIA yet.

**Comment by klueska** [comment]
Stable versions of both the `k8s-device-plugin` and `gpu-feature-discovery` with MIG support have now been released.
https://github.com/NVIDIA/k8s-device-plugin/tree/v0.7.0
https://github.com/NVIDIA/gpu-feature-discovery/tree/v0.2.0

The documents in the description of this issue have been updated accordingly as well. 
I am closing this issue as complete.
