### ISSUE TITLE
Can specify GPU number from Kubernetes?

### ISSUE THREAD

**Issue by sakaia** [NVIDIA/k8s-device-plugin#183]
I want to use 1-node multiple GPU environment (for example g0, g1, g2, g3) in kubernetes.
For this case, GPU number (example g0) can specify from Kubernetes? 
I know `limits` argument can specify the number of using GPUs. But for my case I want to specify GPU#.
Is it available?

From seeing the code, GPU Device UUID is handled on this NVIDIA Device Plugin.
But the information seems not available from Kubernetes, it seems the total available number only from Kubernetes.

**Comment by xqqcoder** [comment]
maybe you can try to set env NVIDIA_VISIBLE_DEVICES=0 for container

**Comment by sakaia** [comment]
Thank you for you comments.

Can kubectl command  handle NVIDIA_VISIBLE_DEVICES?

**Comment by klueska** [comment]
You can set is as an ENVVAR in your pod spec. The semantics are described here:
https://github.com/NVIDIA/nvidia-container-runtime#nvidia_visible_devices
