### ISSUE TITLE
[Q][doc] MIG devices for Kubernetes

### ISSUE THREAD

**Issue by sakaia** [NVIDIA/k8s-device-plugin#184]
Is there any document about MIG device handling for Kubernetes?
Currently MIG is only  in the code.
Of course , it seems in-progress issue.

Thanks in advance.

**Comment by klueska** [comment]
A bunch of docs are linked here:
https://github.com/NVIDIA/k8s-device-plugin/issues/180

**Comment by sakaia** [comment]
Duplicate
