### ISSUE TITLE
Attempts to install with helm fail on EKS

### ISSUE THREAD

**Issue by rlantz-cfa** [NVIDIA/k8s-device-plugin#185]
### 1. Issue or feature description
Helm installation throws an error for version 0.6.0 with EKS.  Kubernetes version: `1.16`, Helm version: `2.16.3`.  Running on AWS Linux. 
### 2. Steps to reproduce the issue
As instructed in the README, when I use:
```
helm install \
    --generate-name \
    --version=0.6.0 \
    --set nodeSelector."nvidia\.com/gpu\.family"=T4  \
    nvdp/nvidia-device-plugin
```
I get: `Error: unknown flag: --generate-name`

When I remove the `--generate-name` argument I get `Error: apiVersion 'v2' is not valid. The value must be "v1"`

Does it require Helm 3?  Maybe EKS doesn't support the v2 of the DaemonSet?  Any advice is appreciated.

**Comment by klueska** [comment]
Yeah, that’s a helm 3 thing.

**Comment by rlantz-cfa** [comment]
Confirmed. Thanks!

**Comment by klueska** [comment]
We should update the docs to say that helm 3 is expected.
