### ISSUE TITLE
[doc] Question about minimul CUDA version.`~=`

### ISSUE THREAD

**Issue by sakaia** [NVIDIA/k8s-device-plugin#186]
From the README.md file,  CUDA version is written as follows.

```bash
NVIDIA drivers ~= 384.81
```

https://github.com/NVIDIA/k8s-device-plugin#prerequisites

Would you re-write above as follows? Or is there any reason to keep `~=`

```bash 
NVIDIA drivers >= 384.81
```

**Comment by sakaia** [comment]
I post following pull request
https://github.com/NVIDIA/k8s-device-plugin/pull/187

**Comment by elgalu** [comment]
Hi here, does anyone knows why such an old driver version is still in the README `NVIDIA drivers ~= 384.81` and also in the [Official NVIDIA GPU device plugin](https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/#official-nvidia-gpu-device-plugin) ?

**Comment by klueska** [comment]
This should be read as `>=`.
