### ISSUE TITLE
device will go unhealthy

### ISSUE THREAD

**Issue by D1abloRUS** [NVIDIA/k8s-device-plugin#189]
### 1. Issue or feature description

```
2020/08/10 19:09:42 XidCriticalError: Xid=69 on Device=GPU-7540a9b3-eeb9-1214-1526-f93c9ea826a8, the device will go unhealthy.
2020/08/10 19:09:42 'nvidia.com/gpu' device marked unhealthy: GPU-7540a9b3-eeb9-1214-1526-f93c9ea826a8
```

I found in code https://github.com/NVIDIA/k8s-device-plugin/blob/master/server.go#L223

what about adding this? or how to reset the status to healthy?

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Common error checking:
 - [ ] The output of `nvidia-smi -a` on your host
 - [ ] Your docker configuration file (e.g: `/etc/docker/daemon.json`)
 - [ ] The k8s-device-plugin container logs
 - [ ] The kubelet logs on the node (e.g: `sudo journalctl -r -u kubelet`)

Additional information that might help better understand your environment and reproduce the bug:
 - [ ] Docker version from `docker version`
 - [ ] Docker command, image and tag used
 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))

**Comment by qingshanyinyin** [comment]
There is no way to do so, Just restart the plugin or shut off the healthy check!

**Comment by klueska** [comment]
Once a device goes unhealthy, there i no way to bring it back to a healthy state currently. As @qingshanyinyin says, the only thing you can do is restart the device plugin (if you are really sure that the fact that it went into an unhealthy state is only a transient error and not something symptomatic of something more serious).
