### ISSUE TITLE
kubectl create -f https://..../nvidia-device-plugin.yml gives no matches for kind "DaemonSet" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by dwschulze** [NVIDIA/k8s-device-plugin#191]
Following the [nvidia-docs](https://docs.nvidia.com/datacenter/kubernetes/kubernetes-upstream/index.html#kubernetes-install-kubeadm) when I try to install the nvidia-device-plugin with this command:

`kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/1.0.0-beta/nvidia-device-plugin.yml`

I get this error:

`error: unable to recognize "https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/1.0.0-beta/nvidia-device-plugin.yml": no matches for kind "DaemonSet" in version "extensions/v1beta1"`

I notice this page shows version 0.6 of the plugin.

What is the correct way to install the plugin daemonset?

**Comment by dwschulze** [comment]
This was an error in the [nvidia docs](https://docs.nvidia.com/datacenter/kubernetes/kubernetes-upstream/index.html#kubernetes-install-kubeadm).  The correct URL (as of this date) is:

`kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/1.0.0-beta6/nvidia-device-plugin.yml`

The docs on this page seem to be out of sync with the [nvidia docs](https://docs.nvidia.com/datacenter/kubernetes/kubernetes-upstream/index.html#kubernetes-install-kubeadm) (version 0.6 versus version 1.0.0-beta6).  It's a bit confusing.

You can close this ticket.

**Comment by xqqcoder** [comment]
you should use the api version which matchs your cluster, maybe update extensions/v1beta1 to apps/v1
