### ISSUE TITLE
[MIG] Compute instances labelling is incomplete/incorrect

### ISSUE THREAD

**Issue by Addyvan** [NVIDIA/k8s-device-plugin#192]
### 1. Issue or feature description

There are two issues actually which both relate to the labels used to provision compute instances:

1. When create mig instances, the labels are adding 1 to the labels in allocatable. So for instance, `7g.40gb` would be `nvidia.com/mig-7g.41gb`.

2. When splitting up gpu instances into compute instances, they are all being treated as the same instance type no matter the compute instance split. Even if one instance is of size `1c.7gb.40gb` and the other `3c.7gb.40gb`, they are both listed as being of type `nvidia.com/mig-7g.41gb`. This results in inconsistent performance across pods as they are given instances of various sizes without explicitly knowing it. 

When describing a node, one would expect to see labels like: 
```
Allocatable:
  cpu:                     255900m
  ephemeral-storage:       1699655293391
  hugepages-1Gi:           0
  hugepages-2Mi:           0
  memory:                  1056295416Ki
  nvidia.com/gpu:          0
  nvidia.com/mig-7g.40gb:  6
  nvidia.com/mig-1c.7g.40gb:  2
  nvidia.com/mig-2c.7g.40gb:  1
  nvidia.com/mig-3c.7g.40gb:  3
```

Instead of the current output of:
```
Allocatable:
  cpu:                     255900m
  ephemeral-storage:       1699655293391
  hugepages-1Gi:           0
  hugepages-2Mi:           0
  memory:                  1056295416Ki
  nvidia.com/gpu:          0
  nvidia.com/mig-7g.41gb:  12
```

The list of compute instances for the above would be:
```
$ sudo nvidia-smi mig -lci
+-------------------------------------------------------+
| Compute instances:                                    |
| GPU     GPU       Name             Profile   Instance |
|       Instance                       ID        ID     |
|         ID                                            |
|=======================================================|
|   0      0       MIG 7g.40gb          4         0     |
+-------------------------------------------------------+
|   1      0       MIG 7g.40gb          4         0     |
+-------------------------------------------------------+
|   2      0       MIG 7g.40gb          4         0     |
+-------------------------------------------------------+
|   3      0       MIG 7g.40gb          4         0     |
+-------------------------------------------------------+
|   4      0       MIG 7g.40gb          4         0     |
+-------------------------------------------------------+
|   5      0       MIG 7g.40gb          4         0     |
+-------------------------------------------------------+
|   6      0       MIG 1c.7g.40gb       0         0     |
+-------------------------------------------------------+
|   6      0       MIG 1c.7g.40gb       0         1     |
+-------------------------------------------------------+
|   6      0       MIG 2c.7g.40gb       1         2     |
+-------------------------------------------------------+
|   6      0       MIG 3c.7g.40gb       2         3     |
+-------------------------------------------------------+
|   7      0       MIG 3c.7g.40gb       2         0     |
+-------------------------------------------------------+
|   7      0       MIG 3c.7g.40gb       2         1     |
+-------------------------------------------------------+
```

### 2. Steps to reproduce the issue

*Using strategy: mixed*

With elevated permissions on your a100 node:
```bash
nvidia-smi mig -cgi 0 # create a 7g.40gb on each gpu
nvidia-smi mig -gi 0 -cci 0 # create a 1c.7gb.40gb comp instance on each gpu
nvidia-smi mig -gi 0 -cci 0 # create a 1c.7gb.40gb comp instance on each gpu
```

Running `nvidia-smi mig -lci` should net you:

```
+-------------------------------------------------------+
| Compute instances:                                    |
| GPU     GPU       Name             Profile   Instance |
|       Instance                       ID        ID     |
|         ID                                            |
|=======================================================|
|   0      0       MIG 1c.7g.40gb       0         0     |
+-------------------------------------------------------+
|   0      0       MIG 1c.7g.40gb       0         1     |
+-------------------------------------------------------+
...
```

Assuming you have followed the instructions for the mixed strategy found [here](https://github.com/NVIDIA/k8s-device-plugin/issues/180), you should see the same output as first described. 

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Common error checking:
 - [x] The k8s-device-plugin container logs

```
2020/08/24 19:47:12 Loading NVML
2020/08/24 19:47:12 Starting FS watcher.
2020/08/24 19:47:12 Starting OS watcher.
2020/08/24 19:47:12 Retreiving plugins.
2020/08/24 19:47:12 Starting GRPC server for 'nvidia.com/mig-7g.41gb'
2020/08/24 19:47:12 Starting to serve 'nvidia.com/mig-7g.41gb' on /var/lib/kubelet/device-plugins/nvidia-mig-7g.41gb.sock
2020/08/24 19:47:12 Registered device plugin for 'nvidia.com/mig-7g.41gb' with Kubelet
```

**Comment by klueska** [comment]
For 1, the algorithm used to generate the name is as follows:

https://github.com/NVIDIA/k8s-device-plugin/blob/master/mig-strategy.go#L178
```
	g := attr.GpuInstanceSliceCount
	gb := ((attr.MemorySizeMB + 1000 - 1) / 1000)
	r := fmt.Sprintf("mig-%dg.%dgb", g, gb)
```

This _should_ match the output of `nvidia-smi` if it does not, then there is a bug and we need to fix it.

For 2, MIG devices with compute instance slice counts different than GPU instance slice counts are unsupported (i.e. anything that has a `*c` component different than a `*g* component in e.g. `1c.7g.40gb`. The code should actually error out if you attempt to connect to a GPU that has such a MIG device configured on it. 

Right now it is _not_ erroring out, and instead reporting them using the same algorithm I pasted above (basically ignoring the `*c*  field because it assumes that `c==g`.

More details on the rationale for this here:
https://docs.google.com/document/d/1Dxx5MwG_GiBeKOuMNwv4QbO8OqA7XFdzn7fzzI7AQDg/edit#heading=h.g2e5xjyshre1

**Comment by klueska** [comment]
Created the following PR to address these:
https://gitlab.com/nvidia/kubernetes/device-plugin/-/merge_requests/47

**Comment by Addyvan** [comment]
> For 1, the algorithm used to generate the name is as follows:
> 
> https://github.com/NVIDIA/k8s-device-plugin/blob/master/mig-strategy.go#L178
> 
> ```
> 	g := attr.GpuInstanceSliceCount
> 	gb := ((attr.MemorySizeMB + 1000 - 1) / 1000)
> 	r := fmt.Sprintf("mig-%dg.%dgb", g, gb)
> ```
> 
> ~This _should_ match the output of `nvidia-smi` if it does not, then there is a bug and we need to fix it.~
> **UPDATE**: The issue is that this should be using `1024` and not `1000`. Will push a patch to fix this soon.
> 
> For 2, MIG devices with compute instance slice counts different than GPU instance slice counts are unsupported (i.e. anything that has a `*c` component different than a `*g` component in e.g. `1c.7g.40gb` is unsupported). The code should actually error out if you attempt to connect to a GPU that has such a MIG device configured on it.
> 
> Right now it is _not_ erroring out, and instead reporting them using the same algorithm I pasted above (basically ignoring the `*c` field because it assumes that `c==g`).
> 
> More details on the rationale for this here:
> https://docs.google.com/document/d/1Dxx5MwG_GiBeKOuMNwv4QbO8OqA7XFdzn7fzzI7AQDg/edit#heading=h.g2e5xjyshre1
> 
> But basically, we don't want to support MIG devices as separate resources if they acre actually sharing memory under the hood (because one container's device could then use up all the memory of another container's device or otherwise crash / corrupt their instance without any warning). We could consider a special mode of operation that allows these types of devices, but they should not be made available in one of the primary supported strategies.

Thanks, for getting back so quickly on this. 

I understand the rational behind not supporting the MIG devices as separate resources since they share GPU slices. So I think until it is decided that there is to be support for multiple compute instances / gpu instance, the fix for this is to just make sure that we don't double count in the event that they are present by throwing an error if an unsupported mig instance type is present.

That being said, perhaps there should still be support for splitting a GPU instance into multiple compute instances. This could be implemented by pooling together all the the compute instances within a gpu instance and exposing them as a single resource in kubernetes. Then, from within the pod you would be able to interact with the various compute instances as you wish, either from a single container or through multiple containers within the pod. This wouldn't work using the current way of provisioning the instances though as you would need a way to differentiate between different permutations of compute instances when scheduling your experiments.

**Comment by Addyvan** [comment]
> Created the following PR to address these:
> https://gitlab.com/nvidia/kubernetes/device-plugin/-/merge_requests/47

Awesome! lgtm, when can we expect a release for this? 

Also one more question, once the change is live, will removing the old labels like this one: `nvidia.com/mig-7g.41gb:` from the node also remove them from allocatable? I would be confusing to have both lingering around for a time.

**Comment by klueska** [comment]
By the end of the week.

**Comment by klueska** [comment]
Published: https://github.com/NVIDIA/k8s-device-plugin/tree/v0.7.0-rc.6

**Comment by klueska** [comment]
Is this safe to close now?

**Comment by Addyvan** [comment]
> Is this safe to close now?

Yep! Thanks!
