### ISSUE TITLE
Not working with Quadro RTX 4000

### ISSUE THREAD

**Issue by karibertils** [NVIDIA/k8s-device-plugin#194]
### 1. Issue or feature description
I have been using Quadro P2000 which works perfectly. When i replace it with Quadro RTX 4000 the plugin does not work. The GPU works fine in regular docker containers but unable to use it in containers started by kubernetes.

### 2. Steps to reproduce the issue
1. Follow all instructions to get the plugin working with for example Quadro P2000
2. Replace the card with Quadro RTX 4000

### 3. Information
[nvidia-smi.log](https://github.com/NVIDIA/k8s-device-plugin/files/5179160/nvidia-smi.log)

[daemon.json.txt](https://github.com/NVIDIA/k8s-device-plugin/files/5179162/daemon.json.txt)

Output from docker run --security-opt=no-new-privileges --cap-drop=ALL --network=none -it -v /var/lib/kubelet/device-plugins:/var/lib/kubelet/device-plugins nvidia/k8s-device-plugin:v0.7.0-rc.7
```
2020/09/06 06:36:14 Loading NVML
2020/09/06 06:36:14 Failed to initialize NVML: could not load NVML library.
2020/09/06 06:36:14 If this is a GPU node, did you set the docker default runtime to `nvidia`?
2020/09/06 06:36:14 You can check the prerequisites at: https://github.com/NVIDIA/k8s-device-plugin#prerequisites
2020/09/06 06:36:14 You can learn how to set the runtime at: https://github.com/NVIDIA/k8s-device-plugin#quick-start
2020/09/06 06:36:14 If this is not a GPU node, you should set up a toleration or nodeSelector to only deploy this plugin on GPU nodes
```
This is the same error as when viewing the logs for nvidia-device-plugin-daemonset-xxxxx pod

Additional information that might help better understand your environment and reproduce the bug:
 - [x] Docker version from `docker version`: 19.03.12
 - [x] Docker command, image and tag used. Tried many. For example nvidia/k8s-device-plugin:v0.7.0-rc.7
 - [x] Kernel version from `uname -a`: Linux 5.4.60-1-pve #1 SMP PVE 5.4.60-1 (Mon, 31 Aug 2020 10:36:22 +0200) x86_64 GNU/Linux
 - [x] Any relevant kernel output lines from `dmesg`: Nothing shows up when testing
 - [x] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`: [nvidia-packages.log](https://github.com/NVIDIA/k8s-device-plugin/files/5179164/nvidia-packages.log)

 - [x] NVIDIA container library version from `nvidia-container-cli -V`: [nvidia-container-cli.log](https://github.com/NVIDIA/k8s-device-plugin/files/5179167/nvidia-container-cli.log)
 - [x] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting)): [nvidia-container-toolkit.log](https://github.com/NVIDIA/k8s-device-plugin/files/5179175/nvidia-container-toolkit.log)

The above logs for "NVIDIA container library logs" show up when using the GPU in a regular docker container. Nothing shows up in this log when the nvidia-device-plugin-daemonset pod is starting.

**Comment by klueska** [comment]
This is strange. It seems as if it is not able to find your `libnvidia-ml.so.1` library. 
Can you check the output of `ldconfig -p` and make sure that `libnvidia-ml.so.1` is in there.
And if it isn't, then run `sudo ldconfig` (without any flags) and try to run the plugin again.

Also, just to make sure this isn't the issue:
> If this is a GPU node, did you set the docker default runtime to `nvidia`?

Can you double check the contents of `/etc/docker/daemon.json` and restart docker:
```
{
    "default-runtime": "nvidia",
    "runtimes": {
        "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}
```

**Comment by karibertils** [comment]
@klueska 

Dohh, i completely missed how this line was somehow gone from the config.
```
"default-runtime": "nvidia",
```

All works fine after adding it back. Thanks
