### ISSUE TITLE
undefined symbol: nvmlDeviceGetCount_v2

### ISSUE THREAD

**Issue by qingshanyinyin** [NVIDIA/k8s-device-plugin#196]
I have used the latest plugin version (0.7.0) ,the driver version is 418.67 , and the CUDA version is 10.1 。The nvml error is "undefined symbol: nvmlDeviceGetCount_v2" ! I want to know if the CUDA version is not good for it ？
![image](https://user-images.githubusercontent.com/35218255/94282905-f6394080-ff82-11ea-8092-e3110f9e0102.png)

**Comment by klueska** [comment]
Is this a regression (meaning, does the v0.6.0 plugin work)?
The underlying NVML library, which the plugin is based on, may have changed to cause this error.

It's strange though, because your driver version is 418.67 and this call was introduced in CUDA 9.0 (i.e. driver version 384.81).

**Comment by qingshanyinyin** [comment]
I got it by rereading the code of libnvidia-container-1.0.2 (which i used), and found the func nvmlDeviceGetCount_v2! Does it matter?
![image](https://user-images.githubusercontent.com/35218255/94353188-6db0c200-00a0-11eb-9fdc-a040a9ee73e5.png)
Thanks!

**Comment by qingshanyinyin** [comment]
it does use the function WaitForEvent, and will be the same error!
![image](https://user-images.githubusercontent.com/35218255/94407304-e2b9ef80-01a5-11eb-9052-2ac0a0681000.png)

**Comment by klueska** [comment]
I'm still having trouble understanding the exact issue you encountered. Can you show me a full log of the error you are encountering.

**Comment by qingshanyinyin** [comment]
It offen stopped by call waitForEvent function , and i edit the function as bellow:
![Uploading 微信图片_20201018221909.jpg…]()

**Comment by qingshanyinyin** [comment]
@klueska  is there a bug in waitForEvent？

**Comment by klueska** [comment]
`nvmlEventSetWait_v2` was added in the 450 driver. But the NVML code should work across deriver versions (because it uses v1 if v2 is not available).
