### ISSUE TITLE
Is it Possible To Hide GPUs?

### ISSUE THREAD

**Issue by stuartthomson** [NVIDIA/k8s-device-plugin#197]
I have a situation where I'd like a subset of the GPUs on a machine to be scheduled by Kubernetes, but a subset of them to never be allocated by Kubernetes, and left free for me to do whatever I want with them.

Is there some way with this plugin to hide GPUs from Kubernetes?

Is this a feature you'd accept a pull request on?

**Comment by stuartthomson** [comment]
Actually, this is possible. Configure the `NVIDIA_VISIBLE_DEVICES` for the plugin container to only include those you want Kubernetes to have control over.

**Comment by doctorcolossus** [comment]
Thanks for sharing your solution, @stuartthomson.

Anyone have any idea how to do this per-node for a multi-node cluster?
