### ISSUE TITLE
is there k8s-device-plugin for cuda 8.0?

### ISSUE THREAD

**Issue by xmm1989218** [NVIDIA/k8s-device-plugin#20]
is there k8s-device-plugin for cuda 8.0? in my env I run tensorflow 1.4 need cuda 8.0

**Comment by RenaudWasTaken** [comment]
Hello !

The device plugin mechanism doesn't work like this.
It allows you to run NVIDIA images whatever the version. Please see this page for more information:
(https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/)[https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/)
