### ISSUE TITLE
device plugin start with --device-list-strategy=volume-mounts, pod create error : nnvidia-container-cli: device error: unknown device id: /var/run/nvidia-container-devices\\\\n\\\"\"": unknown

### ISSUE THREAD

**Issue by xqqcoder** [NVIDIA/k8s-device-plugin#200]
### 1. ERROR LOG
docker create container error: 
    failed to start container "busybox": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=/var/run/nvidia-container-devices --compute --utility --require=cuda>=10.1 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=396,driver<397 brand=tesla,driver>=410,driver<411 --pid=62068 /docker/data/overlay2/xxx/merged]\\\\nnvidia-container-cli: device error: unknown device id: /var/run/nvidia-container-devices\\\\n\\\"\"": unknown

### 2. Steps to reproduce the issue
1. add device plugin args --device-list-strategy=volume-mounts and apply
2. create pod with gpu

Additional information that might help better understand your environment and reproduce the bug:
 ### docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:22:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 nvidia:
  Version:          1.0.0-rc5+dev
  GitCommit:        69663f0bd4b60df09991c08812a60108003fa340-dirty
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

### rpm -qa | grep nvidia
nvidia-docker2-2.0.3-1.docker18.06.1.ce.noarch
libnvidia-container1-1.0.0-1.x86_64
nvidia-container-runtime-hook-1.4.0-2.x86_64
libnvidia-container-tools-1.0.0-1.x86_64
nvidia-container-runtime-2.0.0-1.docker18.06.1.x86_64

**Comment by klueska** [comment]
Did you follow the instructions in the following to also enable this feature in the `nvidia-container-toolkit`?
https://docs.google.com/document/d/1zy0key-EL6JH50MZgwg96RPYxxXXnVUdxLZwGiyqLd8/edit

**Comment by xqqcoder** [comment]
> Did you follow the instructions in the following to also enable this feature in the `nvidia-container-toolkit`?
> https://docs.google.com/document/d/1zy0key-EL6JH50MZgwg96RPYxxXXnVUdxLZwGiyqLd8/edit

thank you, it works, but i found device in /var/run/nvidia-container-devices also use gpu-deviceId, can device-plugin register device used by index, like nvidia0; when use gpu on cloud, if vm be restarted, gpu device id is different from older, this will cause the pod  can not be recover from the kubelet checkpoint with older device id

**Comment by klueska** [comment]
At present, the plugin only registers with the GPU UUID. I guess in your environment you actually get new physical GPUs attached after a reboot?

I will look into adding a flag for enumerating the GPUs by index rather than by their UUID and report back here.

**Comment by xqqcoder** [comment]
> At present, the plugin only registers with the GPU UUID. I guess in your environment you actually get new physical GPUs attached after a reboot?
> 
> I will look into adding a flag for enumerating the GPUs by index rather than by their UUID and report back here.

yes, i use k8s on gcp, when vm gpu maintence and reboot , the vm will get a new physical gpu

**Comment by THULiusj** [comment]
@klueska, I also had this issue when I was using k8s on GCP. Any solution now?

**Comment by klueska** [comment]
This is now targeted for inclusion in v0.9.0. I will report back here and close this issue once it has been released.

**Comment by klueska** [comment]
Here is the PR:
https://gitlab.com/nvidia/kubernetes/device-plugin/-/merge_requests/79

**Comment by dualvtable** [comment]
FWIW, I made a write-up of reproducing this issue and verifying the fix that Kevin implemented here:
`https://gist.github.com/dualvtable/43695ee812c3625b68a0c765679041dd`

The fix was in-turn verified by GCP. I think we can close this issue.
