### ISSUE TITLE
Question: How to set LD_LIBRARY_PATH on the  nvidia-device-plugin pod

### ISSUE THREAD

**Issue by joedborg** [NVIDIA/k8s-device-plugin#204]
### 1. Issue or feature description

Question: I'm wondering, for the nvidia-device-plugin pod, is it possible to pass through the LD_LIBRARY_PATH to tell the pod where to find libnvidia* etc?  There are certain circumstances where these are not found in the usual directory, which puts the pod into CrashLoopBackOff.

### 2. Steps to reproduce the issue

Deploy k8s-device-plugin to a node which has an nvidia card but does not have the drivers installed to the usual location.

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

N/A

**Comment by klueska** [comment]
This is not a property of the k8s-decive-plugin, but rather of the underlying `nvidia-container-toolkit` (which does the job of injecting `libnvidia*` into all containers for you -- including the k8s-device-plugin container).

You can configure where it looks for the driver under `/etc/nvidia-container-runtime/config.toml` with the following option:
```
#root = "/run/nvidia/driver"
```

**Comment by joedborg** [comment]
Awesome, thanks for sharing that @klueska, I'll try it out.
