### ISSUE TITLE
How to distinguish different GPU types while setup K8s resource quota

### ISSUE THREAD

**Issue by stingshen** [NVIDIA/k8s-device-plugin#205]
# 1. Issue or feature description

How to distinguish different GPU types while setup K8s resource quota

# 2. Steps to reproduce the issue

1. Assume a cluster has two GPU types: T4, V100
2. The cluster admin want to limit namespace A to use 1 piece of T4 and 1 piece of V100. 
3. There is no way to do so using k8s cluster quota mechanism.

# 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

N/A

**Comment by klueska** [comment]
You run `gpu-feature-discovery` on the cluster and use a `nodeSelector` to make sure you land on a node with the right type of GPU:
https://github.com/NVIDIA/gpu-feature-discovery

There is no support for multiple GPU types on the same node.

**Comment by stingshen** [comment]
Thank you for the answer! So currently,  there is no way to set resource quotas on per-gpu-type basis, right? Is there any plan to support this feature?

**Comment by klueska** [comment]
Not currently. There are no concrete plans to do so, but the only way to do it would be to have custom resources for each GPU type. So something like:
```
nvidia.com/t4
nvidia.com/v100
...
```

**Comment by stingshen** [comment]
Thank you.
