### ISSUE TITLE
Automatically provisioning /dev/dri devices of GPU inside container?

### ISSUE THREAD

**Issue by ehfd** [NVIDIA/k8s-device-plugin#206]
Tagging: VirtualGL maintainer @dcommander and personal collaborator @dimm0

### 1. Issue or feature description
In docker and kubernetes, people have had to have manual host setup to provision the X server using hostPath directive `/tmp/X11-unix`. This is quite tedious for sysadmins and at the same time a security threat as people can spoof the host.

There have also been attempts (https://github.com/ryought/glx-docker-headless-gpu) to execute an X server and use GLX inside the container after getting provisioned the GPU using the k8s-device-plugin. This requires privileged access or at least access to one or more of the virtual terminal console devices `/dev/ttyX` of the host.

However at last, the developers at VirtualGL (used widely in HPC to enable GPU-based rendering in VNC virtual display environments) have been able to develop a feature that uses the EGL API to enable 3D GL rendering such as Blender, Matlab, and Unity previously only possible with GLX and thus an X server. As you guys know well, nvidia-docker does not support GLX but has introduced the EGL API just below two years ago.

See EGL config section of https://github.com/VirtualGL/virtualgl/issues/113#issuecomment-693127236

**This requires access to the devices `/dev/dri/cardX` corresponding to each GPU provisioned using k8s-device-plugin. However, it does not seem like k8s-device-plugin provisions this automatically. I would like to ask you whether this is possible, and how this can be configured.**

### 2. Steps to reproduce the issue
Provision one `nvidia.com/gpu: 1` inside container `nvidia/cudagl:11.0-devel-ubuntu20.04` or `1.2-glvnd-devel-ubuntu20.04` with k8s-device-plugin v0.7.0 with default configurations in Kubernetes v1.18.6.

Do: ```ls /dev```

Result: Inside the container you see `/dev/nvidiaX`, `/dev/nvidia-modeset`, `/dev/nvidia-uvm`, `/dev/nvidia-uvm-tools`, HOWEVER `/dev/dri` does not exist.
VirtualGL does not work through any devices other than `/dev/dri/cardX`

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Other issues and repos:
Example of VirtualGL EGL configuration that requires `/dev/dri/cardX`: https://github.com/ffeldhaus/docker-xpra-html5-gpu-minimal
Unsuccessful attempts to run an NVIDIA X server inside a container: https://github.com/VirtualGL/virtualgl/issues/98

**Comment by klueska** [comment]
I can't think of a good way to support this off of the top of my head.

Integrating this into `k8s-device-plugin` doesn't feel like the right place (or even really possible) because all it does is pass back a set of GPU-UUIDs to trigger the injection of any necessary libraries / device files by `libnvidia-container` under the hood.

**Comment by ehfd** [comment]
Then should this be a libnvidia-container issue?

**Comment by ehfd** [comment]
Moving to https://github.com/NVIDIA/libnvidia-container/issues/118
