### ISSUE TITLE
Kubernetes 1.19.3 - k8s-device-plugin fails and restarts at least once a day

### ISSUE THREAD

**Issue by svetlana41** [NVIDIA/k8s-device-plugin#210]
#128 # 

Hi everyone,

I am running on Kubernetes 1.19.3 on an EC2 instance:

`kubeadm version: &version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:47:53Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}`

I have the Nvidia drivers and CUDA version:

`440.118.02   CUDA Version: 10.2`

The following version of k8s-device-plugin:

`nvidia/k8s-device-plugin                                              v0.7.0 `

I noticed that the pod restarts at least once a day with the error below:

`2020/11/24 12:11:59 Loading NVML
2020/11/24 12:11:59 Starting FS watcher.
2020/11/24 12:11:59 Starting OS watcher.
2020/11/24 12:11:59 Retreiving plugins.
2020/11/24 12:11:59 Starting GRPC server for 'nvidia.com/gpu'
2020/11/24 12:11:59 Starting to serve 'nvidia.com/gpu' on /var/lib/kubelet/device-plugins/nvidia-gpu.sock
2020/11/24 12:11:59 Registered device plugin for 'nvidia.com/gpu' with Kubelet
nvidia-device-plugin: symbol lookup error: nvidia-device-plugin: undefined symbol: nvmlEventSetWait_v2`

Does anyone know what could be causing this issue? We only have one GPU with very little workload. 

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

nvidia-smi -a logs:

`==============NVSMI LOG==============

Timestamp                           : Thu Nov 26 14:08:20 2020
Driver Version                      : 440.118.02
CUDA Version                        : 10.2

Attached GPUs                       : 1
GPU 00000000:00:1E.0
    Product Name                    : Tesla T4
    Product Brand                   : Tesla
    Display Mode                    : Enabled
    Display Active                  : Disabled
    Persistence Mode                : Disabled
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 4000
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : 1322619054117
    GPU UUID                        : GPU-946ada6d-fa2e-810f-131e-dec43e4fe381
    Minor Number                    : 0
    VBIOS Version                   : 90.04.84.00.06
    MultiGPU Board                  : No
    Board ID                        : 0x1e
    GPU Part Number                 : 900-2G183-0000-001
    Inforom Version
        Image Version               : G183.0200.00.02
        OEM Object                  : 1.1
        ECC Object                  : 5.0
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization Mode         : Pass-Through
        Host VGPU Mode              : N/A
    IBMNPU
        Relaxed Ordering Mode       : N/A
    PCI
        Bus                         : 0x00
        Device                      : 0x1E
        Domain                      : 0x0000
        Device Id                   : 0x1EB810DE
        Bus Id                      : 00000000:00:1E.0
        Sub System Id               : 0x12A210DE
        GPU Link Info
            PCIe Generation
                Max                 : 3
                Current             : 3
            Link Width
                Max                 : 16x
                Current             : 8x
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays Since Reset         : 0
        Replay Number Rollovers     : 0
        Tx Throughput               : 0 KB/s
        Rx Throughput               : 0 KB/s
    Fan Speed                       : N/A
    Performance State               : P0
    Clocks Throttle Reasons
        Idle                        : Not Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Not Active
        HW Slowdown                 : Not Active
            HW Thermal Slowdown     : Not Active
            HW Power Brake Slowdown : Not Active
        Sync Boost                  : Not Active
        SW Thermal Slowdown         : Not Active
        Display Clock Setting       : Not Active
    FB Memory Usage
        Total                       : 15109 MiB
        Used                        : 1726 MiB
        Free                        : 13383 MiB
    BAR1 Memory Usage
        Total                       : 256 MiB
        Used                        : 7 MiB
        Free                        : 249 MiB
    Compute Mode                    : Default
    Utilization
        Gpu                         : 0 %
        Memory                      : 0 %
        Encoder                     : 0 %
        Decoder                     : 0 %
    Encoder Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    FBC Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    Ecc Mode
        Current                     : Enabled
        Pending                     : Enabled
    ECC Errors
        Volatile
            SRAM Correctable        : 0
            SRAM Uncorrectable      : 0
            DRAM Correctable        : 0
            DRAM Uncorrectable      : 0
        Aggregate
            SRAM Correctable        : 0
            SRAM Uncorrectable      : 0
            DRAM Correctable        : 0
            DRAM Uncorrectable      : 0
    Retired Pages
        Single Bit ECC              : 0
        Double Bit ECC              : 0
        Pending Page Blacklist      : No
    Temperature
        GPU Current Temp            : 56 C
        GPU Shutdown Temp           : 96 C
        GPU Slowdown Temp           : 93 C
        GPU Max Operating Temp      : 85 C
        Memory Current Temp         : N/A
        Memory Max Operating Temp   : N/A
    Power Readings
        Power Management            : Supported
        Power Draw                  : 27.99 W
        Power Limit                 : 70.00 W
        Default Power Limit         : 70.00 W
        Enforced Power Limit        : 70.00 W
        Min Power Limit             : 60.00 W
        Max Power Limit             : 70.00 W
    Clocks
        Graphics                    : 585 MHz
        SM                          : 585 MHz
        Memory                      : 5000 MHz
        Video                       : 765 MHz
    Applications Clocks
        Graphics                    : 585 MHz
        Memory                      : 5001 MHz
    Default Applications Clocks
        Graphics                    : 585 MHz
        Memory                      : 5001 MHz
    Max Clocks
        Graphics                    : 1590 MHz
        SM                          : 1590 MHz
        Memory                      : 5001 MHz
        Video                       : 1470 MHz
    Max Customer Boost Clocks
        Graphics                    : 1590 MHz
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes
        Process ID                  : 26468
            Type                    : C
            Name                    : trtserver
            Used GPU Memory         : 1713 MiB
`

Any help would be appreciated. Just a note, the pod gets restarted and it seems to work again until it fails...

Thank you

Svetlana

**Comment by klueska** [comment]
Hi @svetlana41 

This is a known issue, that is under current investigation. We will report back here once a fix has been merged.

**Comment by svetlana41** [comment]
> Hi @svetlana41
> 
> This is a known issue, that is under current investigation. We will report back here once a fix has been merged.

Thank you for letting me know.

Svetlana

**Comment by klueska** [comment]
A fix for this was merged in:
https://github.com/NVIDIA/k8s-device-plugin/commit/bff876ef6a28ab0b1a6e92156b02e095cf1aa8a7

And released in:
https://github.com/NVIDIA/k8s-device-plugin/releases/tag/v0.7.3
