### ISSUE TITLE
Does used:limits.nvidia.com/gpu exist  in resource quota ?

### ISSUE THREAD

**Issue by aheeruru** [NVIDIA/k8s-device-plugin#211]
Hi. 

I am not sure this question is proper here nvidia.

When call resourcequota on k8s, there is not used:limits.nvidia.com/gpu.

kubectl get -o yaml resourcequotas myquota
....
status:
  used:
    limits.cpu: "0"
    limits.memory: "0"   ## limits.nvidia.com/gpu is not appeared.
    requests.cpu: "0"
    requests.memory: "0"
    requests.nvidia.com/gpu: "0"

I read k8s docs about scheduling-gpus, it said resource must set limits.nvidia.com/gpu == requests.nvidia.com/gpu.
So does quota show only requests.nvidia.com/gpu?  

https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/
used image version : nvidia/k8s-device-plugin:1.0.0-beta4

Thanks.

**Comment by klueska** [comment]
I'm not quite sure what you're asking unfortunately.

For quota, it all depends on how you set up your quota as to what will appear here.

For example, setting the following quota:
```
$ cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ResourceQuota
metadata:
  name: gpu-quota
spec:
  hard:
    requests.nvidia.com/gpu: "1"
    limits.nvidia.com/gpu: "1"
EOF
```
and then calling it back up, results in:
```
$ kubectl get -o yaml resourcequotas gpu-quota
...
spec:
  hard:
    limits.nvidia.com/gpu: "1"
    requests.nvidia.com/gpu: "1"
status:
  hard:
    limits.nvidia.com/gpu: "1"
    requests.nvidia.com/gpu: "1"
  used:
    requests.nvidia.com/gpu: "0"
```

Which clearly shows that you set up a hard quota for both the request and the limit of the `nvidia.com/gpu` resource type.

**Comment by aheeruru** [comment]
I wonder that why limits.nvidia.com/gpu value is not existed at status.used.
I thought some problem on my environment at first, but your result doesn't have limits.nvidia.com/gpu same as my environment.
I know it is normal, so problem is solved.

Thanks.
