### ISSUE TITLE
Docker deprecation

### ISSUE THREAD

**Issue by lazystone** [NVIDIA/k8s-device-plugin#212]
Kubernetes [deprecates Docker](https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/) and starting from v1.23 Docker won't be supported.

Currently k8s-device-plugin is tightly coupled with Docker via nvidia-docker so it most probably won't work starting from k8s v1.23.

**Comment by klueska** [comment]
The `k8s-device-plugin` does not have a direct dependence on `docker` (or `nvidia-docker` for that matter).

It's only true dependency is on the `nvidia-container-toolkit`(which is part of the `nvidia-docker` stack, but not the only component of it).

At present, the current instructions only show how to use the `k8s-device-plugin` by installing `nvidia-docker` and updating it's `daemon.json` file to point at the `nvidia-container-runtime`.  However, there is nothing preventing people from using a different container runtime and hooking the `nvidia-container-toolkit` up to that if they choose to.

In fact, the `gpu-operator` (which automates the install of the `nvidia-container-toolkit` and the `k8s-device-plugin` amongst other things) has support for `docker`, `cri-o` as well as standalone `containerd`.

What we can (and should) do is improve the documentation around this (as well as add some tooling) to make it easy to get up and running with these other runtimes outside of the `gpu-operator`.

I left this comment recently with some details about how to get things working in the meantime:
https://github.com/NVIDIA/nvidia-docker/issues/1427#issuecomment-737892353
