### ISSUE TITLE
Node allocatable count of GPU never decreased

### ISSUE THREAD

**Issue by kpouget** [NVIDIA/k8s-device-plugin#213]
### 1. Issue or feature description

In the node status, `Node.status.spec.allocatable.nvidia.com/gpu` seems to never be decreased:

```
apiVersion: v1
kind: Node
status:
  allocatable:
    nvidia.com/gpu: "1"
  capacity:
    nvidia.com/gpu: "1"
```
although I have a Pod running and using the GPU.

and indeed, in the node description, I see that the GPU is allocated:

```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                    Requests     Limits
  --------                    --------     ------
  nvidia.com/gpu              1            1
```
and as expected, I cannot create another GPU Pod:
```
  Warning  FailedScheduling  12s   default-scheduler  0/6 nodes are available: 6 Insufficient nvidia.com/gpu.
```

### 2. Steps to reproduce the issue

deploy the current release of the GPU operator:
```
helm install gpu-operator nvidia/gpu-operator --set platform.openshift=true,operator.validator.version=vectoradd-cuda10.2-ubi8,operator.defaultRuntime=crio,nfd.enabled=false,devicePlugin.version=v0.7.0-ubi8,dcgmExporter.version=2.0.13-2.1.0-ubi8,toolkit.version=1.3.0-ubi8 --wait --namespace gpu-operator --set operator.version=1.4.0
```

and schedule a long running GPU Pod

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Tested on OpenShift `4.6.4`.
Nothing relevant in the `nvidia-device-plugin-daemonset` logs:

```
2020/12/09 12:39:41 Loading NVML
2020/12/09 12:39:41 Starting FS watcher.
2020/12/09 12:39:41 Starting OS watcher.
2020/12/09 12:39:41 Retreiving plugins.
2020/12/09 12:39:41 Starting GRPC server for 'nvidia.com/gpu'
2020/12/09 12:39:41 Starting to serve 'nvidia.com/gpu' on /var/lib/kubelet/device-plugins/nvidia-gpu.sock
2020/12/09 12:39:41 Registered device plugin for 'nvidia.com/gpu' with Kubelet
```

**Comment by klueska** [comment]
I can confirm that this is happening for me as well on a K8s v1.19 cluster.

However, the device plugin interface is stateless. It is the kubelet's responsibility to maintain the state about how many devices have been allocated and report this back to the api-server to update the `capacity` and `allocatable` values.

Is this only happenig with GPUs or any resource advertised over the device plugin interface?

**Comment by kpouget** [comment]
I tested this with another device (SRIOV), and I observed the same behavior:
```
# oc create -f ... # create a pod using 4 openshift.io/intelsriov
# oc describe node
[...]
Capacity:
  openshift.io/intelsriov:  8
Allocatable:
  openshift.io/intelsriov:  8
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                 Requests     Limits
  --------                 --------     ------
  openshift.io/intelsriov  4            4
```

```
oc version
Client Version: 4.6.0-0.nightly-2020-10-03-051134
Server Version: 4.6.0-0.nightly-2020-10-03-051134
Kubernetes Version: v1.19.0+db1fc96
```

**Comment by klueska** [comment]
I've looked into this a bit more. The `Allocatable` field is not meant to be a "real-time" count of the resources available in the cluster. The naming is obviously confusing, but here's how `Allocatable` is calculated:
```
   [Allocatable] = [Node Capacity] - [Kube-Reserved] - [System-Reserved] - [Hard-Eviction-Threshold]
```
This can be seen in:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/node-allocatable.md#api-changes.

For GPUs (and probably most other devices with a plugin), this means that `Allocatable` will always equal to `Capacity` so long as all devices remain healthy.

The `Allocatable` count will only go down if the plugin decides to report fewer devices on the persistent `ListAndWatch()` connection that it maintains with the `kubelet`.  The kubelet will track *all* of the devices it has ever received from `ListAndWatch()`, marking those *not* contained in the most recent list as "unhealthy". The `Capacity` will then be reported as the total number of devices it has ever seen, and `Allocatable` will be reported as the number of healthy ones in this list (i.e. the count of the devices contained in the most recent list sent to the kubelet).

In this way (for device plugins) you can think of these two values as:
1. `Capacity`: The number of (healthy + unhealthy) devices
1. `Allocatable`: The number of (healthy) devices

In any case, I don't think this is a bug and everything is working as intended. Please feel free to reopen, if you feel differently.
