### ISSUE TITLE
Outdated MIG mixed-mode GPUs remain in the node resource listing

### ISSUE THREAD

**Issue by kpouget** [NVIDIA/k8s-device-plugin#214]
When reconfiguring the MIG slicing of the A100 (and killing/relaunching the `device-plugin` Pod), the old resource types remain visible in the Node status (although correctly reported with `0` available):

Example, after a switch from a `mixed` strategy to a `single` strategy:

```
  nvidia.com/gpu:          1
  nvidia.com/mig-1g.5gb:   0
  nvidia.com/mig-3g.20gb:  0
```

it would make more sense if the outdated resources could be completely removed.

Tested with OpenShift `4.6.1` and `k8s-device-plugin:v0.7.0-ubi8`

**Comment by klueska** [comment]
That is not something controllable by the `plugin`. The `kubelet` and the `api-server` synchronize periodically to remove stale resources at which time these entries will be removed.
