### ISSUE TITLE
Consider it to be failed when the plugin failed to load NVML and found no gpu device due to NVML error

### ISSUE THREAD

**Issue by MartinForReal** [NVIDIA/k8s-device-plugin#221]
### 1. Issue or feature description
Consider it to be failed when the plugin failed to load NVML and found no gpu device due to NVML error 

### 2. Steps to reproduce the issue
start a device plugin pod and update nvidia driver on the host then restart device plugin pod

execute nvidia-smi on the host, an error "NVML version mismatch" will be prompted. 

The pod remains ready but new pod which consume gpu can't be scheduled on this node due to insufficient resource

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Common error checking:
 - [ ] The output of `nvidia-smi -a` on your host
 - [ ] Your docker configuration file (e.g: `/etc/docker/daemon.json`)
 - [ ] The k8s-device-plugin container logs
 - [ ] The kubelet logs on the node (e.g: `sudo journalctl -r -u kubelet`)

Additional information that might help better understand your environment and reproduce the bug:
 - [ ] Docker version from `docker version`
 - [ ] Docker command, image and tag used
 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))

**Comment by klueska** [comment]
Hi @MartinForReal,

Which version of the plugin are you using, and how do you deploy it?

As of version [v0.7.0](https://github.com/NVIDIA/k8s-device-plugin/releases/tag/v0.7.0) (technically [v0.7.0-rc.3](https://github.com/NVIDIA/k8s-device-plugin/releases/tag/v0.7.0-rc.3)) there has been a flag called `failOnInitError` that, (when set to `true`) will give you the semantics you are describing. When deploying via helm, `failOnInitError` is set to `true` by default. when deploying via the static yaml files under https://github.com/NVIDIA/k8s-device-plugin/tree/master/deployments/static `failOnInitError` is set to `false`(to remain backwards compatible with the was these daemonset specs worked in the past).

**Comment by aroraakshit** [comment]
@klueska 
I just used helm to install the device plugin
```
helm install \
    --version=0.7.3 \
    --generate-name \
    nvdp/nvidia-device-plugin
```
And it is crashing on non-GPU nodes.
```
kube-system   nvidia-device-plugin-1609971430-ftg57   0/1     CrashLoopBackOff   5          3m51s
kube-system   nvidia-device-plugin-1609971430-tntsl   0/1     CrashLoopBackOff   5          3m51s
kube-system   nvidia-device-plugin-1609971430-wz9h8   1/1     Running            0          3m51s
```
How do I set failOnInitError in helm installation?

**Comment by klueska** [comment]
https://github.com/NVIDIA/k8s-device-plugin#deployment-via-helm

**Comment by aroraakshit** [comment]
thanks!

**Comment by MartinForReal** [comment]
Thanks for the info!
