### ISSUE TITLE
Clone nvidia/k8s-device-plugin to AWS ECR Public Gallery

### ISSUE THREAD

**Issue by amrragab8080** [NVIDIA/k8s-device-plugin#224]
To get around dockerhub anon account pull limits, clone the nvidia/k8s-device-plugin in another public repo like AWS ECR public gallery.

**Comment by klueska** [comment]
This should now be resolved by v0.8.2 of the device plugin:
https://github.com/NVIDIA/k8s-device-plugin/releases/tag/v0.8.2
