### ISSUE TITLE
The mig of A100 is destroied when reboot the system

### ISSUE THREAD

**Issue by qingshanyinyin** [NVIDIA/k8s-device-plugin#225]
Firstly, i set the mig of A100 (such as 7*5g ) , and the plugin can find it ('nvidia-smi -L' shows the migs  )！  
After that, i reboot the system(centos 7.8), the migs (7*5g) is destroied, and the plugin can not find it any more ('nvidia-smi -L' shows the migs)!
I wonder to know  if the migs is destroied when the system reboot? Thanks!
@klueska

**Comment by qingshanyinyin** [comment]
Is there any configures to keep the gpu instances for A100 when reboot the system?

**Comment by klueska** [comment]
MIG mode (i.e. enabled or disabled) persists across node reboots, but the actual MIG configuration does not.
You need to reconfigure MIG across every reboot, or it will be lost.

We are currently working on a component to help with managing the MIG lifecycle in this way.
It should be released / announced soon.

**Comment by qingshanyinyin** [comment]
I got it! If the power is shutted off, the MIGs will be the save? or other status? Thanks!
