### ISSUE TITLE
device plugin mig issue

### ISSUE THREAD

**Issue by Omoong** [NVIDIA/k8s-device-plugin#229]
MIG devices are not detected by the device plugin
---

### 1. Issue or feature description
this was done before 0.8.1 update, havent tested it yet with 0.8.1

device plugin works fine without mig but once i turn on mig on a dgx-a100 device plugin pod crashes and the log states that it doesnt have sufficient permissions to bring call mig devices. At this point I was using the yaml file in the following link with "--mig-strategy=single" added in the arg section.
https://github.com/NVIDIA/k8s-device-plugin/blob/master/nvidia-device-plugin.yml
Since the pod crashed in the state mentioned above, the resource under nvidia.com/gpu showed 0.
To fix the issue I had to add following
"
env: [{
          name: "NVIDIA_MIG_MONITOR_DEVICES",
          value: "all"
        }]
"
into the yaml file. 
Is this, the correct solution to this issue? 
Im not completely done with my test at the moment, so I am not 100% sure, but the above case makes it seem as if 
I would have to use same method when creating a pod on mig enabled device. 
Is my assumption correct?

### 2. Steps to reproduce the issue
turn mig on a device and deploy https://github.com/NVIDIA/k8s-device-plugin/blob/master/nvidia-device-plugin.yml with  "--mig-strategy=single" in its args section

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Additional information that might help better understand your environment and reproduce the bug:
*VERSION*   *OS-IMAGE*                 *KERNEL-VERSION*       *CONTAINER-RUNTIME*
<v1.20.2>       <Ubuntu 20.04.2 LTS>   <5.4.0-65-generic>         <docker://19.3.14>   //dgx
<v1.20.2>       <Ubuntu 18.04.4 LTS>   <4.15.0-135-generic>     <docker://19.3.6>       //master-node
<v1.20.2>       <Ubuntu 20.04.1 LTS>   <5.4.0-64-generic>         <docker://19.3.14>    //dgx
<v1.20.2>      <Ubuntu 18.04.5 LTS>   <4.15.0-135-generic>     <docker://20.10.1>   //x86
<v1.20.2>       <Ubuntu 18.04.5 LTS>   <4.15.0-135-generic>     <docker://19.3.6>     //x86

nfd image k8s.gcr.io/nfd/node-feature-discovery:v0.7.0
gfd image nvidia/gpu-feature-discovery:v0.4.0
device plugin image nvidia/k8s-device-plugin:v0.8.0

**Comment by klueska** [comment]
There was a regression in 0.8.0 that would cause the error you are seeing. It was fixed in 0.8.1.
https://gitlab.com/nvidia/kubernetes/device-plugin/-/merge_requests/74
