### ISSUE TITLE
Failed to start nvml with error

### ISSUE THREAD

**Issue by lijunyong** [NVIDIA/k8s-device-plugin#23]
I install nvidia-docker2, and deploment device plugin in kubernetes 1.8, but kubectl describe pods, I get the error.

loading NVML
Failed to start nvml with error:  could not load NVML library

**Comment by flx42** [comment]
Did you set the default runtime? https://github.com/NVIDIA/k8s-device-plugin#preparing-your-gpu-nodes

**Comment by lijunyong** [comment]
@flx42 thanks, I solved the problem ，the k8s-device-plugin release 1.8 document not show "First you will need to check and/or enable the nvidia runtime as your default runtime on your node". the 1.9 document has
