### ISSUE TITLE
nvcr.io/nvidia/k8s-device-plugin:v0.9.0 does not exist yet

### ISSUE THREAD

**Issue by kwmonroe** [NVIDIA/k8s-device-plugin#230]
### 1. Issue or feature description

`k8s-device-plugin` was bumped to `v0.9.0` in [this merge](https://github.com/NVIDIA/k8s-device-plugin/commit/2490c3187727c554985478d635fa0f8cba59484e#diff-fb4614e02b8fd10476a001f2dd2519c32c4032cfcfce2a6fc8631a67b5a5ea9d), but that image does not exist in the repo:

https://ngc.nvidia.com/catalog/containers/nvidia:k8s-device-plugin/tags

### 2. Steps to reproduce the issue

```bash
$ docker pull nvcr.io/nvidia/k8s-device-plugin:v0.9.0
Error response from daemon: manifest for nvcr.io/nvidia/k8s-device-plugin:v0.9.0 not found: manifest unknown: manifest unknown
```

**Comment by klueska** [comment]
Yes. Our pipeline got stuck and we haven't been able to release the container yet.

**Comment by klueska** [comment]
Should be resolved now, sorry for the hiccup.

**Comment by kwmonroe** [comment]
Confirmed looks good now. Thanks for the quick fix!
