### ISSUE TITLE
[MIG] different GPU node in K8S cluster

### ISSUE THREAD

**Issue by xiekeyang** [NVIDIA/k8s-device-plugin#233]
In user's K8S cluster there are different GPU types nodes (such as A100 and other). Currently user seems can't deploy one device-plugin that supports MIG node(I mean single mode or mixed mode) and other node.

In this case we have to set up two daemon sets. This is really a little hard to maintain. Should we refactor device-plugin that on DS can support both types at same time?

In daemon set spec, `mig-strategy` option only take effect to A100 nodes and by-pass for other nodes.

**Comment by klueska** [comment]
As of  `v0.8.0`, setting either `single` or `mixed` should also be deployable on machines with full GPUs and it should work just fine. It should also work on machines with non MIG-capable GPUs (so long as there is not a mix of different types of GPUs on the same node). There should be no need for separate daemonsets.

**Comment by xiekeyang** [comment]
@klueska Great! I works on `v0.8.0`. Thanks so much!
