### ISSUE TITLE
Is it possible to hide GPUs on a per-node basis?

### ISSUE THREAD

**Issue by doctorcolossus** [NVIDIA/k8s-device-plugin#236]
It is possible [to set the `NVIDIA_VISIBLE_DEVICES` environment variable for the `nvidia-device-plugin-ctr` container](https://github.com/NVIDIA/k8s-device-plugin/issues/197), but this affects all nodes.

Suppose that I have two nodes with four GPUs each.

Is there any way for example to make all GPUs on the first node schedulable, but only GPU indices 0 and 1 on the second node?

**Comment by klueska** [comment]
The only way to do that is to deploy 2 separate daemonsets. 
One daemonset with NVIDIA_VISIBLE_DEVICES set one way and another daemonset with it set another way.

You the need to make sure and apply appropriate labels to the nodes which should have each variant, and use a `nodeSelector` in your daemonset spec to direct each daemonset to the appropriate set of nodes.

**Comment by doctorcolossus** [comment]
Brilliant! Thank you, Kevin.
