### ISSUE TITLE
Does not work with nvidia drivers 460?

### ISSUE THREAD

**Issue by whillas** [NVIDIA/k8s-device-plugin#241]
I'm running this on k3s which is using docker which is using the nvidia-docker which is using nvidia drivers 460 as setup by the [Nvidia driver Ansible role](https://github.com/NVIDIA/ansible-role-nvidia-driver). With the 460 drivers GPUs are not getting allocated. Dropping back to 450 and this starts to work again. Unfortunately i need Nvidia's Triton Server 20.11 which required CUDA 11.1 and thus drivers 455. The Ansible role can only install 450 or 460 which i have [submitted a bug for](https://github.com/NVIDIA/ansible-role-nvidia-driver/issues/34).

Is this damonset supposed to run on 460 drivers?

This might be a duplicate of #235 but there you are talking about cgroups?

weirdly it seems to work for 465.xx drivers?

**Comment by klueska** [comment]
There we no known issues with the plugin and the 460 driver, so it Must be something particular to your setup. Can you provide the output of the plugin logs?

**Comment by klueska** [comment]
Another thing that just occurred to me. I'm not sure how/why it wouldn't be cleaned up, but can you check the contents of the `/var/lib/kubelet/device-plugins` folder. If there is an old `nvidia-gpu.sock` file in there, then the kubelet could be grabbing a reference to it and thinking that these resources are still available even if there is no one listening on the other end of the socket. If so, manually removing this file should should help.

**Comment by whillas** [comment]
I fixed it by accidentally installing 465? I switched drivers a few times and 460 stopped working every time. They where the Canonical drivers for Ubuntu. Thanks for getting back to me!
