### ISSUE TITLE
Question - How to enable NVIDIA driver capability for k8 cluster

### ISSUE THREAD

**Issue by StianHanssen** [NVIDIA/k8s-device-plugin#252]
### 1. Issue or feature description
Apologies for poor problem description, due to my code being work related I can't share my daemonset yaml or code. If there is no obvious remedy I can try, then please dismiss my question.

I am currently trying to run [NVIDIA optical flow](https://developer.nvidia.com/opticalflow-sdk) on an AWS EKS cluster. As per AWS documentation, I enabled access to GPUs through use of this device plugin in my EKS cluster. I have no issue accessing the GPU, I can run my deep leaning models just fine. The issue is with code using NVIDIA optical flow, which need certain device capabilities enabled. I run on a G4DN instance which has a Tesla T4, and the driver version being 450.51.06 (CUDA 11.0).

I need NVIDIA_DRIVER_CAPABILITIES set to "compute,utility,video". So far, I have tried to add:
```yaml
env:
- name: NVIDIA_DRIVER_CAPABILITIES
  value: "compute,video,utility"
```
Both to `nvidia-device-plugin.yml` and my own daemonset which runs nvidia optical flow. But it it fails, with:
```
cv2.error: OpenCV(4.5.2-dev) /opt/opencv-build/opencv_contrib-master/modules/cudaoptflow/src/nvidiaOpticalFlow.cpp:211: error: (-6:Unknown error code -6) Cannot find NvOF library. in function 'LoadNvidiaModules'
```
Which is the same error I would get if I ran locally:
```
docker run -it --rm --gpus all nvidia_optical_flow
```
Because it is lacking `NVIDIA_DRIVER_CAPABILITIES=compute,video,utility`:
```
docker run -it --rm --gpus all -e NVIDIA_DRIVER_CAPABILITIES=compute,video,utility nvidia_optical_flow
```
(Above works with the environment variables added)

I feel like I am just missing a detail on how to adjust one of the Daemonset yamls, but I am out of ideas. Would really appreciate any suggestions, or a confirmation if this should in theory be enough.

**Comment by elezar** [comment]
Hi @StianHanssen. Thanks for the issue.

The environment variable should be set for the `nvidia_optical_flow` container. I assume that you have some podspec for this and would have to add the environment variable there or specify it directly in the `Dockerfile` for the `nvidia_optical_flow` image.

Do you have a link to the AWS EKS documentation that you refer to.

**Comment by StianHanssen** [comment]
Hi @elezar ,

I have indeed already tried to add this to the optical flow dockerfile: `ENV NVIDIA_DRIVER_CAPABILITIES="compute,video,utility"`

I am currently using a Daemon set, and that was where I attempted to add the environment variable as well, but neither were successful, unfortunately.

The daemonset would be similar to this example: https://github.com/aws-samples/amazon-elastic-inference-eks/blob/master/k8s-daemonset.yml
But imagine only having the inference-daemon container.

The EKS documentation I am referring to is given here: https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html

Under section "To enable GPU based workloads".

**Comment by elezar** [comment]
Sorry for my delay in getting back to you. You would need to add `NVIDIA_DRIVER_CAPABILITIES` to the env list here: https://github.com/aws-samples/amazon-elastic-inference-eks/blob/master/k8s-daemonset.yml#L63 and also be sure to request GPU resources or apply a node selector to ensure that this lands on a node that actually has GPUs installed (assuming that you don't have a heterogeneous cluster).

**Comment by StianHanssen** [comment]
Thank you for your suggestion! I am afraid that doesn't work, but I glad you confirmed that is all that should theoretically be needed. My guess is that AWS have applied some sort of limiting factor which prohibits the use of these capabilities.

As we didn't find a solution my team chose a different direction, and so we are not pursuing this further at this point. I will close the issue, but promise to reply if we ever revisit the idea and get it working.
