### ISSUE TITLE
Publish latest dockerfile?

### ISSUE THREAD

**Issue by atishpatel** [NVIDIA/k8s-device-plugin#270]
I noticed the latest docker file on docker v0.9.0 is still using ubuntu 16.04 and older golang version but master already has the os version and golang version bumped. If this is tested, can you please publish the latest master commit as a docker version? 🙏

**Comment by elezar** [comment]
@atishpatel `v0.10.0` of the device plugin has been released. Please let us know if there are any other problems.

**Comment by elezar** [comment]
@atishpatel I am closing this issue as resolved. Please reopen or create a new issue if this is not the case.
