### ISSUE TITLE
Helm chart is not available

### ISSUE THREAD

**Issue by kalaiselvan263** [NVIDIA/k8s-device-plugin#272]
I am not able to download https://nvidia.github.com/k8s-device-plugin/stable/nvidia-device-plugin-0.7.3.tgz

**Comment by klueska** [comment]
The correct URL is:
https://nvidia.github.io/k8s-device-plugin/stable/nvidia-device-plugin-0.7.3.tgz

i.e. nvidia.github.io and not nvidia.github.com

Where did you pull this download URL from? If it’s published incorrectly somewhere we should fix that.

**Comment by kalaiselvan263** [comment]
I got this link from the below URL.

https://github.com/NVIDIA/k8s-device-plugin

**Comment by elezar** [comment]
Thanks for pointing this out @kalaiselvan263. We will update the README in the repo.

**Comment by elezar** [comment]
@kalaiselvan263 I have updated the README.md. Please reopen if the instructions are still incorrect.
