### ISSUE TITLE
ETA for v0.10.0 release

### ISSUE THREAD

**Issue by elgalu** [NVIDIA/k8s-device-plugin#276]
Hi, I would like to know if there's an ETA for nvcr.io/nvidia/k8s-device-plugin:v0.10.0 release, thanks.

**Comment by elezar** [comment]
Hi @elgalu we are working on getting it out as soon as possible. There is one final approval required for the release and then we will get the image out, after which we will publish the updated helm charts.

**Comment by elezar** [comment]
@elgalu [`v0.10.0`](https://github.com/NVIDIA/k8s-device-plugin/releases/tag/v0.10.0) of the device plugin has been released.

**Comment by elgalu** [comment]
Thanks a lot! works!!

```sh
docker pull nvcr.io/nvidia/k8s-device-plugin:v0.10.0
v0.10.0: Pulling from nvidia/k8s-device-plugin
35807b77a593: Pull complete 
beaf026382a5: Pull complete 
9dd04700b73b: Pull complete 
ce3345be8759: Pull complete 
ff416b8b4a8f: Pull complete 
473e5db351e4: Pull complete 
ff0c75f537a9: Pull complete 
Digest: sha256:5b967b3e92900797a74e0f7cd71005747fa3154503986676f372b9d82fe1d898
Status: Downloaded newer image for nvcr.io/nvidia/k8s-device-plugin:v0.10.0
nvcr.io/nvidia/k8s-device-plugin:v0.10.0
```
