### ISSUE TITLE
pods crashlooping on k8s 1.22

### ISSUE THREAD

**Issue by paulfantom** [NVIDIA/k8s-device-plugin#278]
---

### 1. Issue or feature description

DaemonSet Pod is crashlooping when using manifests from https://github.com/NVIDIA/k8s-device-plugin/blob/master/deployments/static/extensions-v1beta1-nvidia-device-plugin.yml with added `runtimeClass` (manifests used: https://github.com/thaum-xyz/ankhmorpork/tree/master/base/kube-system/device-plugins).

X-ref with more information: https://github.com/k3s-io/k3s/issues/4391

### 2. Steps to reproduce the issue

Start k3s cluster in version 1.22.
Apply manifests

---

I am posting this issue here to bring this to maintainers attention. Most information is available in https://github.com/k3s-io/k3s/issues/4391. Also a workaround posted there is working, but it does not look like a good solution from security perspective.

**Comment by elezar** [comment]
Thanks @paulfantom. I have added a comment to the linked issue: https://github.com/k3s-io/k3s/issues/4391#issuecomment-970215400

If you're able to confirm that the updated `nvidia-container-toolkit` packages address this issue for you, that would be useful.

**Comment by paulfantom** [comment]
I installed v1.6.0-rc.3 and it seems to be working just fine. Thank you very much for your support! :+1: :100:
