### ISSUE TITLE
how to schedule jobs to different type of gpus?

### ISSUE THREAD

**Issue by silverlining21** [NVIDIA/k8s-device-plugin#292]
Assuming I got one node with two different type GPUS  `Tesla V100*4 ` and `Tesla T4*4` on the same node. and I want k8s to schedule my training jobs to V100 card, while inference jobs runing on T4. as I konw there is a compromization that put different GPUs on different node and label the node with gpu types, then scheduling by `label selector`. but that not in my consideration.

Is there any possible way to make it happen? 

any suggestion will be appericated.

**Comment by klueska** [comment]
There is no way to do this currently. We are planning to add the ability to set custom resource names soon though. It will be based on matching a string against the model name of a given GPU and then setting a custom resource name for based on it.

So you will be able to have resource names like:
```
nvidia.com/t4
nvidia.com/a110
```
etc.

Where each of those names is chosen by the user after matching to a GPU model name.

**Comment by silverlining21** [comment]
that's pretty cool !  By providing some custom describing field(such as full name or arch type etc.) for those custom resources(different type of GPUs/NPUs), its scheduling will much more flexibile.

**Comment by silverlining21** [comment]
Looking forward!

**Comment by journey-wang** [comment]
@silverlining21 
After adding some custome resource name like: 
nvidia.com/t4
nvidia.com/v100
nvidia.com/rtx

Then one of my pod support both t4 and v100, how to request the resource like:
requests:
   nvidia.com/t4 : 1 or nvidia.com/v100 : 1

**Comment by silverlining21** [comment]
> @silverlining21 After adding some custome resource name like: nvidia.com/t4 nvidia.com/v100 nvidia.com/rtx
> 
> Then one of my pod support both t4 and v100, how to request the resource like: requests: nvidia.com/t4 : 1 or nvidia.com/v100 : 1

Hi, Dose your trail apply on one node? If it's possible to schedule job to different GPU, such as T4 or V100 etc, on the same node ?

**Comment by yeqiugt** [comment]
> There is no way to do this currently. We are planning to add the ability to set custom resource names soon though. It will be based on matching a string against the model name of a given GPU and then setting a custom resource name for based on it.
> 
> So you will be able to have resource names like:
> 
> ```
> nvidia.com/t4
> nvidia.com/v100
> ```
> 
> etc.
> 
> Where each of those names is chosen by the user after matching to a GPU model name.

Do you have a more accurate timetable?
