### ISSUE TITLE
Question - Specifying Nvidia Driver Version

### ISSUE THREAD

**Issue by robincher** [NVIDIA/k8s-device-plugin#293]
Hi,

This is more of a question rather than bug/feature request. Pardon me since i first started work on GPU processing in Kubernetes.

Currently we have a few GPU-optimised node in Azure Kubernetes Service, and manage to enable to the device plugin (https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/aks/gpu-cluster.md#confirm-that-gpus-are-schedulable). 

My question is , is there anyway we can specific the nvidia driver version? 

Unfortunately, we need to fix our driver version **430.30** due to the legacy app. Or if there are any release/tag that support the driver **430.30** version. I am unable to find any information or any documents on it.

https://github.com/GoogleCloudPlatform/container-engine-accelerators/issues/119 

```
kubectl patch daemonset nvidia-driver-installer --namespace kube-system --patch '{"spec":{"template":{"spec":{"initContainers":[{"name":"nvidia-driver-installer","env":[{"name":"NVIDIA_DRIVER_VERSION","value":"450.51.06"}]}]}}}}'
```

Somehow there some workarounds from above, i wonder if this is the right approach.

Thanks!

**Comment by elezar** [comment]
Hi @robincher. The NVIDIA Device Plugin does not specify a driver version, and expects the NVIDIA driver to already be installed. This can either be installed on the host, or through the NVIDIA [driver container](https://docs.nvidia.com/datacenter/cloud-native/driver-containers/overview.html). I am not familiar with AKS and how it deploys the components, but I would assume that the driver is installed as part of provisioning the node.

For the GKE example you included above, what is being modified is a "driver installer container". One would have to find the equivalent for AKS.

**Comment by robincher** [comment]
Hi @elezar ,

Morning, and thanks for the advice. You gave me a better idea on where i should probe. My initial thoughts was perhaps Azure baked something into the device plugin they provide, and probably include a specify driver version with it.

I check with Azure on this, and will close this issue.

Thanks!
Robin
