### ISSUE TITLE
In best effort policy， how will the links between nvidia migs and between a nvidia mig and a normal gpu be scored？

### ISSUE THREAD

**Issue by cqnkjsx** [NVIDIA/k8s-device-plugin#296]
It is not mentioned in besteffort_policy.go

**Comment by klueska** [comment]
There are no links. MIG devices do not support peer-to-peer communication with other devices.

**Comment by cqnkjsx** [comment]
You mean even two mig devices in one gpu cannot communicate with each other?

**Comment by klueska** [comment]
Correct.

**Comment by klueska** [comment]
See the second bullet point here:
https://docs.nvidia.com/datacenter/tesla/mig-user-guide/#app-considerations

**Comment by cqnkjsx** [comment]
thx！
