### ISSUE TITLE
k8s deviceplugin api is changed from v1alpha to v1beta1

### ISSUE THREAD

**Issue by pineking** [NVIDIA/k8s-device-plugin#30]
https://github.com/kubernetes/kubernetes/commit/e64517cd7410166b01642efeb4a8d0374e236153
this commit changes the deviceplugin api from v1alpha to v1beta1, and will be released in v1.10 of k8s.

I have test k8s-device-plugin:v1.9, which does not work with this commit.

could someone please update the code to a new release, k8s-device-plugin:v1.10?

**Comment by pineking** [comment]
@flx42  is It possible create a new branch 1.10? maybe I can file a PR after the new branch created.

**Comment by RenaudWasTaken** [comment]
Hello @pineking !

I'll be taking a look at upgrading against 1.10 next week. Thanks for creating this issue :)

**Comment by pineking** [comment]
@RenaudWasTaken Great, Thanks!

**Comment by RenaudWasTaken** [comment]
Will close the issue when it's fixed :D

**Comment by pineking** [comment]
close this since the branch v1.10 is released
