### ISSUE TITLE
Install nvidia-docker first or install k8s first?

### ISSUE THREAD

**Issue by mingfengwuye** [NVIDIA/k8s-device-plugin#31]
I want to build k8s cluster with gpu support. 
which procedure is better ?
1. install docker 
2. install k8s 
3. install nvidia-docker
or
1. install nvidia-docker 
2. install k8s

**Comment by RenaudWasTaken** [comment]
Hello!

As long as you have all the packages installed as described in the [prerequisites](https://github.com/NVIDIA/k8s-device-plugin#prerequisites) the install order does not matter.
