### ISSUE TITLE
device plugin default_runtime_name requirement and documentation

### ISSUE THREAD

**Issue by rptaylor** [NVIDIA/k8s-device-plugin#314]
The k8s-device-plugin README instructions https://github.com/NVIDIA/k8s-device-plugin#preparing-your-gpu-nodes
link to and somewhat duplicate the container toolkit docs here: 
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html

Having already referred to and closely followed the container toolkit docs, it is easy to miss one piece of config that is both required for the k8s-device-plugin to work (or else you get "failed to load NVML" errors) and somehow completely missing from the container toolkit setup docs:
`default_runtime_name = "nvidia"`

Aside from being easy to miss, it can be particularly confusing because directly testing the containerd integration and container toolkit setup like this `ctr run --rm --gpus 0 docker.io/nvidia/cuda:11.7.0-runtime-ubuntu22.04 nvidia-smi-test nvidia-smi` succeeds even without the change to default_runtime_name. 

Perhaps that step could be included in the container toolkit docs or highlighted in the device plugin docs, or other refactoring/harmonization of the two different (partially redundant?) documentation pages for doing almost the same thing.

**Comment by rptaylor** [comment]
Actually there is another discrepancy between the two documentation pages; I am not sure which one should be considered correct.
https://github.com/NVIDIA/k8s-device-plugin#configure-containerd  this has  `runtime_type = "io.containerd.runc.v2"`

https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#step-1-install-containerd
this has `runtime_type = "io.containerd.runc.v1"`

**Comment by klueska** [comment]
A fix for the github README is included in:
https://gitlab.com/nvidia/kubernetes/device-plugin/-/merge_requests/200

Regarding your second question -- it shouldn't matter much between
```
runtime_type = "io.containerd.runc.v2"
```
and
```
runtime_type = "io.containerd.runc.v1"
```
Modern containerds come with the `io.containerd.runc.v2` shim, but this wasn't always true, so `io.containerd.runc.v1` was used to make sure the instructions worked even on older containerds.
