### ISSUE TITLE
NVIDIA A10 GPUs - are these drivers in the NVIDIA / k8s-device-plugin

### ISSUE THREAD

**Issue by jeffreydahan** [NVIDIA/k8s-device-plugin#317]
### 1. Issue or feature description

Hi, I work at Microsoft and we are getting ready to go live with the A10 VMs (https://docs.microsoft.com/en-us/azure/virtual-machines/nva10v5-series).  Ahead of this go-live, I am trying to determine if the drivers are already located in:  https://github.com/NVIDIA/k8s-device-plugin for Kubernetes

As part of the Azure Kubernetes Service deployments for GPU-enabled nodes, we use your plugin to enable to drivers/GPUs.
https://docs.microsoft.com/en-us/azure/aks/gpu-cluster#manually-install-the-nvidia-device-plugin

Just not sure if A10 is included.  I tried calling NVIDIA support and they said to open a case here.  Thanks!

**Comment by elezar** [comment]
@jeffreydahan the GPU Device Plugin does not install or manage the driver. The expectation is that the user install this directly on the host or that this is installed by something like the driver container. 

Note that there are no device-specifics in the device plugin and as such if the correct driver is installed for a device (e.g. the A10) this should function in the same way as other NVIDIA devices.

Do you have any information as to which driver version is installed and how this is deployed?

**Comment by rogelioamancisidor** [comment]
@jeffreydahan do you think this question is related [issue#3104](https://github.com/Azure/AKS/issues/3104). When I created my cluster some time ago, I used the `yaml` manifest that enables the drivers in the link you post.   

How am I gonna install the drivers directly using AKS?

**Comment by rogelioamancisidor** [comment]
yes the new A10. I have tried to add 1/3-1 A10 GPU and always get the same error message.

**Comment by jeffreydahan** [comment]
I am waiting for product group to resolve this. They are updating the driver install process. Hoping for a few weeks, but no commitment on timeline.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rogelioamancisidor** [comment]
@jeffreydahan how do I know when the drivers are updated? there is no info on this in the AKS webpages, not that I have seen.

**Comment by jeffreydahan** [comment]
I am watching this for now. As of last week it is still work in progress. There may be an option to self install within a week. I am getting the details on the daemon set to use to enable the self install.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rogelioamancisidor** [comment]
Is this issue documented some where? So we can follow it. All azure documentation suggests that A10 GPUs are now available for AKS. But least in our cluster, we keep getting errors when we try to add a nodepool with an A10 GPU.

**Comment by CloudCourierStation** [comment]
Hi, I am currently using NVIDIA A10, but I received the following log after installing the device plugin in the kubernetes cluster。
`I0129 07:41:50.182555       1 main.go:256] Retreiving plugins.
W0129 07:41:50.182894       1 factory.go:31] No valid resources detected, creating a null CDI handler
I0129 07:41:50.182981       1 factory.go:107] Detected non-NVML platform: could not load NVML library: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
I0129 07:41:50.183067       1 factory.go:107] Detected non-Tegra platform: /sys/devices/soc0/family file not found
E0129 07:41:50.183080       1 factory.go:115] Incompatible platform detected
E0129 07:41:50.183086       1 factory.go:116] If this is a GPU node, did you configure the NVIDIA Container Toolkit?
E0129 07:41:50.183092       1 factory.go:117] You can check the prerequisites at: https://github.com/NVIDIA/k8s-device-plugin#prerequisites
E0129 07:41:50.183097       1 factory.go:118] You can learn how to set the runtime at: https://github.com/NVIDIA/k8s-device-plugin#quick-start
E0129 07:41:50.183102       1 factory.go:119] If this is not a GPU node, you should set up a toleration or nodeSelector to only deploy this plugin on GPU nodes
I0129 07:41:50.183110       1 main.go:287] No devices found. Waiting indefinitely.`
To do this, I checked the NVIDIA Container Toolkit. Ensure that the current machine is a GPU node.
Therefore, I would like to know whether the device plugin is not adapted to NVIDIA A10 or I made an error in some step.

**Comment by CloudCourierStation** [comment]
> Hi, I am currently using NVIDIA A10, but I received the following log after installing the device plugin in the kubernetes cluster。 ![image](https://private-user-images.githubusercontent.com/33771248/300374349-fb347d7b-88f4-4035-8815-f8c090e6fa6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTUzMzEsIm5iZiI6MTcwNjUxNTAzMSwicGF0aCI6Ii8zMzc3MTI0OC8zMDAzNzQzNDktZmIzNDdkN2ItODhmNC00MDM1LTg4MTUtZjhjMDkwZTZmYTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA3NTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkYjZmN2M0ZWEzZDg1MjNhOTk3YjAzOGU0ZDU0YmFkMDViZmNmNWNmNzdmNGZmZTI3NTY3MTVkY2FhMWUyNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HF0IQ9cn3Gxpm_ciAcBxISPmIxKo0bG_3aw5Hd7hsF8)
> 
> To do this, I checked the NVIDIA Container Toolkit. Ensure that the current machine is a GPU node. Therefore, I would like to know whether the device plugin is not adapted to NVIDIA A10 or I made an error in some step.

The image I am currently using is: nvcr.io/nvidia/k8s-device-plugin:v0.14.3

**Comment by CloudCourierStation** [comment]
For the following information, my current operating system is aarch64.
![image](https://github.com/NVIDIA/k8s-device-plugin/assets/33771248/e84d5686-f356-4563-8ec7-32637cb1fc17)


> Hi, I am currently using NVIDIA A10, but I received the following log after installing the device plugin in the kubernetes cluster。 ![image](https://private-user-images.githubusercontent.com/33771248/300374349-fb347d7b-88f4-4035-8815-f8c090e6fa6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTYwMjgsIm5iZiI6MTcwNjUxNTcyOCwicGF0aCI6Ii8zMzc3MTI0OC8zMDAzNzQzNDktZmIzNDdkN2ItODhmNC00MDM1LTg4MTUtZjhjMDkwZTZmYTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA4MDg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhYTBiMDU5YWI1MTAyNzgzMzNjMjkxNzkwNGFjMTgwMTFhZjNmZmIzMjI4OTFlZDg5ZTQ2ZDZjODYxZjZjYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v0U_s7V6rSukFzcFo4zHt5hUgOYI6pZuhvwdcva8SWM)
> 
> To do this, I checked the NVIDIA Container Toolkit. Ensure that the current machine is a GPU node. Therefore, I would like to know whether the device plugin is not adapted to NVIDIA A10 or I made an error in some step.
