### ISSUE TITLE
Unable to get nvidia.com/gpu: "1" greater than 1 for Quadro P2000

### ISSUE THREAD

**Issue by brianbrady** [NVIDIA/k8s-device-plugin#321]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._
---

### 1. Issue or feature description
Trying to get time-slicing configured in home lab in preparation for customer delivery. Single GPU workload has been working fine, unable to schedule additioal workloads.

### 2. Steps to reproduce the issue
Using GPU Operator w/P200 installed
Helm: 
helm install --wait --generate-name -n gpu-operator --create-namespace nvidia/gpu-operator --set operator.defaultRuntime=containerd --set devicePlugin.config.name=time-slicing-config --set devicePlugin.config.default=quadro-p2000

K8 ConfigMap:
apiVersion: v1
kind: ConfigMap
metadata:
  name: time-slicing-config
  namespace: gpu-operator
data:
  quadro-p2000: |-
    version: v1
    sharing:
      timeSlicing:
        renameByDefault: true
        failRequestsGreaterThanOne: true
        resources:
        - name: nvidia.com/gpu
          replicas: 4

Node Label:
kubectl label node knuc1 nvidia.com/device-plugin.config=quadro-p2000

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Common error checking:
 - [ ] The output of `nvidia-smi -a` on your host
 - [ ] Your docker configuration file (e.g: `/etc/docker/daemon.json`)
 - [ ] The k8s-device-plugin container logs
 - [ ] The kubelet logs on the node (e.g: `sudo journalctl -r -u kubelet`)

Additional information that might help better understand your environment and reproduce the bug:
 - [ ] Docker version from `docker version`
 - [ ] Docker command, image and tag used
 - [x] Kernel version from `uname -a`
    Linux knuc1 5.13.0-51-generic #58~20.04.1-Ubuntu SMP Tue Jun 14 11:29:12 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))

**Comment by klueska** [comment]
Can you elaborate on the exact issue you are seeing?

You posted good info on how you have set things up, but it's unclear what is not working as expected from your description.

Also, you seem to be deploying the operator, not just the standalone plugin (so your question should technically be part of github project for the operator, not this one).

**Comment by brianbrady** [comment]
Yea... I figured I was asking in the wrong spot given the setup, I assumed I was targeting the right people.

Expectations:
`kubectl describe node knuc1`

> ...
> Capacity:
>   nvidia.com/gpu: 4
> ...
> Allocatable:
>   nvidia.com/gpu: 4

Current Result:
`kubectl describe node knuc1`

> ...
> Capacity:
>   nvidia.com/gpu: 1
> ...
> Allocatable:
>   nvidia.com/gpu: 1

**Comment by klueska** [comment]
Hmm. It seems your config is not picked up at all because with your setting for ‘renameByDefault: true’ you shouldn’t have any nvidia.com/gpu resources and instead 4 nvidia.com/gpu.shared resources.

**Comment by shivamerla** [comment]
Can you paste the logs of device-plugin pod to confirm correct config is picked up? Install command looks fine, assuming ConfigMap is created in right namespace, time-slicing config should have been applied and resources created as "nvidia.com/gpu.shared" instead of `nvidia.com/gpu`. They might be stale entries, but new resources should have been added.

`kubectl logs -l app=nvidia-device-plugin-daemonset -n gpu-operator --all-containers`
`kubectl get node knuc1 -o json | jq '.metadata.labels'`
`kubectl get node knuc1 -o json | jq '.status.capacity'`
`kubectl get node knuc1 -o json | jq '.status.allocatable'`

**Comment by brianbrady** [comment]
@klueska 
Updated Config:
> ---
> apiVersion: v1
> data:
>   quadro-p2000: |-
>     version: v1
>     sharing:
>       timeSlicing:
>         renameByDefault: false
>         failRequestsGreaterThanOne: true
>         resources:
>         - name: nvidia.com/gpu
>           replicas: 4
> kind: ConfigMap

Deleted all pods:
`kubectl delete --all pods --namespace=gpu-operator`

knuc1 labels:
> labels:
>     ...
>     nvidia.com/cuda.driver.major: "510"
>     nvidia.com/cuda.driver.minor: "47"
>     nvidia.com/cuda.driver.rev: "03"
>     nvidia.com/cuda.runtime.major: "11"
>     nvidia.com/cuda.runtime.minor: "6"
>     nvidia.com/device-plugin.config: quadro-p2000
>     nvidia.com/gfd.timestamp: "1657575730"
>     nvidia.com/gpu.compute.major: "6"
>     nvidia.com/gpu.compute.minor: "1"
>     nvidia.com/gpu.count: "1"
>     nvidia.com/gpu.deploy.container-toolkit: "true"
>     nvidia.com/gpu.deploy.dcgm: "true"
>     nvidia.com/gpu.deploy.dcgm-exporter: "true"
>     nvidia.com/gpu.deploy.device-plugin: "true"
>     nvidia.com/gpu.deploy.driver: "true"
>     nvidia.com/gpu.deploy.gpu-feature-discovery: "true"
>     nvidia.com/gpu.deploy.node-status-exporter: "true"
>     nvidia.com/gpu.deploy.nvsm: ""
>     nvidia.com/gpu.deploy.operator-validator: "true"
>     nvidia.com/gpu.family: pascal
>     nvidia.com/gpu.machine: NUC11BTMi7
>     nvidia.com/gpu.memory: "5120"
>     nvidia.com/gpu.present: "true"
>     nvidia.com/gpu.product: Quadro-P2000
>     nvidia.com/mig.strategy: single
>   ...
> status:
>   ...
>   allocatable:
>     ...
>     nvidia.com/gpu: "1"
>     ...
>   capacity:
> ...
>     nvidia.com/gpu: "1"

**Comment by brianbrady** [comment]
@shivamerla 
kubectl logs -l app=nvidia-device-plugin-daemonset -n gpu-operator --all-containers
> waiting for nvidia container stack to be setup
> waiting for nvidia container stack to be setup
> 2022/07/11 21:42:10 Loading NVML
> 2022/07/11 21:42:10 Starting FS watcher.
> 2022/07/11 21:42:10 Starting OS watcher.
> 2022/07/11 21:42:10 Retreiving plugins.
> 2022/07/11 21:42:10 No MIG devices found. Falling back to mig.strategy=&{}
> 2022/07/11 21:42:10 Starting GRPC server for 'nvidia.com/gpu'
> 2022/07/11 21:42:10 Starting to serve 'nvidia.com/gpu' on /var/lib/kubelet/device-plugins/nvidia-gpu.sock
> 2022/07/11 21:42:10 Registered device plugin for 'nvidia.com/gpu' with Kubelet

`kubectl get node knuc1 -o json | jq '.metadata.labels'`
> {
>   "beta.kubernetes.io/arch": "amd64",
>   "beta.kubernetes.io/os": "linux",
>   "feature.node.kubernetes.io/cpu-cpuid.ADX": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AESNI": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX2": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX512BITALG": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX512BW": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX512CD": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX512DQ": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX512F": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX512IFMA": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX512VBMI": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX512VBMI2": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX512VL": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX512VNNI": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX512VP2INTERSECT": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX512VPOPCNTDQ": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.FMA3": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.GFNI": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.IBPB": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.MOVDIR64B": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.MOVDIRI": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.SHA": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.STIBP": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.VAES": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.VMX": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.VPCLMULQDQ": "true",
>   "feature.node.kubernetes.io/cpu-cstate.enabled": "true",
>   "feature.node.kubernetes.io/cpu-hardware_multithreading": "true",
>   "feature.node.kubernetes.io/cpu-pstate.scaling_governor": "powersave",
>   "feature.node.kubernetes.io/cpu-pstate.status": "active",
>   "feature.node.kubernetes.io/cpu-pstate.turbo": "true",
>   "feature.node.kubernetes.io/cpu-rdt.RDTL2CA": "true",
>   "feature.node.kubernetes.io/kernel-config.NO_HZ": "true",
>   "feature.node.kubernetes.io/kernel-config.NO_HZ_IDLE": "true",
>   "feature.node.kubernetes.io/kernel-version.full": "5.13.0-51-generic",
>   "feature.node.kubernetes.io/kernel-version.major": "5",
>   "feature.node.kubernetes.io/kernel-version.minor": "13",
>   "feature.node.kubernetes.io/kernel-version.revision": "0",
>   "feature.node.kubernetes.io/pci-10de.present": "true",
>   "feature.node.kubernetes.io/pci-1d6a.present": "true",
>   "feature.node.kubernetes.io/pci-8086.present": "true",
>   "feature.node.kubernetes.io/pci-8086.sriov.capable": "true",
>   "feature.node.kubernetes.io/storage-nonrotationaldisk": "true",
>   "feature.node.kubernetes.io/system-os_release.ID": "ubuntu",
>   "feature.node.kubernetes.io/system-os_release.VERSION_ID": "20.04",
>   "feature.node.kubernetes.io/system-os_release.VERSION_ID.major": "20",
>   "feature.node.kubernetes.io/system-os_release.VERSION_ID.minor": "04",
>   "feature.node.kubernetes.io/usb-ef_0bda_49f1.present": "true",
>   "kubernetes.io/arch": "amd64",
>   "kubernetes.io/hostname": "knuc1",
>   "kubernetes.io/os": "linux",
>   "network-role": "ingress-node",
>   "node-role.kubernetes.io/worker": "worker",
>   "nvidia.com/cuda.driver.major": "510",
>   "nvidia.com/cuda.driver.minor": "47",
>   "nvidia.com/cuda.driver.rev": "03",
>   "nvidia.com/cuda.runtime.major": "11",
>   "nvidia.com/cuda.runtime.minor": "6",
>   "nvidia.com/device-plugin.config": "quadro-p2000",
>   "nvidia.com/gfd.timestamp": "1657575730",
>   "nvidia.com/gpu.compute.major": "6",
>   "nvidia.com/gpu.compute.minor": "1",
>   "nvidia.com/gpu.count": "1",
>   "nvidia.com/gpu.deploy.container-toolkit": "true",
>   "nvidia.com/gpu.deploy.dcgm": "true",
>   "nvidia.com/gpu.deploy.dcgm-exporter": "true",
>   "nvidia.com/gpu.deploy.device-plugin": "true",
>   "nvidia.com/gpu.deploy.driver": "true",
>   "nvidia.com/gpu.deploy.gpu-feature-discovery": "true",
>   "nvidia.com/gpu.deploy.node-status-exporter": "true",
>   "nvidia.com/gpu.deploy.nvsm": "",
>   "nvidia.com/gpu.deploy.operator-validator": "true",
>   "nvidia.com/gpu.family": "pascal",
>   "nvidia.com/gpu.machine": "NUC11BTMi7",
>   "nvidia.com/gpu.memory": "5120",
>   "nvidia.com/gpu.present": "true",
>   "nvidia.com/gpu.product": "Quadro-P2000",
>   "nvidia.com/mig.strategy": "single"
> }

`kubectl get node knuc1 -o json | jq '.status.capacity'`
> {
>   "cpu": "16",
>   "ephemeral-storage": "959863856Ki",
>   "hugepages-1Gi": "0",
>   "hugepages-2Mi": "0",
>   "memory": "65474788Ki",
>   "nvidia.com/gpu": "1",
>   "pods": "110"
> }

`kubectl get node knuc1 -o json | jq '.status.allocatable'`

> {
>   "cpu": "16",
>   "ephemeral-storage": "884610528225",
>   "hugepages-1Gi": "0",
>   "hugepages-2Mi": "0",
>   "memory": "65372388Ki",
>   "nvidia.com/gpu": "1",
>   "pods": "110"
> }

**Comment by shivamerla** [comment]
@brianbrady can you confirm if you are using v1.11.0 of operator. Looks like its the old one.

**Comment by klueska** [comment]
Those logs indicate an old plugin. What version of the operator are you running? The new time-slicing support is only available as of operator 1.11.

**Comment by brianbrady** [comment]
FYSA I did try clearing out all of the nvidia.com labels out of knuc1 prior to deploying the GPU Operator.

**Comment by shivamerla** [comment]
Please upgrade to latest version. You need to update CRD + Operator as mentioned here: 
https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#using-helm, Also run "helm repo update" prior to ensure latest chart is pulled.

**Comment by brianbrady** [comment]
- `helm repo update`
> Hang tight while we grab the latest from your chart repositories...
> ...Successfully got an update from the "nvidia" chart repository
> Update Complete. ⎈Happy Helming!⎈

- `helm delete -n gpu-operator $(helm list -n gpu-operator | grep gpu-operator | awk '{print $1}')`
> release "gpu-operator-1657552313" uninstalled

- Deleted nvidia.com/* labels on knuc1

- Deleted gpu-operator Config Maps
- Deleted Nvidia CRD clusterpolicies.nvidia.com
- Rebooted knuc1 
- Applied time-slicing-config
> apiVersion: v1
> kind: ConfigMap
> data:
>   quadro-p2000: |-
>     version: v1
>     sharing:
>       timeSlicing:
>         renameByDefault: false
>         failRequestsGreaterThanOne: true
>         resources:
>         - name: nvidia.com/gpu
>           replicas: 4

- kubectl label node knuc1 nvidia.com/device-plugin.config=quadro-p2000
- `helm install --wait --generate-name -n gpu-operator --create-namespace nvidia/gpu-operator --set op
erator.defaultRuntime=containerd --set devicePlugin.config.name=time-slicing-config --set devicePlugin.config.default=qu
adro-p2000`
> NAME: gpu-operator-1657577502
> LAST DEPLOYED: Mon Jul 11 16:11:45 2022
> NAMESPACE: gpu-operator
> STATUS: deployed
> REVISION: 1
> TEST SUITE: None

- `kubectl get node knuc1 -o json | jq '.metadata.labels'`
> {
>   "beta.kubernetes.io/arch": "amd64",
>   "beta.kubernetes.io/os": "linux",
>   "feature.node.kubernetes.io/cpu-cpuid.ADX": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AESNI": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX2": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX512BITALG": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX512BW": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX512CD": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX512DQ": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX512F": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX512IFMA": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX512VBMI": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX512VBMI2": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX512VL": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX512VNNI": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX512VP2INTERSECT": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.AVX512VPOPCNTDQ": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.FMA3": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.GFNI": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.IBPB": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.MOVDIR64B": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.MOVDIRI": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.SHA": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.STIBP": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.VAES": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.VMX": "true",
>   "feature.node.kubernetes.io/cpu-cpuid.VPCLMULQDQ": "true",
>   "feature.node.kubernetes.io/cpu-cstate.enabled": "true",
>   "feature.node.kubernetes.io/cpu-hardware_multithreading": "true",
>   "feature.node.kubernetes.io/cpu-pstate.scaling_governor": "powersave",
>   "feature.node.kubernetes.io/cpu-pstate.status": "active",
>   "feature.node.kubernetes.io/cpu-pstate.turbo": "true",
>   "feature.node.kubernetes.io/cpu-rdt.RDTL2CA": "true",
>   "feature.node.kubernetes.io/kernel-config.NO_HZ": "true",
>   "feature.node.kubernetes.io/kernel-config.NO_HZ_IDLE": "true",
>   "feature.node.kubernetes.io/kernel-version.full": "5.13.0-51-generic",
>   "feature.node.kubernetes.io/kernel-version.major": "5",
>   "feature.node.kubernetes.io/kernel-version.minor": "13",
>   "feature.node.kubernetes.io/kernel-version.revision": "0",
>   "feature.node.kubernetes.io/pci-10de.present": "true",
>   "feature.node.kubernetes.io/pci-1d6a.present": "true",
>   "feature.node.kubernetes.io/pci-8086.present": "true",
>   "feature.node.kubernetes.io/pci-8086.sriov.capable": "true",
>   "feature.node.kubernetes.io/storage-nonrotationaldisk": "true",
>   "feature.node.kubernetes.io/system-os_release.ID": "ubuntu",
>   "feature.node.kubernetes.io/system-os_release.VERSION_ID": "20.04",
>   "feature.node.kubernetes.io/system-os_release.VERSION_ID.major": "20",
>   "feature.node.kubernetes.io/system-os_release.VERSION_ID.minor": "04",
>   "feature.node.kubernetes.io/usb-ef_0bda_49f1.present": "true",
>   "kubernetes.io/arch": "amd64",
>   "kubernetes.io/hostname": "knuc1",
>   "kubernetes.io/os": "linux",
>   "network-role": "ingress-node",
>   "node-role.kubernetes.io/worker": "worker",
>   "nvidia.com/cuda.driver.major": "515",
>   "nvidia.com/cuda.driver.minor": "48",
>   "nvidia.com/cuda.driver.rev": "07",
>   "nvidia.com/cuda.runtime.major": "11",
>   "nvidia.com/cuda.runtime.minor": "7",
>   "nvidia.com/device-plugin.config": "quadro-p2000",
>   "nvidia.com/gfd.timestamp": "1657577658",
>   "nvidia.com/gpu.compute.major": "6",
>   "nvidia.com/gpu.compute.minor": "1",
>   "nvidia.com/gpu.count": "1",
>   "nvidia.com/gpu.deploy.container-toolkit": "true",
>   "nvidia.com/gpu.deploy.dcgm": "true",
>   "nvidia.com/gpu.deploy.dcgm-exporter": "true",
>   "nvidia.com/gpu.deploy.device-plugin": "true",
>   "nvidia.com/gpu.deploy.driver": "true",
>   "nvidia.com/gpu.deploy.gpu-feature-discovery": "true",
>   "nvidia.com/gpu.deploy.node-status-exporter": "true",
>   "nvidia.com/gpu.deploy.nvsm": "",
>   "nvidia.com/gpu.deploy.operator-validator": "true",
>   "nvidia.com/gpu.family": "pascal",
>   "nvidia.com/gpu.machine": "NUC11BTMi7",
>   "nvidia.com/gpu.memory": "5368709120",
>   "nvidia.com/gpu.present": "true",
>   "nvidia.com/gpu.product": "Quadro-P2000-SHARED",
>   "nvidia.com/gpu.replicas": "4",
>   "nvidia.com/mig.strategy": "single"
> }

- `kubectl get node knuc1 -o json | jq '.status.capacity'`
> {
>   "cpu": "16",
>   "ephemeral-storage": "959863856Ki",
>   "hugepages-1Gi": "0",
>   "hugepages-2Mi": "0",
>   "memory": "65474784Ki",
>   "nvidia.com/gpu": "4",
>   "pods": "110"
> }

- `kubectl get node knuc1 -o json | jq '.status.allocatable'`

>  {
>   "cpu": "16",
>   "ephemeral-storage": "884610528225",
>   "hugepages-1Gi": "0",
>   "hugepages-2Mi": "0",
>   "memory": "65372384Ki",
>   "nvidia.com/gpu": "4",
>   "pods": "110"
> }

**Looks to be Successfull. Thanks for pointing out my helm version mistake!**

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by brianbrady** [comment]
Thanks again!
