### ISSUE TITLE
CUDA memory error

### ISSUE THREAD

**Issue by Borchies** [NVIDIA/k8s-device-plugin#323]
### Issue or feature description
I am currently using `Time-Slicing` to have different services sharing resources in my Tesla T4 GPU in Kubernetes. Aim is to have 3 or 4 services/pods using that GPU, but as of now, I am having issues with 2 of them. At the beginning, the two services work well, but after a while, one of them increases the memory usage until it just crashes with the following message:

`RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 14.76 GiB total capacity; 4.37 GiB already allocated; 14.75 MiB free; 4.43 GiB reserved in total by PyTorch)`

Context for this is: According to the output from `nvidia-smi`, the GPU has a total memory of 15GiB, and the pod/service that works allocated around 9GiB, so when the other reaches to a point where it wants to allocate more memory than what it can, it crashes and restarts for infinity.

What would be the best way to tackle this issue? Is there a way to increase the GPU memory that my NVIDIA device plugin is using? I would really appreciate some insights on this!

Thank you in advance!

Kind regards,
Borja

**Comment by Borchies** [comment]
The two applications that I mentioned use ML models, and are written in Python
One of them is an AI-based question answering system that uses haystack and the other app is an image recognition system

**Comment by klueska** [comment]
As Evan mentioned, there is nothing we can do at the plugin level to alleviate this. Your applications will need to cooperatively allocate less memory so as not to force the other one to OOM. It seems as if pytorch has a way to limit this: https://github.com/pytorch/pytorch/blob/e44b2b72bd4ccecf9c2f6c18d09c11eff446b5a3/torch/cuda/memory.py#L75-L99

**Comment by Borchies** [comment]
Okay understood.

Just as a curiosity, the `nvidia-smi` output shows that the total allocatable memory is 15GiB, and my question is: On what depends that amount of total memory?

**Comment by klueska** [comment]
The plugin doesn't control that (nor can you control it from anywhere else). That is the total size of the physical memory available on the GPU.

**Comment by Borchies** [comment]
Okay, we will try to keep working on this from the application side then, thanks! 😊
