### ISSUE TITLE
undefined symbol nvmlGpuInstanceGetComputeInstanceProfileInfoV in v12+

### ISSUE THREAD

**Issue by anthonyrisinger** [NVIDIA/k8s-device-plugin#326]
I'm trying to update our clusters to the latest versions of various Nvidia components. When building from source and linking against `libnvidia-ml.so.460.73.01`, I see this when trying to run the resultant `nvidia-device-plugin` binary:

```
nvidia-device-plugin: undefined symbol: nvmlGpuInstanceGetComputeInstanceProfileInfoV
```

I didn't notice anything in release notes but haven't dug much deeper either since using v11.0 seems to work fine. Probably the driver version will be updated soon -- is 460.73.01 too old?

**Comment by klueska** [comment]
If you are building from source, make sure you are building with these flags:
```
go build -ldflags="-extldflags=-Wl,-z,lazy" <files>.go
```

**Comment by anthonyrisinger** [comment]
That was exactly it!

```
# Ensure libnvidia-ml.so.1 is DT_NEEDED so we fail fast.
export GO111MODULES=on CGO_ENABLED=1 CGO_LDFLAGS=-lnvidia-ml
go build -v -trimpath -tags=netgo,osusergo -buildmode=pie -ldflags='-s -w -extldflags=-Wl,-z,lazy'
```

LMK if there's a more obvious way to do the above (the intent is fast failing should the management library be missing, but maybe it's overly paranoid), thanks again!

**Comment by klueska** [comment]
It should already fail fast if NVML is not present on the system. When it tries to do the dynamic loading of libnvidia-ml it will fail if it’s not present.
