### ISSUE TITLE
Handling hot plug events

### ISSUE THREAD

**Issue by srinivas491-oneconvergence** [NVIDIA/k8s-device-plugin#34]
I'm working on a feature where I can hotplug nvidia gpus to the host. But when I did that, the device plugin is not recognizing the hotplugged gpu. 

 It would be great if the support for hotplug events is provided.

**Comment by flx42** [comment]
@RenaudWasTaken API-wise, would it work? The `ListAndWatch` will be called again if the device plugin re-registers, right?

The main issue being that if the device plugin runs in a container, the container will not have the right device cgroup to access the new GPU.

Two options then:
- Restart the whole daemonset on the node
- Run the device plugin outside of a container

**Comment by RenaudWasTaken** [comment]
Hello!

Hotplug GPUs at the container level is not a trivial problem and we don't have plans to address it immediately (though it is on our roadmap).

In the meantime my suggestion is that you restart the device plugin.

**Comment by RenaudWasTaken** [comment]
Feel free to re-open the issue of you have any questions :)
