### ISSUE TITLE
MIG for A6000

### ISSUE THREAD

**Issue by arijitthegame** [NVIDIA/k8s-device-plugin#340]
I have a quick about MIGs for A6000. The official docs says that MIG works for Ampere architecture an all the examples in the docs are for A100. My question is does MIG support A6000, since A6000 has compute capability 8.6?

**Comment by elezar** [comment]
MIG support is not determined by the compute capability as there are Ampere devices that do not support MIG. 

Please see the list of supported GPUs here: https://docs.nvidia.com/datacenter/tesla/mig-user-guide/index.html#supported-gpus
