### ISSUE TITLE
what k8s does behind device plugin ?

### ISSUE THREAD

**Issue by mingfengwuye** [NVIDIA/k8s-device-plugin#37]
I read another device plugin example, https://github.com/vikaschoudhary16/sfc-device-plugin
In this device plugin, during allocate phase, it only response the Host Path and Container Path of the device. So does it mean the k8s will mount the device to container?
In nvidia device plugin, it set an env "NVIDIA_VISIBLE_DEVICES", then the nvidia-container-cli will use the env, then mount the device to container.

**Comment by pineking** [comment]
see the docs: https://kubernetes.io/docs/concepts/cluster-administration/device-plugins/

**Comment by RenaudWasTaken** [comment]
> In this device plugin, during allocate phase, it only response the Host Path and Container Path of the device. So does it mean the k8s will mount the device to container?

So Kubelet fills the information in the CRI spec mounting is then handled in the CRI agent.

> In nvidia device plugin, it set an env "NVIDIA_VISIBLE_DEVICES", then the nvidia-container-cli will use the env, then mount the device to container.

yes.

If you still have any questions feel free to re-open the issue :)

**Comment by mingfengwuye** [comment]
So users could only set the numbers of gpu they want to use. They could not appoint which one to use, it will be allocate by k8s. 
Yes ?

**Comment by RenaudWasTaken** [comment]
> So users could only set the numbers of gpu they want to use. They could not appoint which one to use, it will be allocated by k8s. K8s does not know the differences between gpus. If i want to appoint the desired gpu, what may i need to do ?

You don't really have any options that would be supported by Kubernetes currently. Can you describe your use case a bit more? I might have a few suggestions :)

**Comment by mingfengwuye** [comment]
there are may different kinds of gpus in cluster, such as k80 and k40. they have different memory capacity or cuda cores. so user may want to apply k80, but cluster may allocate k40, user can not use the desired one. cluster only remember a device id.

**Comment by RenaudWasTaken** [comment]
As long as you have homogeneous nodes (i.e: All GPUs on a node are the same), you can use node labels, to select the GPU kind

**Comment by mingfengwuye** [comment]
One more question, now one gpu only could be used in one container. what is about a more complex condition, one gpu is mounted to two or three containers, but they use different cuda cores and memories.

**Comment by pineking** [comment]
@mingfengwuye For one GPU is shared between multi containers, I do not think this is a correct way for deep learning trainning.

**Comment by mingfengwuye** [comment]
The efficiency may be too low, it is just some kind of thinkings. I think about it a little more, if multi users use the GPU same time, an arbiter is need to decide which one to use the only one bus, the switch cost may be too high.

**Comment by RenaudWasTaken** [comment]
> One more question, now one gpu only could be used in one container. what is about a more complex condition, one gpu is mounted to two or three containers, but they use different cuda cores and memories.

That's not currently possible with Kubernetes. We however have a design document that is being reviewed by the community for that.
If you are interested you can join the resource management [workgroup google group](https://groups.google.com/forum/#!forum/kubernetes-wg-resource-management).

> @mingfengwuye For one GPU is shared between multi containers, I do not think this is a correct way for deep learning trainning.

Training not really but it makes sense for inference.

**Comment by mingfengwuye** [comment]
@RenaudWasTaken thank you very much. I have joined the group. It is a possible method to share GPU between containers in inference situation.
