### ISSUE TITLE
Manifest in upstream kubernetes?

### ISSUE THREAD

**Issue by ktsakalozos** [NVIDIA/k8s-device-plugin#38]
The yaml manifest available upstream [1] a) is not the one suggested in the project's README [2] and b) is gke specific. As a result it is not clear to the kubernetes distributions (such as for example CDK [3]) what manifest should be shipped with each k8s release. We are doing our best, but any feedback from you on what the right path is, would be much appreciated.

[1] https://github.com/kubernetes/kubernetes/blob/release-1.10/cluster/addons/device-plugins/nvidia-gpu/daemonset.yaml
[2]  https://github.com/NVIDIA/k8s-device-plugin/blob/v1.9/nvidia-device-plugin.yml
[3] https://www.ubuntu.com/kubernetes

**Comment by RenaudWasTaken** [comment]
Hello @ktsakalozos !

> The yaml manifest available upstream
> a) is not the one suggested in the project's README
> b) is gke specific

So currently if you are using [COS](https://cloud.google.com/container-optimized-os/docs/) as your host OS you are better off using the GKE device plugin (installing the drivers + the NVIDIA container runtime is not an easy feat).

On other distributions you are better off using the NVIDIA device plugin as it allows you to run more NVIDIA images (graphics) and has health checking features.
The README on this repository should give you more insights on how to install the device plugin.

Does that answer your question?

**Comment by ktsakalozos** [comment]
Thank you for your reply @RenaudWasTaken .

I am with the team that ships the Canonical Distribution of Kubernetes (CDK). We package Kubernetes and deploy it in Ubuntu images on any cloud (public/private) or bare metal. We would like to offer out of the box GPU support based on Nvidia's solution. Upon detecting GPU capable hardware we automatically install cuda-drivers and nvidia-docker2 and configure kubelet appropriately. What is not clear is which NVIDIA device plugin manifest should we apply. 

Note that as soon as Kubernetes releases we start testing it and we do a release of CDK within a week. If the NVIDIA plugin yaml manifest is not released with Kubernetes (upstream) it is not straight forward as to how we can support NVIDIA hardware in for example on prem deployments. Do you think we could coordinate somehow our releases? Could we for example have a non-gke specific yaml upstream?

**Comment by flx42** [comment]
We are already discussing with some of your colleagues. Please sync internally :)

**Comment by ktsakalozos** [comment]
Thank you
