### ISSUE TITLE
can k8s-device-plugin support numa-aware alloc

### ISSUE THREAD

**Issue by zmoon111** [NVIDIA/k8s-device-plugin#39]
we op one gpu cluster , every server has 4 gpus. suppose the id is 0, 1, 2,3. one job taken id 0， if the comming job needs 2 gpus. can  the plugin give 2,3 to kubelet？.(now is 1,2 ) if do this ，job in the same pcie can connect faster than in diffrent pcie  slot 。

**Comment by RenaudWasTaken** [comment]
This can't be done in the device plugin, Kubelet is in charge of assigning devices to the container.

However NUMA aware device assignation is definitely something we are looking at right now.

A workaround right now is to ask for all the GPUs
