### ISSUE TITLE
On the node with mig enabled, nvidia-device-plugin reports an error when it starts

### ISSUE THREAD

**Issue by yeqiugt** [NVIDIA/k8s-device-plugin#399]
I pulled the latest code and compiled it locally today，but on the node with mig enabled, nvidia-device-plugin reports an error when it starts
Below is the error log：
error starting plugins: unable to add default resources to config: error visiting devices: error visiting device: error visiting device: error getting device memory info: Insufficient Pemmissions
<img width="565" alt="ec7583c9ca700dba3121d57b046b331" src="https://user-images.githubusercontent.com/37202250/232771146-64987cf5-a143-41da-bede-87b0b11be578.png">

<img width="1091" alt="f8a22b1e68bd199bf9cc98728998dbc" src="https://user-images.githubusercontent.com/37202250/232771340-d51bd506-d1e9-48fa-a160-12e97ff173cc.png">

![image](https://user-images.githubusercontent.com/37202250/232775025-c652d595-e6a9-46b1-9ae6-7c40b21b477d.png)

<img width="565" alt="ec7583c9ca700dba3121d57b046b331" src="(https://user-images.githubusercontent.com/37202250/232775025-c652d595-e6a9-46b1-9ae6-7c40b21b477d.png">

**Comment by klueska** [comment]
How are you running the plugin? This is typical if you don't set the environment variable for NVIDIA_MIG_MONITOR_DEVICES=all on the plugin deployment.

**Comment by yeqiugt** [comment]
By doing this I did solve my problem, thanks a lot
