### ISSUE TITLE
Allocating same GPU to multiple requests

### ISSUE THREAD

**Issue by reverson** [NVIDIA/k8s-device-plugin#4]
Are you open to a PR that allocates the same GPU to multiple requests based on additional requirements passed to the process?

I'm thinking I could ask for `nvidia/gpu:1` and get 1 whole GPU, or I could ask for `nvidia/gpu-memory:1Gi` and `nvidia/gpu-cpu:2` and get "allocated" 1Gi of memory and 2 cores on 1 GPU, leaving whatever is left for other `nvidia/gpu-memory` and `nvidia/gpu-cpu` requests.

It wouldn't be enforced, but this way we can at least context switch between multiple processes on 1 GPU, which is something the main kubernetes project doesn't seem to want to support until at least v1.11 (https://github.com/kubernetes/kubernetes/issues/52757)

**Comment by ScorpioCPH** [comment]
@reverson Hi, as far as my experience, most GPU applications such as training a model use `TensorFlow`, it will occupy the whole GPU because the huge requirement of Hardware, so could you show us some use case about sharing GPU between multiple applications?

And I think we can't allocate `nvidia/gpu-cpu:2` of 2 cores on 1 GPU right now, please correct me if i'm wrong @flx42

**Comment by reverson** [comment]
I'm thinking more about using it for TF serving, as opposed to the training portion.

I know that allocating memory or processing resources on the GPU aren't enforced in any way (there aren't any hooks into the cgroup/kernel that I'm aware of), but this would be more as a way to being a "good citizen" and just requesting what you've configured your app to use.

**Comment by flx42** [comment]
I understand the need here, you are not the only one. But as you are aware this won't be enforced. As a result, this is not something I want to support officially for now, this would be too confusing.

**Comment by reverson** [comment]
That's cool, I'll fork this and play around with it for myself for now. Thanks!
