### ISSUE TITLE
Can we use k8s-device-plugin and Nvidia-docker2 in minikube?

### ISSUE THREAD

**Issue by yoshihingis** [NVIDIA/k8s-device-plugin#40]
1.Question
  This is not issue, only Question.
  Can we use k8s-device-plugin and Nvidia-docker2 in minikube

2.Enviroment
 ・OS:Ubuntu16.04
 ・minikube: v0.24.1
 ・ kubectl : v1.10.0
 ・ Nvidia driver :384.111
 ・ Docker :Client:
 　Version:	18.03.0-ce
 　API version:	1.37
 　Go version:	go1.9.4
　 Git commit:	0520e24
 　Built:	Wed Mar 21 23:10:01 2018
 　OS/Arch:	linux/amd64
 　Experimental:	false
 　Orchestrator:	swarm

　Server:
 　Engine:
  　Version:	18.03.0-ce
  　API version:	1.37 (minimum version 1.12)
  　Go version:	go1.9.4
  　Git commit:	0520e24
  　Built:	Wed Mar 21 23:08:31 2018
  　OS/Arch:	linux/amd64
  　Experimental:	false

・Results of kubectl version
 Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0",   GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}

・GPU:Maxwell Geforce TITUN-X

・ /erc/docker/daemon.json
{
    "dns": ["150.16.X.X", "150.16.X.X"],
    "runtimes": {
        "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}

3.Problem
  (1) I installerd minikube and kubectl to test Nvidia-docker2 .

  (2)I started  minikube as below
      sudo CHANGE_MINIKUBE_NONE_USER=true minikube start --vm-driver=none  --featuregates=Accelerators=true 

    ★Hyper visor=on(Ubuntu PC BIOS)
 
(2) I did as below 
　$ kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v1.8/nvidia-device-plugin.yml

 (3)Next I did as below
   $ kubectl create -f test.yml

(4) test.yml file
apiVersion: v1
kind: Pod
metadata:
  name: cuda-vector-add
spec:
  restartPolicy: OnFailure
  containers:
    - name: cuda-vector-add
      # https://github.com/kubernetes/kubernetes/blob/v1.7.11/test/images/nvidi$
      image: "k8s.gcr.io/cuda-vector-add:v0.1"
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU

(5)Results
   $ kubectl get pod 
NAME                                   READY     STATUS             RESTARTS   AGE
cuda-vector-add                        0/1       Pending            0          11s
nvidia-device-plugin-daemonset-mq4pm   0/1       CrashLoopBackOff   4          2m

★Pod error and nvidia-device-plugin-daemonset error

(6)My opinion
  I faced on this eroor(pods ans Daemon Set were nor Running), I think nvidia-device-plug in was disabel.
  But I don't kown the way to eanble nvidia-device-plug.
  Perhaps I must set --feature-gates="DevicePlugins=true.
  But minikube looks like that kubelet is not used.

★Could you any advices to use nvidia-docker2 in minikube?

**Comment by flx42** [comment]
> kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v1.8/nvidia-device-plugin.yml

That's the wrong version, you want to use `v1.10` instead for your setup.
That's probably the reason it fails to start.

>  But minikube looks like that kubelet is not used.

It does, but it requires a hack:
```
$ sudo emacs /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
# add --feature-gates=DevicePlugins=true
$ sudo systemctl daemon-reload
$ sudo systemctl restart kubelet.service
```
It's a hack because even if you script it, `minikube` will override the kubeadm configuration file the next time you do a `start`.
