### ISSUE TITLE
Who is maintaining this repo??

### ISSUE THREAD

**Issue by maaft** [NVIDIA/k8s-device-plugin#401]
Who is maintaining this repo? Or is this repository dead and there are alternatives that I'm not aware of?

**Comment by ArangoGutierrez** [comment]
This is a mirror of https://gitlab.com/nvidia/kubernetes/device-plugin 
Any contributions and issues should be taken there.

Thanks for your comment!

**Comment by maaft** [comment]
thanks! I think this should be written in the readme then, right?
