### ISSUE TITLE
The device will go unhealthy

### ISSUE THREAD

**Issue by id-aa-ling** [NVIDIA/k8s-device-plugin#415]
<img width="1374" alt="微信图片_20230615110942" src="https://github.com/NVIDIA/k8s-device-plugin/assets/60840469/0702400b-e7c0-40cd-898e-0cfe4338af14">

**Comment by lordofire** [comment]
Just curious why not let the devie plugin rediscover the device to avoid manual reset of device plugin pod?

**Comment by mingkai-yang** [comment]
> Just curious why not let the devie plugin rediscover the device to avoid manual reset of device plugin pod?
> 
> 只是好奇为什么不让devie插件重新发现设备以避免手动重置设备插件pod？
请问这个问题后续有根本解决发方法吗
