### ISSUE TITLE
Configuration for CDI mode?

### ISSUE THREAD

**Issue by kwohlfahrt** [NVIDIA/k8s-device-plugin#418]
### 1. Issue or feature description

I would like to test the new CDI features in the `0.14.0` release (because I suspect it might resolve some of the issues we see with an `CUDA initialization: CUDA unknown error` message). I'm using CRI-O as my container runner for this experiment - in production we use `containerd`, but the packages for it haven't been updated for version 1.7 (with CDI support).

I was able to start a GPU pod, but only if I configure the node with the following OCI hook:

```json
{
    "version": "1.0.0",
    "hook": {
        "path": "/usr/bin/nvidia-container-runtime-hook",
        "args": ["nvidia-container-runtime-hook", "prestart"],
        "env": [ "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" ]
    },
    "when": { "always": true, "commands": [".*"] },
    "stages": ["prestart"]
}
```

Otherwise, I see the error in the log below. However, [the `nvidia-container-toolkit` documentation](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#container-device-interface-cdi-support) suggests that configuring the hook should not be necessary when using CDI. So, I have some questions:

1. Should the device plugin work without an OCI hook when configured to use CDI? If yes, what changes do I need to make to the configuration below, to avoid the errors?
2. If the hook is required for the device plugin, how do I check that my workload pod is being provisioned with CDI?

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Logs (failed run):
```
I0619 17:46:11.262397      48 main.go:154] Starting FS watcher.
I0619 17:46:11.262485      48 main.go:161] Starting OS watcher.
I0619 17:46:11.262848      48 main.go:176] Starting Plugins.
I0619 17:46:11.262866      48 main.go:234] Loading configuration.
I0619 17:46:11.263235      48 main.go:242] Updating config with default resource matching patterns.
I0619 17:46:11.263288      48 main.go:253] 
Running with config:
{
  "version": "v1",
  "flags": {
    "migStrategy": "none",
    "failOnInitError": true,
    "nvidiaDriverRoot": "/",
    "gdsEnabled": false,
    "mofedEnabled": false,
    "plugin": {
      "passDeviceSpecs": true,
      "deviceListStrategy": [
        "volume-mounts"
      ],
      "deviceIDStrategy": "uuid",
      "cdiAnnotationPrefix": "cdi.k8s.io/",
      "nvidiaCTKPath": "/usr/bin/nvidia-ctk",
      "containerDriverRoot": "/driver-root"
    }
  },
  "resources": {
    "gpus": [
      {
        "pattern": "*",
        "name": "nvidia.com/gpu"
      }
    ]
  },
  "sharing": {
    "timeSlicing": {}
  }
}
I0619 17:46:11.263307      48 main.go:256] Retreiving plugins.
W0619 17:46:11.263463      48 factory.go:31] No valid resources detected, creating a null CDI handler
I0619 17:46:11.263510      48 factory.go:107] Detected non-NVML platform: could not load NVML library: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
I0619 17:46:11.263542      48 factory.go:107] Detected non-Tegra platform: /sys/devices/soc0/family file not found
E0619 17:46:11.263555      48 factory.go:115] Incompatible platform detected
E0619 17:46:11.263559      48 factory.go:116] If this is a GPU node, did you configure the NVIDIA Container Toolkit?
E0619 17:46:11.263563      48 factory.go:117] You can check the prerequisites at: https://github.com/NVIDIA/k8s-device-plugin#prerequisites
E0619 17:46:11.263567      48 factory.go:118] You can learn how to set the runtime at: https://github.com/NVIDIA/k8s-device-plugin#quick-start
E0619 17:46:11.263571      48 factory.go:119] If this is not a GPU node, you should set up a toleration or nodeSelector to only deploy this plugin on GPU nodes
E0619 17:46:11.276361      48 main.go:123] error starting plugins: error creating plugin manager: unable to create plugin manager: platform detection failed
```

DaemonSet definition:
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: nvidia-device-plugin
    app.kubernetes.io/name: nvidia-device-plugin
    app.kubernetes.io/version: 0.14.0
  name: nvidia-device-plugin-c223f052
  namespace: nvidia
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: nvidia-device-plugin
      app.kubernetes.io/name: nvidia-device-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: nvidia-device-plugin
        app.kubernetes.io/name: nvidia-device-plugin
        app.kubernetes.io/version: 0.14.0
    spec:
      affinity:
        nodeAffinity:
          # Trimmed, I don't think it's relevant
      containers:
      - name: nvidia-device-plugin-sidecar
        # Trimmed, I don't think it's relevant
      - env:
        - name: CONFIG_FILE
          value: /config/config.yaml
        - name: NVIDIA_MIG_MONITOR_DEVICES
          value: all
        image: nvcr.io/nvidia/k8s-device-plugin:v0.14.0
        name: nvidia-device-plugin-ctr
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /available-configs
          name: available-configs
        - mountPath: /var/lib/kubelet/device-plugins
          name: device-plugin
        - mountPath: /var/run/cdi
          name: cdi-root
        - mountPath: /host
          mountPropagation: HostToContainer
          name: host-root
          readOnly: true
      initContainers:
      - name: nvidia-device-plugin-init
        # Trimmed, I don't think it's relevant
      shareProcessNamespace: true
      volumes:
      - hostPath:
          path: /var/lib/kubelet/device-plugins
          type: Directory
        name: device-plugin
      - hostPath:
          path: /var/run/cdi
          type: DirectoryOrCreate
        name: cdi-root
      - hostPath:
          path: /
          type: Directory
        name: host-root
      - configMap:
          defaultMode: 420
          name: nvidia-device-plugin-4eb44413
        name: available-configs
      - emptyDir: {}
        name: config
```

**Comment by elezar** [comment]
Hi @kwohlfahrt. The CDI mode in the plugin was introduced to be used in the context of the GPU Operator. Although it is theoretically possible to use this standalone, this is not something that we've documented at present.

One issue is that the device plugin also needs access to NVIDIA devices and libraries to enumerate the available GPUs. In the context of the GPU operator we configure the NVIDIA Container Runtime as a runtime in the cri-o (or Containerd) config and then launch the device plugin using a runtime class associated with this runtime. This allows the Device Plugin to have the required access to generate the CDI specifications that can be used in CDI-enabled runtimes. In this case the hook you mention is then not needed.

Note that at present, in order to enable CDI mode, the `deviceListStrategy` must include `cdi-annotations` -- which is not the case in your applied config.

**Comment by kwohlfahrt** [comment]
> One issue is that the device plugin also needs access to NVIDIA devices and libraries to enumerate the available GPUs. In the context of the GPU operator we configure the NVIDIA Container Runtime as a runtime in the cri-o (or Containerd) config and then launch the device plugin using a runtime class associated with this runtime. This allows the Device Plugin to have the required access to generate the CDI specifications that can be used in CDI-enabled runtimes. In this case the hook you mention is then not needed.

OK, yes this makes sense. I was looking at the operator source, but couldn't quite figure out how this worked. Thank you for the explanation!

> Note that at present, in order to enable CDI mode, the deviceListStrategy must include cdi-annotations -- which is not the case in your applied config.

Oops, yes - I'd definitely set that on an earlier attempt, but pasted the wrong log snippet. The error (`could not load NVML library` is the same though).

> Although it is theoretically possible to use this standalone, this is not something that we've documented at present.

Should I get this working well in stand-alone mode, would a PR documenting the setup be welcome? Or is the intent to migrate all deployments to use the operator? We would prefer to continue using the standalone device plugin, as we have a few concerns about the operator (probably out of scope for discussion here?).

**Comment by elezar** [comment]
> If I get this working well in stand-alone mode, would a PR documenting the setup be welcome? Or is the intent to migrate all deployments to use the operator? We would prefer to continue using the standalone device plugin, as we have a few concerns about the operator (probably out of scope for discussion here?).

Yes, that would be welcome! There are still use cases for a standalone plugin, so enabling this is would definitely be useful.

**Comment by kwohlfahrt** [comment]
On another PR, you mentioned this is a read-only mirror, so I've opened a PR against the GitLab repo here https://gitlab.com/nvidia/kubernetes/device-plugin/-/merge_requests/298. Let me know if I should do it against the GitHub repo instead.

Otherwise, CDI mode is working for us and it has resolved the original `CUDA: Unknown error` issue for us.

**Comment by elezar** [comment]
Thanks for the MR, @kwohlfahrt. I'll have a look at it early next week.
