### ISSUE TITLE
Helm chart for v0.14.1

### ISSUE THREAD

**Issue by TornjV** [NVIDIA/k8s-device-plugin#427]
Version 0.14.1 seems like it's not released to helm yet

`chart "nvidia-device-plugin" version "0.14.1" not found in https://nvidia.github.io/k8s-device-plugin repository`

**Comment by klueska** [comment]
It appears the `v0.14.1` tag was created without updating the helm chart version to `0.14.1`:
https://github.com/NVIDIA/k8s-device-plugin/blob/v0.14.1/deployments/helm/nvidia-device-plugin/Chart.yaml#L5

It's unclear if this means that the 0.14.0 helm chart was overwritten by the helm chart meant for 0.14.1 or if 0.14.1 was not released at all.

@elezar can you take a look?

**Comment by elezar** [comment]
Thanks for raising this. The `0.14.1` helm chart was not published at all, meaning that the `0.14.0` chart is still valid.

**Comment by elezar** [comment]
I have just published the `v0.14.1` helm charts. Please let us know if we can close this issue.

**Comment by TornjV** [comment]
Yes the v0.14.1 is published and installs successfully 👍
