### ISSUE TITLE
Image registry.k8s.io/nfd/node-feature-discovery:v0.12.1 in helm chart is not available

### ISSUE THREAD

**Issue by 8rV1n** [NVIDIA/k8s-device-plugin#434]
### 1. Issue or feature description
Image registry.k8s.io/nfd/node-feature-discovery:v0.12.1 in helm chart is not available, I tried using proxy to different locations including HK, JP, Silicon Valley.

### 2. Steps to reproduce the issue
```bash
helm upgrade -i nvdp nvdp/nvidia-device-plugin \
    --version=0.14.1 \
    --namespace nvidia-device-plugin \
    --create-namespace \
    --set gfd.enabled=true
```
Then, `k -n nvidia-device-plugin describe pod` shows :
```text
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  36s               default-scheduler  Successfully assigned nvidia-device-plugin/nvdp-node-feature-discovery-master-7857575598-q4bxd to MASKED_OUT_HOSTNAME
  Warning  Failed     24s               kubelet            Failed to pull image "registry.k8s.io/nfd/node-feature-discovery:v0.12.1": rpc error: code = Unknown desc = Error response from daemon: Head "https://us-west2-docker.pkg.dev/v2/k8s-artifacts-prod/images/nfd/node-feature-discovery/manifests/v0.12.1": net/http: TLS handshake timeout
  Warning  Failed     24s               kubelet            Error: ErrImagePull
  Normal   BackOff    23s               kubelet            Back-off pulling image "registry.k8s.io/nfd/node-feature-discovery:v0.12.1"
  Warning  Failed     23s               kubelet            Error: ImagePullBackOff
  Normal   Pulling    9s (x2 over 35s)  kubelet            Pulling image "registry.k8s.io/nfd/node-feature-discovery:v0.12.1"
```
### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Common error checking:
 - [x] The kubelet logs on the node (e.g: `sudo journalctl -r -u kubelet`) - See above

Additional information that might help better understand your environment and reproduce the bug:
- I tried to search where the "registry.k8s.io/nfd/node-feature-discovery:v0.12.1" image could be, but I can not really find a v0.12.1 image from the Internet(eg. [quay.io node-feature-discovery](https://quay.io/repository/kubernetes_incubator/node-feature-discovery?tab=tags&tag=latest)). I'm wondering whether this is the right Image to use.

**Comment by yitingdc** [comment]
How did you resolve it finally?
