### ISSUE TITLE
Does the nvidia-device-plugin need to be running on all worker nodes?

### ISSUE THREAD

**Issue by Itfly** [NVIDIA/k8s-device-plugin#45]
I can deploy the device-plugin on my gpu nodes successfully. After running `kubectl create` command, all the worker nodes deploy one nvidia-device-plugin. I know this is because using `DaemonSet` to deploy the plugin, but what confuses me is that do we also need to deploy the plugin on these non-gpu nodes?

Suggest to add `Node affinity` `requiredDuringSchedulingIgnoredDuringExecution` type or `nodeSelector`

**Comment by liyimeng** [comment]
Maybe you should label your GPU/non-GPU node and deploy the daemon set with node selector https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#running-pods-on-only-some-nodes?

**Comment by RenaudWasTaken** [comment]
Sorry I just saw your issue.
Yep we could add Node affinity but you'd then have to label your nodes.
We're working on that!
