### ISSUE TITLE
allocatable resource not reduce when gpu resource having by pod use

### ISSUE THREAD

**Issue by lengrongfu** [NVIDIA/k8s-device-plugin#452]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._
---

### 1. Issue or feature description
allocatable resource not reduce when gpu resource having by pod use.

### 2. Steps to reproduce the issue

1. install k8s-device-plugin
2. apply gpu pod, set nvidia.com/gpu: 1 to limits.
3. describe node allocatable data.

**Comment by klueska** [comment]
That is not how ‘Allocatable’ works in Kubernetes. It is the total number of resources *available* for allocation (not a real-time representation of how many resources have been allocated). In the context of GPUs you can think of it as Capacity —> total # GPUs, Allocatable —> # healthy GPUs.
