### ISSUE TITLE
Is ClusterRole necessary for timeslicing?

### ISSUE THREAD

**Issue by erikschul** [NVIDIA/k8s-device-plugin#463]
---

### 1. Issue or feature description
I'd like to allow multiple pods to share a GPU, by using "timeslicing".

I've added the config:
```
version: v1
    sharing:
    	timeSlicing:
    	resources:
    	- name: nvidia.com/gpu
    		replicas: 10
```

but it causes the helm chart to a lot of changes. I'm guessing that these are necessary because an otherwise empty configmap would override the defaults, so the defaults have to be set in the resources? Example:

---

<img width="496" alt="image" src="https://github.com/NVIDIA/k8s-device-plugin/assets/128804597/89e0f1a6-6db0-4f5c-8428-49abb454da4a">

---

But it also adds a ClusterRole, which I'm not so happy about.
Is it really necessary?
I had the impression that all this configuration would do, would be to set "nvidia.com/gpu" to 10 instead of 1.
Or is the `nvidia-device-plugin` also doing scheduling, which requires it to evaluate all nodes?

**Comment by chipzoller** [comment]
I think can be closed as no longer relevant. The Helm chart does not create a ClusterRole when a device plugin config is provided either in-line to the values or pointed to an external ConfigMap.
