### ISSUE TITLE
How to solve could not load NVML library: libnvidia-ml.so.1

### ISSUE THREAD

**Issue by yeeeee7** [NVIDIA/k8s-device-plugin#478]
k8s : minikube start --kubernetes-version=v1.25.16 --force --driver=docker
helm cmd:
helm upgrade -i nvdp nvdp/nvidia-device-plugin \
  --namespace nvidia-device-plugin \
  --create-namespace \
  --version 0.14.3 \
  --set runtimeClassName=nvidia

cat /etc/containerd/config.toml
version = 2

[plugins]

  [plugins."io.containerd.grpc.v1.cri"]

    [plugins."io.containerd.grpc.v1.cri".containerd]
      default_runtime_name = "nvidia"

      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]

        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia]
          privileged_without_host_devices = false
          runtime_engine = ""
          runtime_root = ""
          runtime_type = "io.containerd.runc.v2"

          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options]
            BinaryName = "/usr/bin/nvidia-container-runtime"

nvidia-smi cmd:
Wed Jan 17 23:43:04 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:08.0 Off |                    0 |
| N/A   36C    P0    52W / 300W |  26742MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     15466      C   python                          26740MiB |
+-----------------------------------------------------------------------------+

kubectl logs -f -n nvidia-device-plugin   nvdp-nvidia-device-plugin-9dbf7
I0117 15:43:15.905641       1 main.go:154] Starting FS watcher.
I0117 15:43:15.905756       1 main.go:161] Starting OS watcher.
I0117 15:43:15.906127       1 main.go:176] Starting Plugins.
I0117 15:43:15.906157       1 main.go:234] Loading configuration.
I0117 15:43:15.906298       1 main.go:242] Updating config with default resource matching patterns.
I0117 15:43:15.906538       1 main.go:253] 
Running with config:
{
  "version": "v1",
  "flags": {
    "migStrategy": "none",
    "failOnInitError": true,
    "nvidiaDriverRoot": "/",
    "gdsEnabled": false,
    "mofedEnabled": false,
    "plugin": {
      "passDeviceSpecs": false,
      "deviceListStrategy": [
        "envvar"
      ],
      "deviceIDStrategy": "uuid",
      "cdiAnnotationPrefix": "cdi.k8s.io/",
      "nvidiaCTKPath": "/usr/bin/nvidia-ctk",
      "containerDriverRoot": "/driver-root"
    }
  },
  "resources": {
    "gpus": [
      {
        "pattern": "*",
        "name": "nvidia.com/gpu"
      }
    ]
  },
  "sharing": {
    "timeSlicing": {}
  }
}
I0117 15:43:15.906553       1 main.go:256] Retreiving plugins.
W0117 15:43:15.907261       1 factory.go:31] No valid resources detected, creating a null CDI handler
I0117 15:43:15.907336       1 factory.go:107] Detected non-NVML platform: could not load NVML library: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
I0117 15:43:15.907377       1 factory.go:107] Detected non-Tegra platform: /sys/devices/soc0/family file not found
E0117 15:43:15.907388       1 factory.go:115] Incompatible platform detected
E0117 15:43:15.907392       1 factory.go:116] If this is a GPU node, did you configure the NVIDIA Container Toolkit?
E0117 15:43:15.907396       1 factory.go:117] You can check the prerequisites at: https://github.com/NVIDIA/k8s-device-plugin#prerequisites
E0117 15:43:15.907401       1 factory.go:118] You can learn how to set the runtime at: https://github.com/NVIDIA/k8s-device-plugin#quick-start
E0117 15:43:15.907405       1 factory.go:119] If this is not a GPU node, you should set up a toleration or nodeSelector to only deploy this plugin on GPU nodes

**Comment by yeeeee7** [comment]
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    meta.helm.sh/release-name: nvdp
    meta.helm.sh/release-namespace: nvidia-device-plugin
  creationTimestamp: "2024-01-17T15:16:12Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: nvdp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nvidia-device-plugin
    app.kubernetes.io/version: 0.14.3
    helm.sh/chart: nvidia-device-plugin-0.14.3
  name: nvdp-nvidia-device-plugin
  namespace: nvidia-device-plugin
  resourceVersion: "128315"
  uid: 4528100a-7e0c-4871-a27e-a7112c87aebb
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: nvdp
      app.kubernetes.io/name: nvidia-device-plugin
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: nvdp
        app.kubernetes.io/name: nvidia-device-plugin
    spec:
      containers:
      - env:
        - name: NVIDIA_MIG_MONITOR_DEVICES
          value: all
        image: nvcr.io/nvidia/k8s-device-plugin:v0.14.3
        imagePullPolicy: IfNotPresent
        name: nvidia-device-plugin-ctr
        resources: {}
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/kubelet/device-plugins
          name: device-plugin
      dnsPolicy: ClusterFirst
      priorityClassName: system-node-critical
      restartPolicy: Always
      runtimeClassName: nvidia
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
      volumes:
      - hostPath:
          path: /var/lib/kubelet/device-plugins
          type: ""
        name: device-plugin
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate

**Comment by NayamAmarshe** [comment]
I'm having the same issue. 

```bash
$ kubectl logs -n kube-system nvidia-device-plugin-daemonset-zndv7
I0121 12:04:24.655909       1 main.go:154] Starting FS watcher.
I0121 12:04:24.658440       1 main.go:161] Starting OS watcher.
I0121 12:04:24.658816       1 main.go:176] Starting Plugins.
I0121 12:04:24.658840       1 main.go:234] Loading configuration.
I0121 12:04:24.658960       1 main.go:242] Updating config with default resource matching patterns.
I0121 12:04:24.659189       1 main.go:253] 
Running with config:
{
  "version": "v1",
  "flags": {
    "migStrategy": "none",
    "failOnInitError": false,
    "nvidiaDriverRoot": "/",
    "gdsEnabled": false,
    "mofedEnabled": false,
    "plugin": {
      "passDeviceSpecs": false,
      "deviceListStrategy": [
        "envvar"
      ],
      "deviceIDStrategy": "uuid",
      "cdiAnnotationPrefix": "cdi.k8s.io/",
      "nvidiaCTKPath": "/usr/bin/nvidia-ctk",
      "containerDriverRoot": "/driver-root"
    }
  },
  "resources": {
    "gpus": [
      {
        "pattern": "*",
        "name": "nvidia.com/gpu"
      }
    ]
  },
  "sharing": {
    "timeSlicing": {}
  }
}
I0121 12:04:24.659210       1 main.go:256] Retreiving plugins.
W0121 12:04:24.666244       1 factory.go:31] No valid resources detected, creating a null CDI handler
I0121 12:04:24.666347       1 factory.go:107] Detected non-NVML platform: could not load NVML library: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
I0121 12:04:24.666407       1 factory.go:107] Detected non-Tegra platform: /sys/devices/soc0/family file not found
E0121 12:04:24.666416       1 factory.go:115] Incompatible platform detected
E0121 12:04:24.666441       1 factory.go:116] If this is a GPU node, did you configure the NVIDIA Container Toolkit?
E0121 12:04:24.666459       1 factory.go:117] You can check the prerequisites at: https://github.com/NVIDIA/k8s-device-plugin#prerequisites
E0121 12:04:24.666464       1 factory.go:118] You can learn how to set the runtime at: https://github.com/NVIDIA/k8s-device-plugin#quick-start
E0121 12:04:24.666468       1 factory.go:119] If this is not a GPU node, you should set up a toleration or nodeSelector to only deploy this plugin on GPU nodes
I0121 12:04:24.666476       1 main.go:287] No devices found. Waiting indefinitely.

```

nvidia-smi:
```bash
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1660 ...    On  | 00000000:29:00.0  On |                  N/A |
|  0%   33C    P8              15W / 125W |    244MiB /  6144MiB |      8%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1497      G   /usr/bin/gnome-shell                        241MiB |
+---------------------------------------------------------------------------------------+
```

```bash
$ cat /etc/containerd/config.toml
disabled_plugins = ["cri"]
version = 1

[plugins]

  [plugins.cri]

    [plugins.cri.containerd]

      [plugins.cri.containerd.runtimes]

        [plugins.cri.containerd.runtimes.nvidia]
          privileged_without_host_devices = false
          runtime_engine = ""
          runtime_root = ""
          runtime_type = "io.containerd.runc.v2"

          [plugins.cri.containerd.runtimes.nvidia.options]
            BinaryName = "/usr/bin/nvidia-container-runtime"
            Runtime = "/usr/bin/nvidia-container-runtime"
```

**Comment by klueska** [comment]
You don’t appear to have the NVIDIA runtime set as the default in your containerd config.

**Comment by NayamAmarshe** [comment]
> You don’t appear to have the NVIDIA runtime set as the default in your containerd config.

Oops, sorry. I'm using docker, not containerd and there it's set as default. Docker detects the GPU just fine when using --gpus all but kubectl detects 0/1 nodes.

**Comment by klueska** [comment]
—gpus=alll uses a different code path.

To test that the default runtime is set correctly you need to run:

docker run -e NVIDIA_VIDIBLE_DEVICES=all …

As a side note, may  I ask what setting you are using in the kubelet to ensure that docker is used as the underlying runtime? Containerd is the default.

**Comment by NayamAmarshe** [comment]
> —gpus=alll uses a different code path.
> 
> To test that the default runtime is set correctly you need to run:
> 
> docker run -e NVIDIA_VIDIBLE_DEVICES=all …
> 
> As a side note, may I ask what setting you are using in the kubelet to ensure that docker is used as the underlying runtime? Containerd is the default.

I'm using the kubernetes that comes with Docker Desktop.

```
$ kubectl get nodes -o wide

NAME             STATUS   ROLES           AGE     VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE         KERNEL-VERSION    CONTAINER-RUNTIME
docker-desktop   Ready    control-plane   2d18h   v1.28.2   192.168.65.9   <none>        Docker Desktop   6.5.11-linuxkit   docker://24.0.7
```

**Comment by klueska** [comment]
GPUs are not currently supported under docker desktop because it starts a VM between the host and the containers and we don’t have any tooling to set the VM up with GPU support itself.

**Comment by NayamAmarshe** [comment]
> GPUs are not currently supported under docker desktop because it starts a VM between the host and the containers and we don’t have any tooling to set the VM up with GPU support itself.

Ah ok. So I should install kubernetes manually instead of using this option then?
<img width="823" alt="image" src="https://github.com/NVIDIA/k8s-device-plugin/assets/25067102/1e488d60-fde6-4781-87a6-42a0eea1200a">

**Comment by NayamAmarshe** [comment]
@klueska The error is still the same after installing Kubernetes via minikube (docker runtime).

**Comment by klueska** [comment]
No matter how you run Kubernetes you will continue to have problems as long as you are using docker desktop.

**Comment by NayamAmarshe** [comment]
> No matter how you run Kubernetes you will continue to have problems as long as you are using docker desktop.

I have uninstalled Docker Desktop already and installed minikube from scratch.

**Comment by klueska** [comment]
And you’ve followed all of these steps for installing the NVIDIA container toolkit and making nvidia the default docker runtime?

https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html

**Comment by klueska** [comment]
Independent of that, what are you doing in minikube to ensure that the docker container that’s starts to represent a k8s node has the toolkit installed within it (as well as has access to GPUs)?

**Comment by NayamAmarshe** [comment]
> And you’ve followed all of these steps for installing the NVIDIA container toolkit and making nvidia the default docker runtime?
> 
> https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html

Hi, yes, I've followed all the steps mentioned. Independently, Docker seems to run fine with the GPU. Just not with Kubernetes.

**Comment by NayamAmarshe** [comment]
> Independent of that, what are you doing in minikube to ensure that the docker container that’s starts to represent a k8s node has the toolkit installed within it (as well as has access to GPUs)?

I've followed the steps mentioned here for using Minikube with Nvidia GPUs: https://minikube.sigs.k8s.io/docs/tutorials/nvidia/

I've installed nvidia-container-toolkit which seems to be working with `docker run`.
Then I installed k8s-device-plugin, following the instructions but the example gpu-pod is still stuck on pending.

```
$ kubectl get pods                                                                   
NAME      READY   STATUS    RESTARTS   AGE
gpu-pod   0/1     Pending   0          46h
```
```
$ kubectl describe pod gpu-pod
Name:             gpu-pod
Namespace:        default
Priority:         0
Service Account:  default
Node:             <none>
Labels:           <none>
Annotations:      <none>
Status:           Pending
IP:               
IPs:              <none>
Containers:
  cuda-container:
    Image:      nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2
    Port:       <none>
    Host Port:  <none>
    Limits:
      nvidia.com/gpu:  1
    Requests:
      nvidia.com/gpu:  1
    Environment:       <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-55b5t (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  kube-api-access-55b5t:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
                             nvidia.com/gpu:NoSchedule op=Exists
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  46h (x2 over 46h)    default-scheduler  0/1 nodes are available: 1 Insufficient nvidia.com/gpu. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..
  Warning  FailedScheduling  11s (x2 over 5m11s)  default-scheduler  0/1 nodes are available: 1 Insufficient nvidia.com/gpu. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..
  Warning  FailedScheduling  46h                  default-scheduler  0/1 nodes are available: 1 Insufficient nvidia.com/gpu. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..
```

**Comment by klueska** [comment]
It sound like an issue running under minikube then (I’ve not used minikube in quite some time and am not sure how well it supports GPUs (or not)).

Maybe @ArangoGutierrez has some insights.

**Comment by NayamAmarshe** [comment]
> It sound like an issue running under minikube then (I’ve not used minikube in quite some time and am not sure how well it supports GPUs (or not)).
> 
> Maybe @ArangoGutierrez has some insights.

Are there any minikube alternatives that you recommend? I'll try those.

**Comment by NayamAmarshe** [comment]
@klueska I was able to get the pod working with the GPU with minikube!
Here's what I did:
```
kubectl delete all --all
minikube delete
minikube start

minikube addons enable nvidia-device-plugin 
minikube addons enable nvidia-gpu-device-plugin
```

I did not setup the **k8s-device-plugin** as mentioned in the `README.md`.

Next, I made the following chanes to my `containers` field in the deployment yaml:
```
      containers:
      - name:  ----
        image:  ----
        resources:
          limits:
            cpu: 1000m
            memory: 1500Mi
            nvidia.com/gpu: "1"
        env:
          - name: NVIDIA_VISIBLE_DEVICES
            value: all
          - name: NVIDIA_DRIVER_CAPABILITIES
            value: all
```

and finally:

```
$ kubectl get pods -A

NAMESPACE     NAME                                   READY   STATUS                     RESTARTS        AGE
default       mylocal-deployment-7879d234rc-q7oca    0/1     UnexpectedAdmissionError   0               39m
kube-system   coredns-5dd5756b68-ck9fz               0/1     Running                    2 (4m49s ago)   95m
kube-system   etcd-minikube                          0/1     Running                    2 (4m54s ago)   95m
kube-system   kube-apiserver-minikube                0/1     Running                    2 (27s ago)     95m
kube-system   kube-controller-manager-minikube       0/1     Running                    2 (4m54s ago)   95m
kube-system   kube-proxy-ntrfx                       1/1     Running                    2 (4m54s ago)   95m
kube-system   kube-scheduler-minikube                0/1     Running                    2 (4m54s ago)   95m
kube-system   nvidia-device-plugin-daemonset-5zcrh   1/1     Running                    1 (4m54s ago)   94m
kube-system   nvidia-gpu-device-plugin-s6jzf         1/1     Running                    2 (4m54s ago)   94m
kube-system   storage-provisioner                    1/1     Running                    3 (4m54s ago)   95m
```

**Comment by yeeeee7** [comment]
I'm using Minikube to deploy Kubernetes and I've tried to install the plugin using the instructions from the README, but it's still not working. Do you have any specific troubleshooting suggestions?

**Comment by NayamAmarshe** [comment]
> I'm using Minikube to deploy Kubernetes and I've tried to install the plugin using the instructions from the README, but it's still not working. Do you have any specific troubleshooting suggestions? @klueska @NayamAmarshe @elezar

Did you make sure that docker on its own is detecting GPU first?

**Comment by yeeeee7** [comment]
> detecting

**Comment by RLutsch** [comment]
similar problem here. 

- running k3s, ubuntu 22.04, have 1050ti installed with drivers configured
- can't seem to add a GPU 
- I installed toolkit 

```
version = 2

[plugins."io.containerd.internal.v1.opt"]
  path = "/var/lib/rancher/k3s/agent/containerd"
[plugins."io.containerd.grpc.v1.cri"]
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
  enable_selinux = false
  enable_unprivileged_ports = true
  enable_unprivileged_icmp = true
  sandbox_image = "rancher/mirrored-pause:3.6"

[plugins."io.containerd.grpc.v1.cri".containerd]
  snapshotter = "overlayfs"
  disable_snapshot_annotations = true
  


[plugins."io.containerd.grpc.v1.cri".cni]
  bin_dir = "/var/lib/rancher/k3s/data/13f9723ffde84ba41d08658d407a523bcf32698f179c9ab30cc0534e1e5d2c1a/bin"
  conf_dir = "/var/lib/rancher/k3s/agent/etc/cni/net.d"


[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
  SystemdCgroup = true

[plugins."io.containerd.grpc.v1.cri".registry]
  config_path = "/var/lib/rancher/k3s/agent/etc/containerd/certs.d"






[plugins."io.containerd.grpc.v1.cri".containerd.runtimes."nvidia"]
  runtime_type = "io.containerd.runc.v2"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes."nvidia".options]
  BinaryName = "/usr/bin/nvidia-container-runtime"
  SystemdCgroup = true



[plugins."io.containerd.grpc.v1.cri".containerd.runtimes."custom"]
  runtime_type = "io.containerd.runc.v2"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes."custom".options]
  BinaryName = "/usr/bin/custom-container-runtime"
  ```
  and the logs I'm getting is 
  ``` 
  I0226 09:43:46.980538       1 main.go:256] Retreiving plugins.
W0226 09:43:46.980825       1 factory.go:31] No valid resources detected, creating a null CDI handler
I0226 09:43:46.980888       1 factory.go:107] Detected non-NVML platform: could not load NVML library: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
I0226 09:43:46.980923       1 factory.go:107] Detected non-Tegra platform: /sys/devices/soc0/family file not found
E0226 09:43:46.980931       1 factory.go:115] Incompatible platform detected
E0226 09:43:46.980937       1 factory.go:116] If this is a GPU node, did you configure the NVIDIA Container Toolkit?
E0226 09:43:46.980943       1 factory.go:117] You can check the prerequisites at: https://github.com/NVIDIA/k8s-device-plugin#prerequisites
E0226 09:43:46.980946       1 factory.go:118] You can learn how to set the runtime at: https://github.com/NVIDIA/k8s-device-plugin#quick-start
E0226 09:43:46.980949       1 factory.go:119] If this is not a GPU node, you should set up a toleration or nodeSelector to only deploy this plugin on GPU nodes
I0226 09:43:46.980957       1 main.go:287] No devices found. Waiting indefinitely.
```
the library is installed here 
``` 
ls /usr/lib/x86_64-linux-gnu/libnvidia-ml.so*

```

**Comment by elezar** [comment]
Did you define a RuntimeClass and use this RuntimeClassName when deploying the Device Plugin?

**Comment by mhs5218** [comment]
> similar problem here.
> 
> * running k3s, ubuntu 22.04, have 1050ti installed with drivers configured
> * can't seem to add a GPU
> * I installed toolkit
> 
> ```
> version = 2
> 
> [plugins."io.containerd.internal.v1.opt"]
>   path = "/var/lib/rancher/k3s/agent/containerd"
> [plugins."io.containerd.grpc.v1.cri"]
>   stream_server_address = "127.0.0.1"
>   stream_server_port = "10010"
>   enable_selinux = false
>   enable_unprivileged_ports = true
>   enable_unprivileged_icmp = true
>   sandbox_image = "rancher/mirrored-pause:3.6"
> 
> [plugins."io.containerd.grpc.v1.cri".containerd]
>   snapshotter = "overlayfs"
>   disable_snapshot_annotations = true
>   
> 
> 
> [plugins."io.containerd.grpc.v1.cri".cni]
>   bin_dir = "/var/lib/rancher/k3s/data/13f9723ffde84ba41d08658d407a523bcf32698f179c9ab30cc0534e1e5d2c1a/bin"
>   conf_dir = "/var/lib/rancher/k3s/agent/etc/cni/net.d"
> 
> 
> [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
>   runtime_type = "io.containerd.runc.v2"
> 
> [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
>   SystemdCgroup = true
> 
> [plugins."io.containerd.grpc.v1.cri".registry]
>   config_path = "/var/lib/rancher/k3s/agent/etc/containerd/certs.d"
> 
> 
> 
> 
> 
> 
> [plugins."io.containerd.grpc.v1.cri".containerd.runtimes."nvidia"]
>   runtime_type = "io.containerd.runc.v2"
> [plugins."io.containerd.grpc.v1.cri".containerd.runtimes."nvidia".options]
>   BinaryName = "/usr/bin/nvidia-container-runtime"
>   SystemdCgroup = true
> 
> 
> 
> [plugins."io.containerd.grpc.v1.cri".containerd.runtimes."custom"]
>   runtime_type = "io.containerd.runc.v2"
> [plugins."io.containerd.grpc.v1.cri".containerd.runtimes."custom".options]
>   BinaryName = "/usr/bin/custom-container-runtime"
> ```
> 
> and the logs I'm getting is
> 
> ```
> I0226 09:43:46.980538       1 main.go:256] Retreiving plugins.
> W0226 09:43:46.980825       1 factory.go:31] No valid resources detected, creating a null CDI handler
> I0226 09:43:46.980888       1 factory.go:107] Detected non-NVML platform: could not load NVML library: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
> I0226 09:43:46.980923       1 factory.go:107] Detected non-Tegra platform: /sys/devices/soc0/family file not found
> E0226 09:43:46.980931       1 factory.go:115] Incompatible platform detected
> E0226 09:43:46.980937       1 factory.go:116] If this is a GPU node, did you configure the NVIDIA Container Toolkit?
> E0226 09:43:46.980943       1 factory.go:117] You can check the prerequisites at: https://github.com/NVIDIA/k8s-device-plugin#prerequisites
> E0226 09:43:46.980946       1 factory.go:118] You can learn how to set the runtime at: https://github.com/NVIDIA/k8s-device-plugin#quick-start
> E0226 09:43:46.980949       1 factory.go:119] If this is not a GPU node, you should set up a toleration or nodeSelector to only deploy this plugin on GPU nodes
> I0226 09:43:46.980957       1 main.go:287] No devices found. Waiting indefinitely.
> ```
> 
> the library is installed here
> 
> ```
> ls /usr/lib/x86_64-linux-gnu/libnvidia-ml.so*
> ```

I am experiencing the same issue, were you ever able to resolve this?

**Comment by deepio** [comment]
> I am experiencing the same issue, were you ever able to resolve this?

My guy, just do this: https://web.archive.org/web/20240602171951/https://medium.com/sparque-labs/serving-ai-models-on-the-edge-using-nvidia-gpu-with-k3s-on-aws-part-4-dd48f8699116

Never mind the AWS stuff, k3s + PIs it works fine.

**Comment by mhs5218** [comment]
> > I am experiencing the same issue, were you ever able to resolve this?
> 
> My guy, just do this: https://web.archive.org/web/20240602171951/https://medium.com/sparque-labs/serving-ai-models-on-the-edge-using-nvidia-gpu-with-k3s-on-aws-part-4-dd48f8699116
> 
> Never mind the AWS stuff, k3s + PIs it works fine.

Adding the Nvidia GPU Operator resolved the issue for me.

**Comment by import-max** [comment]
I resolved the same problem with this command.
I am using k3s + h200.

`nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml`
