### ISSUE TITLE
Couldn't build k8s-device-plugin (v1.10) locally

### ISSUE THREAD

**Issue by kohheinomura** [NVIDIA/k8s-device-plugin#48]
`go build` failed because of lack of nvml sources in recent github.com/NVIDIA/nvidia-docker.  I found nvml src files only exist in version 1.0.x of nvidia-docker.

**Comment by flx42** [comment]
Not sure what you've done wrong, but we've checked in the right version of `nvidia-docker` (vendoring) here:
https://github.com/NVIDIA/k8s-device-plugin/tree/v1.10/vendor/github.com/NVIDIA/nvidia-docker
