### ISSUE TITLE
device plugin runs on ALL nodes

### ISSUE THREAD

**Issue by miramar-labs** [NVIDIA/k8s-device-plugin#50]
I have 9 worker nodes in my cluster but only ONE of them has a GPU. However, the device plugin seems to be running on ALL nodes. On the nodes without a GPU you can see the device plugin failing to find NVML .. (succeeds on the node with a GPU) ... so it seems to me that this plugin should only be running on the node that has a GPU.

Q: How can make the device plugin only run on my GPU node?  Labels? Taints? Something else?

**Comment by pineking** [comment]
what's the version of device plugin you used  https://github.com/NVIDIA/k8s-device-plugin/issues/9  should fix this, so it can work on non-GPU node.

**Comment by miramar-labs** [comment]
v1.10
so my question is ... is there a label or taint that I can apply to my non-GPU nodes so that the plugin does not attempt to run on them...?

**Comment by miramar-labs** [comment]
implemented myself as suggested
