### ISSUE TITLE
pods cannot share a GPU?

### ISSUE THREAD

**Issue by miramar-labs** [NVIDIA/k8s-device-plugin#51]
I'm using JupyterLAB on Kubernetes and have a cluster of 8 CPU worker nodes and one CPU/GPU worker node. I have the device plugin set up etc... and when I log into JupyterLAB, a user pod is created and the device plugin/scheduler run it on my GPU node ... all is great! .. until .. a second user logs in .. the second user pod fails to start as the GPU has already been allocated by the first user....

Q: is it correct that pods can't share a GPU device? If so why not? seems like there is a valid use case here of multiple users being able to do training tasks on a shared GPU at different times at least?

**Comment by flx42** [comment]
Yes, it's one GPU device per **container**. You can't even share a GPU across the containers of a single pod.

It's a limitation of the device plugin API of Kubernetes, not a limitation of our own device plugin.
You can see the discussion here:
https://github.com/kubernetes/kubernetes/issues/52757

**Comment by RenaudWasTaken** [comment]
Closing as this can't be addressed by our device plugin right now.
