### ISSUE TITLE
Cannot restart docker after configuring /etc/docker/daemon.json

### ISSUE THREAD

**Issue by yeya24** [NVIDIA/k8s-device-plugin#53]
Hi everyone.
I got some trouble today installing this plugin.
Here is my environment
AWS Ubuntu Server 16.04
docker 18.03.1-ce
NVIDIA Docker: 2.0.3
CUDA Version 9.1.85

I have already installed nvidia-docker 2 . Then I used the following command to test the nvidia-docker2 and it is successful.
docker run --runtime=nvidia -it -p 8888:8888 tensorflow/tensorflow:latest-gpu

Then I followed the guide to install this plugin.I tried to configure the /etc/docker/daemon.json and
run the following commands:
sudo systemctl daemon-reload && sudo systemctl restart docker

And my configuration in daemon.json is here
{ "default-runtime": "nvidia", "runtimes": { "nvidia": { "path": "/usr/bin/nvidia-container-runtime", "runtimeArgs": [] } } }

But this step was wrong and I got the following output
job for docker.service failed because the control process exited with error code

Who can help me?
Thank you!

**Comment by yeya24** [comment]
Hi @RenaudWasTaken 
Here is the output of    `sudo journalctl -r -u docker`

May 30 01:32:02 ip-172-31-3-138 systemd[1]: Failed to start Docker Application Container Engine.
May 30 01:32:02 ip-172-31-3-138 systemd[1]: docker.service: Start request repeated too quickly.
May 30 01:32:02 ip-172-31-3-138 systemd[1]: Stopped Docker Application Container Engine.
May 30 01:32:02 ip-172-31-3-138 systemd[1]: docker.service: Service hold-off time over, scheduling restart.
May 30 01:32:02 ip-172-31-3-138 systemd[1]: docker.service: Failed with result 'exit-code'.
May 30 01:32:02 ip-172-31-3-138 systemd[1]: docker.service: Unit entered failed state.
May 30 01:32:02 ip-172-31-3-138 systemd[1]: Failed to start Docker Application Container Engine.
May 30 01:32:02 ip-172-31-3-138 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
May 30 01:32:02 ip-172-31-3-138 dockerd[16624]: unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file: run
May 30 01:32:02 ip-172-31-3-138 systemd[1]: Starting Docker Application Container Engine...
May 30 01:32:02 ip-172-31-3-138 systemd[1]: Stopped Docker Application Container Engine.
May 30 01:32:02 ip-172-31-3-138 systemd[1]: docker.service: Service hold-off time over, scheduling restart.
May 30 01:32:01 ip-172-31-3-138 systemd[1]: docker.service: Failed with result 'exit-code'.
May 30 01:32:01 ip-172-31-3-138 systemd[1]: docker.service: Unit entered failed state.
May 30 01:32:01 ip-172-31-3-138 systemd[1]: Failed to start Docker Application Container Engine.
May 30 01:32:01 ip-172-31-3-138 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
May 30 01:32:01 ip-172-31-3-138 dockerd[16584]: unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file: run
May 30 01:32:01 ip-172-31-3-138 systemd[1]: Starting Docker Application Container Engine...
May 30 01:32:01 ip-172-31-3-138 systemd[1]: Stopped Docker Application Container Engine.
May 30 01:32:01 ip-172-31-3-138 systemd[1]: docker.service: Service hold-off time over, scheduling restart.
May 30 01:32:01 ip-172-31-3-138 systemd[1]: docker.service: Failed with result 'exit-code'.
May 30 01:32:01 ip-172-31-3-138 systemd[1]: docker.service: Unit entered failed state.
May 30 01:32:01 ip-172-31-3-138 systemd[1]: Failed to start Docker Application Container Engine.
May 30 01:32:01 ip-172-31-3-138 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
May 30 01:32:01 ip-172-31-3-138 dockerd[16574]: unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file: run
May 30 01:32:01 ip-172-31-3-138 systemd[1]: Starting Docker Application Container Engine...
May 30 01:32:01 ip-172-31-3-138 systemd[1]: Stopped Docker Application Container Engine.


It's really confused that I dont't know why the log said unable to configure the docker daemon

**Comment by yeya24** [comment]
@RenaudWasTaken  Thanks a lot!
I found the same question at [](https://github.com/docker/for-linux/issues/165) and I fixed it.
Now I will close this issue

**Comment by priyakansal** [comment]
@yeya24
I am facing exactly the same issue, I am not new to docker, and not able to follow the steps suggested in the URL shared, because I do not have any EXEC kind of file or document ... can you please suggest me how to do it from starting

**Comment by RenaudWasTaken** [comment]
https://github.com/NVIDIA/nvidia-container-runtime/blob/master/README.md#docker-engine-setup
