### ISSUE TITLE
ppc64le docker image

### ISSUE THREAD

**Issue by paulbsch** [NVIDIA/k8s-device-plugin#54]
Please push a docker image built for ppc64le and use manifest-tool (https://github.com/estesp/manifest-tool ).  Then, when the provided k8s DaemonSet pulls the docker image, it will "just work" on all platforms.

**Comment by paulbsch** [comment]
Ah.  The manifest command is now built into docker proper as an experimental feature.  I did not realize:
https://docs.docker.com/edge/engine/reference/commandline/manifest/

**Comment by RenaudWasTaken** [comment]
@flx42 ^

**Comment by flx42** [comment]
Yes this has been planned for a while... cc @clnperez for visibility

**Comment by clnperez** [comment]
@paulbsch is this what you're looking for? https://github.com/NVIDIA/k8s-device-plugin/pull/44
Then making it into a manifest list? :1st_place_medal:

**Comment by flx42** [comment]
The DockerHub repository is now multi-arch:
https://hub.docker.com/r/nvidia/k8s-device-plugin/
Please test!
