### ISSUE TITLE
Using kubernetes to run tensorflow training much slower than `docker run`

### ISSUE THREAD

**Issue by cheyang** [NVIDIA/k8s-device-plugin#56]
I've installed nvidia-docker2(nvidia-container-runtime) + kubernetes 1.9.7, and run tensorflow training in 8 1080ti nvidia-gpu . When I'm using kubectl to deploy pod with nvidia.com/gpu=8. The logs shows

```
Iteration 200 (0.833003 iter/s)
```
But when I run with the command: `docker run --runtime=nvidia caffe-mpi:v0.2.22.test1`, the performance is much better.
```
Iteration 200 (1.655003 iter/sr)
```

But when I add "cgroup-parent" which of the pod I created first, I find the performance is as the same as the pod.

```
docker run --runtime=nvidia --cgroup-parent=kubepods-besteffort-podf4e9758b_6fda_11e8_93ce_00163e008c08.slice caffe-mpi:v0.2.22.test1
Iteration 200 (0.851113 iter/s)
```

I suspect it's related to the cgroup setting of the kubernetes. Do you have any suggestions? Thanks in advanced.

**Comment by pineking** [comment]
@cheyang any update? have you solved this issue?

**Comment by flx42** [comment]
I didn't have time to look at it, but please share your pod spec as requested by @RenaudWasTaken.

**Comment by ray1888** [comment]
is any update on this ? i focusing on it @cheyang

**Comment by RenaudWasTaken** [comment]
Closing as no further answers were provided.
We did not see any slowdown on our side.
