### ISSUE TITLE
Minikube doesn't recognize GPU

### ISSUE THREAD

**Issue by aclowkey** [NVIDIA/k8s-device-plugin#57]
I installed NVIDIA docker and now trying to test it on my local minikube without success.
I followed few threads around the same topics, also without luck.

```bash
sudo minikube start --vm-driver=none --feature-gates=Accelerators=true 
kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v1.10/nvidia-device-plugin.yml 
kubectl get nodes -o=custom-columns=NAME:.metadata.name,GPUs:.status.capacity.'nvidia\.com/gpu' 
```
Getting:

> NAME       GPUs
> minikube   \<none\>

**Comment by pineking** [comment]
--feature-gates=DevicePlugins=true

**Comment by aclowkey** [comment]
I tried
`sudo minikube start --feature-gates=DevicePlugins=true --vm-driver none --feature-gates=Accelerators=true`
got the same result

**Comment by aclowkey** [comment]
@pineking It actually didn't work. I tried added default-runtime=nvidia to the docker service which solved that. Is there a way to specify it for the minikube?

**Comment by pineking** [comment]
I'm not sure whether minikube can do this (set the docker default runtime).
BTW: `--feature-gates=Accelerators=true` is not necessary for nvidia device plugin.

**Comment by aclowkey** [comment]
Ohh ok. Thank you!
