### ISSUE TITLE
Using CUDA MPS to enable GPU sharing in K8S， error：error checking MPS daemon health

### ISSUE THREAD

**Issue by zhangQiWorr** [NVIDIA/k8s-device-plugin#634]
![image](https://github.com/NVIDIA/k8s-device-plugin/assets/151835175/37d4e2c8-0328-4000-84c8-29b22e9a1581)

![image](https://github.com/NVIDIA/k8s-device-plugin/assets/151835175/08cb8f1d-d1cc-49e5-96c9-621f7cbda4f4)

![image](https://github.com/NVIDIA/k8s-device-plugin/assets/151835175/a9d28746-7171-462b-a589-7545e2f5f25e)

**Comment by zhangQiWorr** [comment]
Should I start MPS daemon（nvidia-cuda-mps-control） in the k8s node？

**Comment by elezar** [comment]
@zhangQiWorr are you deploying the device plugin using helm? The use of MPS in the device plugin requires both GFD and an additional component to manage the lifecycle of the MPS control daemon. Here the use of helm is recommended since this deploys the relevant daemonsets.
