### ISSUE TITLE
1.11 not working with CUDA 8.0

### ISSUE THREAD

**Issue by Eloahman** [NVIDIA/k8s-device-plugin#66]
Hey, I met the problem following
> nvidia-device-plugin: symbol lookup error: nvidia-device-plugin: undefined symbol: nvmlDeviceGetPciInfo_v3

when I run with following command

> docker run --security-opt=no-new-privileges --cap-drop=ALL --network=none -it -v /var/lib/kubelet/device-plugins:/var/lib/kubelet/device-plugins nvidia/k8s-device-plugin:1.11

And it works well with k8s-device-plugin:1.10

I think I met the same problem with #33 and k8s-device-plugin:1.11 does not works with CUDA 8.0

**Comment by flx42** [comment]
Yes, we now require a more recent CUDA.
You can still use the older image `k8s-device-plugin:1.10`, the API didn't change in-between.

**Comment by Eloahman** [comment]
Thanks for the confirmation.
May be it will be helpful to point it out in doc.
