### ISSUE TITLE
How to get  unscheduled gpus?

### ISSUE THREAD

**Issue by 694982827** [NVIDIA/k8s-device-plugin#67]
In k8s cluster with k8s-device-plugin，if I want to know how many gpus are used and not used, how to get these infomations?

**Comment by RenaudWasTaken** [comment]
Hello!

If you want to know how many GPUs are used in the cluster: List all pods running and add the `nvidia.com/gpu`.
If you want to know many GPUs are used on a node: List all pods running on that node and add the `nvidia.com/gpu`.

You can use the K8s client lib
