### ISSUE TITLE
nvidia-device-plugin.hasConfigMap returns a string

### ISSUE THREAD

**Issue by fraenkel** [NVIDIA/k8s-device-plugin#689]
### 2. Issue or feature description
The helm chart helper `nvidia-device-plugin.hasConfigMap` attempts to return true/false but an `include` will always return a string.

Some places handled this properly by comparing to `true` while other places used the string as a guard.

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) 
https://github.com/NVIDIA/k8s-device-plugin/blob/main/deployments/helm/nvidia-device-plugin/templates/role.yml#L1
https://github.com/NVIDIA/k8s-device-plugin/blob/main/deployments/helm/nvidia-device-plugin/templates/service-account.yml#L1
https://github.com/NVIDIA/k8s-device-plugin/blob/main/deployments/helm/nvidia-device-plugin/templates/role-binding.yml#L1

**Comment by mrkiani98** [comment]
Hi there,

Same issue here that we can see it's creating these extra resources by mistake which are not being used anywhere.

Any update on this issue?

**Comment by mrkiani98** [comment]
But I can see that the created serviceAccount is not being used in any of the deployments or daemonsets.

**Comment by fraenkel** [comment]
I see it used in all the daemonsets.

**Comment by mrkiani98** [comment]
For my side, I'm currently using the chart version `0.14.5` and then after upgrading to chart version `0.15.0` I can only see the helm diff as I have only two Daemonset which are `nvidia-device-plugin-mps-control-daemon` and `nvidia-device-plugin` which I can see there is no `serviceAccount` definition on these Daemonsets at all. 

Note: I'm using the actual default values of the chart and touching nothing.

**Comment by mrkiani98** [comment]
May I also ask you to check if the issue mentioned here is also be addressed in the future or not? @elezar

**Comment by elezar** [comment]
@mrkiani98 no, we have not yet had a look at it. Could you provide the helm diff for your specific configuration?

**Comment by fraenkel** [comment]
@elezar I cannot verify the changes given I just switch employers.
