### ISSUE TITLE
Why should we get more than one service while checking server is ready?

### ISSUE THREAD

**Issue by ScorpioCPH** [NVIDIA/k8s-device-plugin#7]
@flx42 Hi, in these [codes](https://github.com/NVIDIA/k8s-device-plugin/blob/master/server.go#L62-69), i think `only one` service will be got. WDYT？ 

```go
services := m.server.GetServiceInfo()
if len(services) > 1 {
	break
}
```

**Comment by flx42** [comment]
Yeah, this code was taken from the device plugin stub code:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/deviceplugin/device_plugin_stub.go#L73-L75

@RenaudWasTaken has a PR for fixing this (among other things):
https://github.com/kubernetes/kubernetes/pull/52612

**Comment by flx42** [comment]
fixed, thanks for bringing that to my attention @ScorpioCPH
