### ISSUE TITLE
Unable to schedule Pods: Insufficient nvidia.com/gpu

### ISSUE THREAD

**Issue by ruettimac** [NVIDIA/k8s-device-plugin#71]
I have configured a k8s cluster by following the various recipes. I am struggling with scheduling any Pod using the GPU with the message insufficient nvidia.com/gpu. I read through all the reports, but I did not find the issue in my case:
1. I changed the runtime of docker to nvidia and can execute the container with the nvidia-smi binary. The output shows the GPU.

`
docker run --rm nvidia/cuda nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.44                 Driver Version: 396.44                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro M4000        Off  | 00000000:08:00.0 Off |                  N/A |
| 46%   34C    P8    11W / 120W |      0MiB /  8126MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
`

2. I disabled the health check in the plugin, but the same issue with insufficient nvidia.com/gpu appears.

3. I checked the log of the device plugin and that looks good:

`
kubectl logs nvidia-device-plugin-9ks7m --namespace kube-system
2018/08/30 15:17:57 Loading NVML
2018/08/30 15:17:57 Fetching devices.
2018/08/30 15:17:57 Starting FS watcher.
2018/08/30 15:17:57 Starting OS watcher.
2018/08/30 15:17:57 Starting to serve on /var/lib/kubelet/device-plugins/nvidia.sock
2018/08/30 15:17:57 Registered device plugin with Kubelet
`

4. I checked the node and it seems to be OK:

`
kubectl describe node xy.net
Name:               xy.net
Roles:              node
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/hostname=xy.net
                    node-role.kubernetes.io/node=node
                    nvidia.com/gpu=true
Annotations:        node.alpha.kubernetes.io/ttl=0
                    volumes.kubernetes.io/controller-managed-attach-detach=true
CreationTimestamp:  Tue, 28 Aug 2018 08:46:52 +0200
Taints:             nvidia.com/gpu=true:NoSchedule
Unschedulable:      false
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  OutOfDisk        False   Thu, 30 Aug 2018 17:47:12 +0200   Tue, 28 Aug 2018 08:46:52 +0200   KubeletHasSufficientDisk     kubelet has sufficient disk space available
  MemoryPressure   False   Thu, 30 Aug 2018 17:47:12 +0200   Tue, 28 Aug 2018 08:46:52 +0200   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Thu, 30 Aug 2018 17:47:12 +0200   Thu, 30 Aug 2018 15:57:31 +0200   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Thu, 30 Aug 2018 17:47:12 +0200   Tue, 28 Aug 2018 08:46:52 +0200   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Thu, 30 Aug 2018 17:47:12 +0200   Thu, 30 Aug 2018 13:41:16 +0200   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  10.222.15.88
  Hostname:    sp-h335-dn05.corproot.net
Capacity:
 cpu:                56
 ephemeral-storage:  3997376Ki
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             263842152Ki
 nvidia.com/gpu:     1
 pods:               110
Allocatable:
 cpu:                56
 ephemeral-storage:  3683981716
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             263739752Ki
 nvidia.com/gpu:     1
 pods:               110
System Info:
 Machine ID:                 44c5cbda83b7464aa129ba6cd56935fe
 System UUID:                30393137-3136-5A43-4A37-323230325030
 Boot ID:                    09b64e32-97d8-4556-9e97-4beec706b704
 Kernel Version:             3.10.0-862.11.6.el7.x86_64
 OS Image:                   Red Hat Enterprise Linux Server 7.5 (Maipo)
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://1.13.1
 Kubelet Version:            v1.10.5
 Kube-Proxy Version:         v1.10.5
ExternalID:                  xy.net
Non-terminated Pods:         (2 in total)
  Namespace                  Name                          CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ---------                  ----                          ------------  ----------  ---------------  -------------
  kube-system                calico-node-tmbbn             600m (1%)     700m (1%)   1124Mi (0%)      1224Mi (0%)
  kube-system                nvidia-device-plugin-9ks7m    500m (0%)     1 (1%)      200Mi (0%)       1Gi (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ------------  ----------  ---------------  -------------
  1100m (1%)    1700m (3%)  1324Mi (0%)      2248Mi (0%)
Events:         <none>
`

5. I also applied the toleration and node affinity to the Pod - just in case the exposed resource is not enough to be scheduled on the gpu enabled node. Because the node has a taint applied and is labeled.

**Comment by flx42** [comment]
What's your pod spec?

**Comment by ruettimac** [comment]
`
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
  namespace: kube-system
spec:
  imagePullSecrets:
  - name: swisscom-registry-secret
  tolerations:
  - key: nvidia.com/gpu
    operator: Equal
    value: "true"
    effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu
            operator: In
            values:
            - "true"
  containers:
  - name: cuda-container
    image: remote-docker.artifactory.swisscom.com/nvidia/cuda:9.0-devel
    resources:
      limits:
        nvidia.com/gpu: 1 # requesting 1 GPUs
  - name: digits-container
    image: nvidia/digits:6.0
    resources:
      limits:
        nvidia.com/gpu: 1 # requesting 1 GPUs
`

**Comment by flx42** [comment]
Your pod is effectively requesting 2 GPUs. GPUs are assigned per-container, and are not shared.

**Comment by ruettimac** [comment]
Thanks Felix for your explanation. That helped to shorten my effort to resolve this issue. Do you have a pointer to the documentation where GPU-Sharing is described detailed?

**Comment by RenaudWasTaken** [comment]
GPU sharing is not available yet in Kubernetes

**Comment by flx42** [comment]
@ruettimac this is the ongoing discussion: https://github.com/kubernetes/kubernetes/issues/52757
