### ISSUE TITLE
The plugin has already support nvlink?

### ISSUE THREAD

**Issue by baoervsdier** [NVIDIA/k8s-device-plugin#711]
I found this pr https://github.com/NVIDIA/k8s-device-plugin/issues/546,it looks like having supported nvlink now,is there any one success?

**Comment by mangohoney** [comment]
I also encountered the same problem. After downloading and compiling and testing the gpuallocator v0.4.2 ,  the NVLINK topo scheduling is effective. However, the k8s-device-plugin v0.15.0 container is still assigning GPUs randomly.
