### ISSUE TITLE
List of possible values for `nvidia.com/gpu.product`?

### ISSUE THREAD

**Issue by romilbhardwaj** [NVIDIA/k8s-device-plugin#739]
Thank you for this useful utility. Is there some place I can find the list of possible values for the `nvidia.com/gpu.product` label?

For example, I'm looking for a list like `["T4", "V100", ''A100-SXM4-80GB", "A100-SXM4-40GB" ....]`, which contains all possible values.

Alternatively, it would be useful to know how these label values are generated (e.g., how are they parsed from `lspci`/`nvidia-smi`?)

**Comment by Jonathan-Eid** [comment]
@romilbhardwaj Did you ever get that list?
