### ISSUE TITLE
Can a single GPU be shared by mulitple container at the same time?

### ISSUE THREAD

**Issue by yukuo78** [NVIDIA/k8s-device-plugin#76]
Hi,

We only have one single NVDIA GPU installed on one node of a multi-nodes cluster, can this GPU be shared among multiple containers at the same time? Thanks.

Best Regards,
Kevin

**Comment by warmchang** [comment]
ref: https://github.com/kubernetes/kubernetes/issues/52757

**Comment by RenaudWasTaken** [comment]
Hello!

Sorry for the delay, this is currently not explicitly possible using the K8S API.
However, there are some work around: https://github.com/kubernetes/kubernetes/issues/52757#issuecomment-402772200

**Comment by RenaudWasTaken** [comment]
Feel free to reopen if you have other questions :)

**Comment by yukuo78** [comment]
@RenaudWasTaken thank you :)
