### ISSUE TITLE
I want to deploy three models, one large language model occupying one GPU, one embedding model and one re-ranking model sharing one GPU, How can I do it？

### ISSUE THREAD

**Issue by Flynn-Zh** [NVIDIA/k8s-device-plugin#769]
there are two gpu device on the kubenetes node,
the timeSlicing.replicas is two,
the nvidia.com/gpu of large langurage model is two,
the nvidia.com/gpu of other models are one,
but the pod of large langurage model has two gpu device

**Comment by klueska** [comment]
You can't do this with the standard device plugin. You will need to wait until DRA is available:
https://docs.google.com/document/d/1BNWqgx_SmZDi-va_V31v3DnuVwYnF2EmN7D-O_fB6Oo/edit#heading=h.bxuci8gx6hna

**Comment by Flynn-Zh** [comment]
the DRA cannot be used in production environments.
Can we modify the code of GPU allocation strategy to implement it?
Can anyone give me some help?

**Comment by Flynn-Zh** [comment]
> the DRA cannot be used in production environments. Can we modify the code of GPU allocation strategy to implement it? Can anyone give me some help?

example: not used timeslicing，but the nvidia.com.gpu of limits can set 0.1，How to modify code？
