### ISSUE TITLE
The GetPreferredAllocation api takes too long to return 

### ISSUE THREAD

**Issue by horizen** [NVIDIA/k8s-device-plugin#774]
### 1. Quick Debug Information
* OS/Version: ubuntu20.04
* Kernel Version: 5.4.119
* Container Runtime Type/Version: Docker
* K8s Flavor/Version: K8s

### 2. Issue or feature description
GetPreferredAllocation is too slow, it took nearly 30 seconds.

### 3. Information to attach
 - k8s-device-plugin version
   **v0.13.0**
 - nvidia-smi -a output
    [nvidia-smi.log](https://github.com/user-attachments/files/15884050/nvidia-smi.log)
 
 - kubelet logs 
    [kubelet.log](https://github.com/user-attachments/files/15884214/kubelet.log)

From the following log snippet, it can be seen that GetPreferredAllocation took nearly 30 seconds.
13:17:33.553431  160160 manager.go:1100] "Issuing a GetPreferredAllocation call for container" containerName="main" podUID="ad55cb1c-b7b1-411d-b3aa-9f30ffc8044e"
...
13:18:00.011131  160160 manager.go:963] "Making allocation request for device plugin" devices=[GPU-931ca6fe-e207-950e-7ce6-fec891678386 GPU-82412263-d3c9-fc58-ea6d-9ebfbaaef8e2 GPU-83c1a537-afc0-8b35-56d8-8930dd0d2c68 GPU-a4d33f09-1360-9455-3f9d-1ee29a9b982f GPU-bab8a983-52b0-0008-c924-74a197a9c663 GPU-ea5f9db4-c827-8d57-d9cb-3ccc48d409f7 GPU-940360f2-35b0-bd40-55ec-9ba3b06f980c] resourceName="nvidia.com/gpu"

### 4. Solution

I tried updating to the latest version, and it also took nearly 16 seconds.

I read the code and found that the time consumption is mainly spent on this line of [code](https://github.com/NVIDIA/k8s-device-plugin/blob/6a10d70fa7327e919066d527b46c91929a10c62f/internal/rm/nvml_manager.go#L116C2-L121C3)

I suspect that the NVML API calls might be consuming too much time. Is that correct?

**Comment by klueska** [comment]
It shouldn't take that long. How many GPUs do you have on your machine? And is your host running the nvidia-persistenced daemon?

**Comment by horizen** [comment]
> It shouldn't take that long. How many GPUs do you have on your machine? And is your host running the nvidia-persistenced daemon?

There are 8 A100 GPUs.
Persistence mode is on.
below is nvidia-smi output
<img width="574" alt="image" src="https://github.com/NVIDIA/k8s-device-plugin/assets/4516205/69c339c7-7778-4742-a892-be0c76caed42">

**Comment by horizen** [comment]
I tried add some debug log at nvml api, the result show than nvml.GetNVLink seems take too long 

> 2024/06/18 13:39:36 nvml.GetDeviceCount() cost 0 millseconds
2024/06/18 13:39:36 nvml.NewDevice(0) cost 167 millseconds
2024/06/18 13:39:36 nvml.NewDevice(1) cost 3 millseconds
2024/06/18 13:39:36 nvml.NewDevice(2) cost 2 millseconds
2024/06/18 13:39:36 nvml.NewDevice(3) cost 2 millseconds
2024/06/18 13:39:36 nvml.NewDevice(4) cost 292 millseconds
2024/06/18 13:39:36 nvml.NewDevice(5) cost 3 millseconds
2024/06/18 13:39:36 nvml.NewDevice(6) cost 2 millseconds
2024/06/18 13:39:36 nvml.NewDevice(7) cost 2 millseconds
2024/06/18 13:39:36 nvml.GetP2PLink(GPU-83c1a537-afc0-8b35-56d8-8930dd0d2c68, GPU-6c66af24-e251-39ec-9b8a-9a11beb3511c) cost 0 millseconds
2024/06/18 13:39:37 nvml.GetNVLink(GPU-83c1a537-afc0-8b35-56d8-8930dd0d2c68, GPU-6c66af24-e251-39ec-9b8a-9a11beb3511c) cost 599 millseconds
2024/06/18 13:39:37 nvml.GetP2PLink(GPU-83c1a537-afc0-8b35-56d8-8930dd0d2c68, GPU-a4d33f09-1360-9455-3f9d-1ee29a9b982f) cost 0 millseconds
2024/06/18 13:39:38 nvml.GetNVLink(GPU-83c1a537-afc0-8b35-56d8-8930dd0d2c68, GPU-a4d33f09-1360-9455-3f9d-1ee29a9b982f) cost 595 millseconds
2024/06/18 13:39:38 nvml.GetP2PLink(GPU-83c1a537-afc0-8b35-56d8-8930dd0d2c68, GPU-bab8a983-52b0-0008-c924-74a197a9c663) cost 0 millseconds
2024/06/18 13:39:38 nvml.GetNVLink(GPU-83c1a537-afc0-8b35-56d8-8930dd0d2c68, GPU-bab8a983-52b0-0008-c924-74a197a9c663) cost 298 millseconds
2024/06/18 13:39:38 nvml.GetP2PLink(GPU-83c1a537-afc0-8b35-56d8-8930dd0d2c68, GPU-ea5f9db4-c827-8d57-d9cb-3ccc48d409f7) cost 0 millseconds
2024/06/18 13:39:38 nvml.GetNVLink(GPU-83c1a537-afc0-8b35-56d8-8930dd0d2c68, GPU-ea5f9db4-c827-8d57-d9cb-3ccc48d409f7) cost 106 millseconds
2024/06/18 13:39:38 nvml.GetP2PLink(GPU-83c1a537-afc0-8b35-56d8-8930dd0d2c68, GPU-940360f2-35b0-bd40-55ec-9ba3b06f980c) cost 0 millseconds
2024/06/18 13:39:38 nvml.GetNVLink(GPU-83c1a537-afc0-8b35-56d8-8930dd0d2c68, GPU-940360f2-35b0-bd40-55ec-9ba3b06f980c) cost 198 millseconds
2024/06/18 13:39:38 nvml.GetP2PLink(GPU-83c1a537-afc0-8b35-56d8-8930dd0d2c68, GPU-931ca6fe-e207-950e-7ce6-fec891678386) cost 0 millseconds
2024/06/18 13:39:38 nvml.GetNVLink(GPU-83c1a537-afc0-8b35-56d8-8930dd0d2c68, GPU-931ca6fe-e207-950e-7ce6-fec891678386) cost 106 millseconds
2024/06/18 13:39:38 nvml.GetP2PLink(GPU-83c1a537-afc0-8b35-56d8-8930dd0d2c68, GPU-82412263-d3c9-fc58-ea6d-9ebfbaaef8e2) cost 0 millseconds
2024/06/18 13:39:39 nvml.GetNVLink(GPU-83c1a537-afc0-8b35-56d8-8930dd0d2c68, GPU-82412263-d3c9-fc58-ea6d-9ebfbaaef8e2) cost 291 millseconds
2024/06/18 13:39:39 nvml.GetP2PLink(GPU-6c66af24-e251-39ec-9b8a-9a11beb3511c, GPU-83c1a537-afc0-8b35-56d8-8930dd0d2c68) cost 0 millseconds
2024/06/18 13:39:39 nvml.GetNVLink(GPU-6c66af24-e251-39ec-9b8a-9a11beb3511c, GPU-83c1a537-afc0-8b35-56d8-8930dd0d2c68) cost 107 millseconds
2024/06/18 13:39:39 nvml.GetP2PLink(GPU-6c66af24-e251-39ec-9b8a-9a11beb3511c, GPU-a4d33f09-1360-9455-3f9d-1ee29a9b982f) cost 0 millseconds
2024/06/18 13:39:39 nvml.GetNVLink(GPU-6c66af24-e251-39ec-9b8a-9a11beb3511c, GPU-a4d33f09-1360-9455-3f9d-1ee29a9b982f) cost 196 millseconds
2024/06/18 13:39:39 nvml.GetP2PLink(GPU-6c66af24-e251-39ec-9b8a-9a11beb3511c, GPU-bab8a983-52b0-0008-c924-74a197a9c663) cost 0 millseconds
2024/06/18 13:39:39 nvml.GetNVLink(GPU-6c66af24-e251-39ec-9b8a-9a11beb3511c, GPU-bab8a983-52b0-0008-c924-74a197a9c663) cost 197 millseconds
2024/06/18 13:39:39 nvml.GetP2PLink(GPU-6c66af24-e251-39ec-9b8a-9a11beb3511c, GPU-ea5f9db4-c827-8d57-d9cb-3ccc48d409f7) cost 0 millseconds
2024/06/18 13:39:39 nvml.GetNVLink(GPU-6c66af24-e251-39ec-9b8a-9a11beb3511c, GPU-ea5f9db4-c827-8d57-d9cb-3ccc48d409f7) cost 107 millseconds
2024/06/18 13:39:39 nvml.GetP2PLink(GPU-6c66af24-e251-39ec-9b8a-9a11beb3511c, GPU-940360f2-35b0-bd40-55ec-9ba3b06f980c) cost 0 millseconds
2024/06/18 13:39:39 nvml.GetNVLink(GPU-6c66af24-e251-39ec-9b8a-9a11beb3511c, GPU-940360f2-35b0-bd40-55ec-9ba3b06f980c) cost 196 millseconds
2024/06/18 13:39:39 nvml.GetP2PLink(GPU-6c66af24-e251-39ec-9b8a-9a11beb3511c, GPU-931ca6fe-e207-950e-7ce6-fec891678386) cost 0 millseconds
2024/06/18 13:39:40 nvml.GetNVLink(GPU-6c66af24-e251-39ec-9b8a-9a11beb3511c, GPU-931ca6fe-e207-950e-7ce6-fec891678386) cost 197 millseconds
...

**Comment by horizen** [comment]
I found the reason. 
Previously, the CPU and memory quotas for the k8s-device-plugin were too low(cpu:100m, memory: 512Mi) . I increased the CPU and memory, and now it's normal.

So，why the CPU and memory have such a big impact？

> I tried using strace to trace the API calls and found that most of the time was spent on ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7ffdf3d456b0) = 0.

**Comment by klueska** [comment]
It's a fairly heavy-weight operation, so i can see how not having much CPU time dedicated to it might affect things. Mot users don't set any limit on the plugin, so that is likely why we havevn't encountered this problem before.

**Comment by horizen** [comment]
> It's a fairly heavy-weight operation, so i can see how not having much CPU time dedicated to it might affect things. Mot users don't set any limit on the plugin, so that is likely why we havevn't encountered this problem before.

Got it, thanks for your explanation.
