### ISSUE TITLE
should I install cuda lib when build my tensorflow image?

### ISSUE THREAD

**Issue by Cherishty** [NVIDIA/k8s-device-plugin#79]
### 1. Issue or feature description
I am a new-comer to nvidia-gpu in k8s, and I would like to train my tensorflow model via gpu in docker container.
And I wonder if I need to install cuda lib in my docker image, or device plugin will mount all driver/cuda env into container automatically if I set everthing right?
Seems the official images provided by Nvidia always contain a build-in CLI , is this a must to run tensorflow training?

**Comment by flx42** [comment]
You should not install the NVIDIA driver inside the container. But you **do** need to install the **CUDA toolkit** libraries (e.g. cuDNN, cuBLAS, cuFFT) inside your container image.
