### ISSUE TITLE
Limit the number of gpu that are passed to kubernets

### ISSUE THREAD

**Issue by jomach** [NVIDIA/k8s-device-plugin#81]
---

### 1. Issue or feature description
How can I limit the number of gpus that are recognized from Kubernetes ? 
We have a node that we want to split for testing 4 gpus for mesos and 4 gpus for Kubernetes. On Mesos we can do it, how does it work on kube ?

**Comment by RenaudWasTaken** [comment]
You can set the env variable `NVIDIA_VISIBLE_DEVICES` to `0,1,2,3` in the device plugin spec if you only want it to advertise the first 4 GPUs.

You'll need some more work if you have some nodes with less than 4 GPUs by deploying two device plugins and the clever use of nodeSelectors and labels.

Feel free to reopen if that didn't answer all your questions.

**Comment by tingzhang-ming** [comment]
> You can set the env variable `NVIDIA_VISIBLE_DEVICES` to `0,1,2,3` in the device plugin spec if you only want it to advertise the first 4 GPUs.
> 
> You'll need some more work if you have some nodes with less than 4 GPUs by deploying two device plugins and the clever use of nodeSelectors and labels.
> 
> Feel free to reopen if that didn't answer all your questions.

hi, i have 16 gpus in my node, and i split it into two device-plugins running in this node, device-plugin-01 maps to 0~7 gpus, and device-plugin-02 maps to 8~15 gpus, but these two device-plugins store the pod information releated with gpus in the same file named /var/lib/kubelet/device-plugins/kubelet_internal_checkpoint, so this file will be override by this two device-plugins and I could not get the all 16 gpus assignment information from the  /var/lib/kubelet/device-plugins/kubelet_internal_checkpoint.

Is there any solutions for this problem? for example, could i specify the storage name(such as kubelet_internal_checkpoint-01) in each device-plugin?
