### ISSUE TITLE
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

### ISSUE THREAD

**Issue by p01ne** [NVIDIA/k8s-device-plugin#812]
Hi  I use an AMD GPU. I get this error please help me

**Comment by justinthelaw** [comment]
The NVIDIA K8s device plugin only works on CUDA capable GPUs (aka, NVIDIA GPUs). If you are using an AMD GPU, you need to look for the AMD/ROCm version of device plugin.

**Comment by elezar** [comment]
Please see https://github.com/ROCm/k8s-device-plugin
