### ISSUE TITLE
Can GPU workloads span GPU nodes

### ISSUE THREAD

**Issue by kmmanto** [NVIDIA/k8s-device-plugin#83]
Hi

I've recently setup a kubernetes cluster with 2 DGX station as nodes. Each has 4 GPUs. So basically my cluster has 8 GPUs.

If I request for a workload that needs 4 GPUs, k8s is able to schedule it.
If I request for a workload that needs more than 4 GPUs, k8s is **NOT** able to schedule it.

Am I doing this right? 

---------------

DGX_SWBUILD_VERSION="3.1.6"

NVIDIA Docker: 2.0.3

NVIDIA-SMI 384.125               
Driver Version: 384.125

kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.8", GitCommit:"1ed3ecc3b2dfe63f922a70acd5b4cd839f44acc5", GitTreeState:"clean", BuildDate:"2018-11-29T04:49:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.8", GitCommit:"f997b4f41285b6bb1c85000fdb4ff391247f4edd", GitTreeState:"clean", BuildDate:"2018-10-23T18:48:25Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by guptaNswati** [comment]
No this is not possible, you can request maximum of 4 GPUs per Job.

**Comment by kmmanto** [comment]
Is there a way to achieve this somehow?

Say I have 2 DGX Stations with 4 GPUs each.
I would like to request for a job with 6 GPUs so that the resource in the cluster is used efficiently.

Is this possible?

**Comment by klueska** [comment]
You can not have a single job that requests resources that span multiple machines. This is not a limitation of k8s-device-plugin, but rather a constraint imposed by Kubernetes itself.

**Comment by RenaudWasTaken** [comment]
@kmmanto you can always create two jobs, one which requests four GPUs and another which requests 2.

**Comment by kmmanto** [comment]
@klueska Can NVIDIA/deepops solve this somehow?

@RenaudWasTaken We specifically need at least 8GPUs for our workload.

**Comment by klueska** [comment]
How would you imagine this working exactly?

With Kubernetes, the resources you specify for a pod are always in terms of a single node. If you want a logical "job" to span multiple nodes, you need to separate it into multiple pods and write the software (or leverage higher level programming constructs such as MPI or distributed TensorFlow) that knows how communicate between the pods to provide the multi-node semantics that you want.
