### ISSUE TITLE
Docker image tag v0.9.0-ubuntu20.04

### ISSUE THREAD

**Issue by yuliyan-valchev-ft** [NVIDIA/k8s-device-plugin#833]
### 1. Quick Debug Information
* OS/Version(e.g. RHEL8.6, Ubuntu22.04):
* Kernel Version:
* Container Runtime Type/Containerd
* K8s Flavor/EKS 1.30

### 2. Issue or feature description

Hello, 

We have created a new EKS  1.30 cluster with a gpu instance node group. On the cluster installed from AWS we get an nvidia-device-plugin daemonset  and got notified that it is using an EOL Ububntu 16.04  base image.

Which lead me to look at the images for nvcr.io/nvidia/k8s-device-plugin:v0.9.0  and found that the there might be an error with the tag v0.9.0-ubuntu20.04, being actually on the ubuntu16.04 base

Here is a quick check:

`docker run -it --platform=linux/amd64   --entrypoint bash nvcr.io/nvidia/k8s-device-plugin:v0.9.0-ubuntu20.04
`

```
root@76e879e636b3:/# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

Maybe the tag needs to be deleted as it is all the same image

<img width="965" alt="image" src="https://github.com/user-attachments/assets/30fca2c4-ea9a-4664-89a9-294698019033">

**Comment by elezar** [comment]
@yuliyan-valchev-ft it is not clear why you are using such an old devic eplugin image. Are you able to specify the device plugin version? We have just released `v0.16.2` and this should be used if possible.

**Comment by elezar** [comment]
It seems as if the EKS documentation [here](https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-eks-setup.html) is out of date.

<img width="1085" alt="Screenshot 2024-08-08 at 16 32 25" src="https://github.com/user-attachments/assets/94448938-e9bd-43aa-84d1-ee1c49b3ebf6">

Our recommended mechanism for installing and managing the plugin is Helm. The instructions from the README should be ablicable to EKS too.

**Comment by vara-bonthu** [comment]
We are working on updating these docs. Will update the issue once it's resolved.
