### ISSUE TITLE
bug: cannot build without docker

### ISSUE THREAD

**Issue by angao** [NVIDIA/k8s-device-plugin#84]
### 1. Issue or feature description
when I build this without docker, the following error occurred:
k8s-device-plugin version: v1.10
Kernel version: `Linux kube 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
```
In file included from vendor/github.com/NVIDIA/nvidia-docker/src/nvml/bindings.go:6:0:
./nvml_dl.h:6:18: fatal error: nvml.h: No such file or directory
 #include <nvml.h>
```
### 2. Steps to reproduce the issue
- git checkout -b v1.10 origin/v1.10
- execute `C_INCLUDE_PATH=/usr/local/cuda/include LIBRARY_PATH=/usr/local/cuda/lib64 go build`

**Comment by guptaNswati** [comment]
Is there a reason you are building version v1.10? The latest is v1.11. 

This error is because of missing NVML headers. In version v1.11 we are calling NVML bindings from here https://github.com/NVIDIA/gpu-monitoring-tools/tree/master/bindings/go/nvml and not nvidia-docker. So in your case, either change to the right version or change the import path.

**Comment by tingzhang-ming** [comment]
you said that either change to the right version or change the import path, so how to change the import path? could you explain more specificlly?

**Comment by tingzhang-ming** [comment]
@guptaNswati i built the version v1.10 with the same problem, you said that either change to the right version or change the import path, so how to change the import path? could you explain more specificlly?

**Comment by guptaNswati** [comment]
Change the go vendor import path to `"github.com/NVIDIA/gpu-monitoring-tools/bindings/go/nvml"` from `"github.com/NVIDIA/nvidia-docker/src/nvml"`

Check this https://github.com/NVIDIA/k8s-device-plugin/commit/b06bf4828f8fee1d6a6d8e2a43f37ac1e1c31bfe

You should be able to build 1.11 with k8s 1.10
