### ISSUE TITLE
README section for MPS should state `spec.hostIPC: true` is required in a Pod

### ISSUE THREAD

**Issue by chipzoller** [NVIDIA/k8s-device-plugin#843]
(Issue template overkill for this one.)

The README section on MPS should state that when MPS is used, the Pod `spec`-level field `hostIPC: true` is required. This information is nicely called out in the Google Cloud documentation [here](https://cloud.google.com/kubernetes-engine/docs/how-to/nvidia-mps-gpus) along with a warning of the security implications this has. The device plugin's documentation should similarly call this out so it's clear for users.

**Comment by chipzoller** [comment]
I'm glad to assign this to myself if there are no objections here by the maintainers.

**Comment by klueska** [comment]
This should not be necessary. It would be good to understand what is special about your environment that is making you require this.

**Comment by chipzoller** [comment]
To be honest, I did not notice this did not work without setting `hostIPC: true`. I was making an assumption from Google's docs that this was a universal need. You're saying that, as of the current version, if running outside of a GKE environment this field does not need to be set?

**Comment by klueska** [comment]
Yes, GKE runs a completely different GPU stack for k8s than what we provide for most users. We are working to converge them, but the process is slow.

So long as you follow this, there is no need for `hostIPC: true`.
https://docs.google.com/document/d/1H-ddA11laPQf_1olwXRjEDbzNihxprjPr74pZ4Vdf2M/edit

**Comment by chipzoller** [comment]
Thank you for correction here. Closing this as not planned.
