### ISSUE TITLE
how to add `-ulimit memlock=-1 --ulimit stack=67108864 ` ?

### ISSUE THREAD

**Issue by zgfh** [NVIDIA/k8s-device-plugin#85]
when use nvidia-docker, we can do this:
```
docker run -it -shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864  nvcr.io/nvidia/tensorflow:18.11-py3 bash
```
,when we run a pod with kubernates,how to add  parameter of ` -shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864  `?

**Comment by RenaudWasTaken** [comment]
Hello!

In the future, please open issues against Kubernetes or ask on the Kubernetes slack channel.
This repository isn't purposed to answer these questions.

Ulimit: https://stackoverflow.com/questions/33649192/how-do-i-set-ulimit-for-containers-in-kubernetes
shm: https://stackoverflow.com/questions/43373463/how-to-increase-shm-size-of-a-kubernetes-container-shm-size-equivalent-of-doc

**Comment by zgfh** [comment]
@RenaudWasTaken thanks for help
