### ISSUE TITLE
master gets nvidia.com/gpu as 0

### ISSUE THREAD

**Issue by Pallavi-code** [NVIDIA/k8s-device-plugin#89]
I have created kubernetes cluster with 1 master and 2 nodes . 2 nodes having GPU. installing nvidia device plugin detects the GPU in node1. in node2 it  detects the GPU but the requests as 0.
 
Result of describe node in master node.
========================
Allocated resources:(Result of nod2)
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource        Requests    Limits
  --------        --------    ------
  cpu             250m (0%)   0 (0%)
  memory          250Mi (0%)  0 (0%)
  **nvidia.com/gpu  0           0**

It replys with **nvidia.com/gpu  0           0**.

node2 (nvidia-smi)
============

root@node3:/etc/systemd/system/kubelet.service.d# nvidia-smi
Wed Jan  9 16:05:12 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.54                 Driver Version: 396.54                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:04:00.0  On |                  N/A |
|  0%   44C    P8     9W / 200W |     42MiB /  8118MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1359      G   /usr/lib/xorg/Xorg                            39MiB |
+-----------------------------------------------------------------------------+

Log of nvidia-device pod in master 
=========================
root@kmaster:/home/ubuntu# kubectl logs -n kube-system nvidia-device-plugin-daemonset-tg45p
Error from server: Get https://10.203.203.38:10250/containerLogs/kube-system/nvidia-device-plugin-daemonset-tg45p/nvidia-device-plugin-ctr: Forbidden

**Comment by RenaudWasTaken** [comment]
If you can't access logs you have problems not related to NVIDIA GPUs.
See among other issues: https://github.com/kubernetes/kubeadm/issues/211
