### ISSUE TITLE
Error on gpu requests in nvidia-docker2

### ISSUE THREAD

**Issue by Aaron-DH** [NVIDIA/k8s-device-plugin#90]
Since nvidia-docker2 run docker with nvidia-runtime and through env(NVIDIA_VISIBLE_DEVICES) to controller witch gpu can use.
How can i use in kubernetes to use nvidia-device-plugin to manage gpu resource

Steps as this:
apply 1 gpu in podA (set resources.limits.nvidia.com/gpu:1)
error occurs that don't have the env NVIDIA_VISIBLE_DEVICES, i need to set it manually

then apply 1 gpu in another podB

But these two pods has used the same gpu
+-----------------------------------------------------------------------------+
| Processes: GPU Memory |
| GPU PID Type Process name Usage |
|==============================================
| 0 23831 C python 10445MiB |
| 0 27936 C python 499MiB |

In addition, if apply 1 gpu but set NVIDIA_VISIBLE_DEVICES=all, it still can get all gpus in container
how could k8s automatic  set NVIDIA_VISIBLE_DEVICES  according to the requests

**Comment by RenaudWasTaken** [comment]
Please see this project's README, the behavior that you describe doesn't happen if you set resources.
If you hit any error, open a new issue **following the issue template**.
