### ISSUE TITLE
Lack of Metrics for SLO Onboarding with k8s-device-plugin

### ISSUE THREAD

**Issue by vijjais1** [NVIDIA/k8s-device-plugin#900]
The k8s-device-plugin is currently deployed on several clusters, and the deployment has been successful. However, we are not able to retrieve any metrics that are necessary for SLO onboarding.

Could this issue be addressed in an upcoming release or fix?

**Comment by elezar** [comment]
@vijjais1 which metrics would you require?

**Comment by vijjais1** [comment]
We are seeking metrics that will allow us to assess whether a service is functioning as intended—not just that it is running, but also that it is performing as expected. As part of our efforts to enhance platform reliability, we are defining Service Level Objectives (SLOs) for all core components, including the Kubernetes device plugin, which is a critical element of our infrastructure.
