### ISSUE TITLE
Use `apps/v1` API for the DaemonSet resources

### ISSUE THREAD

**Issue by thomas-riccardi** [NVIDIA/k8s-device-plugin#93]
#91 had to explicitly set the `updateStrategy` to `RollingUpdate` to have  proper update behavior. This is the default behavior when using `apps/v1` `apiVersion` instead of the current `extensions/v1beta1`.

Maybe it's time to update to `apiVersion: apps/v1`.

See also:
- https://github.com/NVIDIA/k8s-device-plugin/pull/91#issuecomment-456103347
- https://github.com/kubernetes/kubernetes/commit/5139bb580ac3688640e570803c10b6c65b97141f

**Comment by RenaudWasTaken** [comment]
@kklues

**Comment by suneeta-mall** [comment]
@RenaudWasTaken https://github.com/NVIDIA/k8s-device-plugin/pull/128

**Comment by RenaudWasTaken** [comment]
I believe this is done!
