### ISSUE TITLE
GPU's not recognized using docker 18.09.2

### ISSUE THREAD

**Issue by phogan-nvidia** [NVIDIA/k8s-device-plugin#95]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._
---

### 1. Issue or feature description
GPU's not recognized with minikube n

### 2. Steps to reproduce the issue
# nvidia-docker run nvidia/cuda nvidia-smi
Thu Feb 14 00:35:12 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:02:00.0 Off |                  N/A |
| 22%   27C    P0    33W / 180W |      0MiB /  8119MiB |      5%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

minikube start --feature-gates=DevicePlugins=true --vm-driver none
kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v1.10/nvidia-device-plugin.yml
# kubectl describe nodes | grep -B 3 gpu  ## No GPU's recognized
#
root@gpu1:~# kubectl get nodes
NAME       STATUS   ROLES    AGE     VERSION
minikube   Ready    master   3m54s   v1.13.2
root@gpu1:~# kubectl describe nodes
...
 kube-system                kube-controller-manager-minikube        200m (5%)     0 (0%)      0 (0%)           0 (0%)         2m43s
  kube-system                kube-proxy-4ww97                        0 (0%)        0 (0%)      0 (0%)           0 (0%)         3m50s
  kube-system                kube-scheduler-minikube                 100m (2%)     0 (0%)      0 (0%)           0 (0%)         3m
  ****kube-system                nvidia-device-plugin-daemonset-pwj45    0 (0%)        0 (0%)      0 (0%)           0 (0%)         2m35s****
  kube-system                storage-provisioner                     0 (0%)        0 (0%)      0 (0%)           0 (0%)         3m48s
...

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Common error checking:
 - [ ] The output of `nvidia-smi -a` on your host
# nvidia-smi -a

==============NVSMI LOG==============

Timestamp                           : Thu Feb 14 00:32:53 2019
Driver Version                      : 410.79
CUDA Version                        : 10.0

Attached GPUs                       : 1
GPU 00000000:02:00.0
    Product Name                    : GeForce GTX 1080
    Product Brand                   : GeForce
    Display Mode                    : Disabled
    Display Active                  : Disabled
    Persistence Mode                : Disabled
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 4000
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : 0321018023528
    GPU UUID                        : GPU-b8125ac0-1538-afd6-7f72-6c5cdd2bd271
    Minor Number                    : 0
    VBIOS Version                   : 86.04.60.00.02
    MultiGPU Board                  : No
    Board ID                        : 0x200
    GPU Part Number                 : 900-1G413-2500-000
    Inforom Version
        Image Version               : G001.0000.01.04
        OEM Object                  : 1.1
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization mode         : None
    IBMNPU
        Relaxed Ordering Mode       : N/A
    PCI
        Bus                         : 0x02
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x1B8010DE
        Bus Id                      : 00000000:02:00.0
        Sub System Id               : 0x119E10DE
        GPU Link Info
            PCIe Generation
                Max                 : 3
                Current             : 1
            Link Width
                Max                 : 16x
                Current             : 4x
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays since reset         : 0
        Tx Throughput               : 0 KB/s
        Rx Throughput               : 0 KB/s
    Fan Speed                       : 27 %
    Performance State               : P8
    Clocks Throttle Reasons
        Idle                        : Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Not Active
        HW Slowdown                 : Not Active
            HW Thermal Slowdown     : Not Active
            HW Power Brake Slowdown : Not Active
        Sync Boost                  : Not Active
        SW Thermal Slowdown         : Not Active
        Display Clock Setting       : Not Active
    FB Memory Usage
        Total                       : 8119 MiB
        Used                        : 0 MiB
        Free                        : 8119 MiB
    BAR1 Memory Usage
        Total                       : 256 MiB
        Used                        : 2 MiB
        Free                        : 254 MiB
    Compute Mode                    : Default
    Utilization
        Gpu                         : 0 %
        Memory                      : 0 %
        Encoder                     : 0 %
        Decoder                     : 0 %
    Encoder Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    FBC Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            Single Bit
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
        Aggregate
            Single Bit
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending                     : N/A
    Temperature
        GPU Current Temp            : 24 C
        GPU Shutdown Temp           : 96 C
        GPU Slowdown Temp           : 93 C
        GPU Max Operating Temp      : N/A
        Memory Current Temp         : N/A
        Memory Max Operating Temp   : N/A
    Power Readings
        Power Management            : Supported
        Power Draw                  : 5.48 W
        Power Limit                 : 180.00 W
        Default Power Limit         : 180.00 W
        Enforced Power Limit        : 180.00 W
        Min Power Limit             : 90.00 W
        Max Power Limit             : 217.00 W
    Clocks
        Graphics                    : 139 MHz
        SM                          : 139 MHz
        Memory                      : 405 MHz
        Video                       : 544 MHz
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : 1911 MHz
        SM                          : 1911 MHz
        Memory                      : 5005 MHz
        Video                       : 1708 MHz
    Max Customer Boost Clocks
        Graphics                    : N/A
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes                       : None

 - [ ] Your docker configuration file (e.g: `/etc/docker/daemon.json`)
::::::::::::::
/etc/docker/daemon.json
::::::::::::::
{
    "runtimes": {
        "nvidia": {
            "path": "nvidia-container-runtime",
            "runtimeArgs": []
        }
    },
    "storage-driver": "overlay2"
}
 - [ ] The k8s-device-plugin container logs
 - [ ] The kubelet logs on the node (e.g: `sudo journalctl -r -u kubelet`)
# journalctl -r -u kublet
-- Logs begin at Sat 2019-02-09 19:42:09 UTC, end at Thu 2019-02-14 00:32:23 UTC. --
-- No entries --
Additional information that might help better understand your environment and reproduce the bug:
 - [ ] Docker version from `docker version`
# docker version
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:31 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:02:44 2019
  OS/Arch:          linux/amd64
  Experimental:     false

 - [ ] Docker command, image and tag used
 - [ ] Kernel version from `uname -a`
# uname -a
Linux gpu1 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
# dpkg -l *nvidia* |grep -v none
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
||/ Name                                            Version               Architecture Description
+++-===============================================-=====================-============-=========================================================
ii  libnvidia-cfg1-410:amd64                        410.79-0ubuntu1       amd64        NVIDIA binary OpenGL/GLX configuration library
ii  libnvidia-common-410                            410.79-0ubuntu1       all          Shared files used by the NVIDIA libraries
ii  libnvidia-compute-410:amd64                     410.79-0ubuntu1       amd64        NVIDIA libcompute package
ii  libnvidia-container-tools                       1.0.1-1               amd64        NVIDIA container runtime library (command-line tools)
ii  libnvidia-container1:amd64                      1.0.1-1               amd64        NVIDIA container runtime library
ii  libnvidia-decode-410:amd64                      410.79-0ubuntu1       amd64        NVIDIA Video Decoding runtime libraries
ii  libnvidia-encode-410:amd64                      410.79-0ubuntu1       amd64        NVENC Video Encoding runtime library
ii  libnvidia-fbc1-410:amd64                        410.79-0ubuntu1       amd64        NVIDIA OpenGL-based Framebuffer Capture runtime library
ii  libnvidia-gl-410:amd64                          410.79-0ubuntu1       amd64        NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and Vulkan ICD
ii  libnvidia-ifr1-410:amd64                        410.79-0ubuntu1       amd64        NVIDIA OpenGL-based Inband Frame Readback runtime library
ii  nvidia-compute-utils-410                        410.79-0ubuntu1       amd64        NVIDIA compute utilities
ii  nvidia-container-runtime                        2.0.0+docker18.09.1-1 amd64        NVIDIA container runtime
ii  nvidia-container-runtime-hook                   1.4.0-1               amd64        NVIDIA container runtime hook
ii  nvidia-diag-driver-local-repo-ubuntu1804-410.79 1.0-1                 amd64        nvidia-diag-driver-local repository configuration files
ii  nvidia-dkms-410                                 410.79-0ubuntu1       amd64        NVIDIA DKMS package
ii  nvidia-docker2                                  2.0.3+docker18.09.1-1 all          nvidia-docker CLI wrapper
ii  nvidia-driver-410                               410.79-0ubuntu1       amd64        NVIDIA driver metapackage
ii  nvidia-kernel-common-410                        410.79-0ubuntu1       amd64        Shared files used with the kernel module
ii  nvidia-kernel-source-410                        410.79-0ubuntu1       amd64        NVIDIA kernel source package
ii  nvidia-prime                                    0.8.8.2               all          Tools to enable NVIDIA's Prime
ii  nvidia-settings                                 410.79-0ubuntu1       amd64        Tool for configuring the NVIDIA graphics driver
ii  nvidia-utils-410                                410.79-0ubuntu1       amd64        NVIDIA driver support binaries
ii  xserver-xorg-video-nvidia-410                   410.79-0ubuntu1       amd64        NVIDIA binary Xorg driver

 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
# nvidia-container-cli -V
version: 1.0.1
build date: 2019-01-15T23:24+00:00
build revision: 038fb92d00c94f97d61492d4ed1f82e981129b74
build compiler: x86_64-linux-gnu-gcc-7 7.3.0
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections

 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))

**Comment by RenaudWasTaken** [comment]
Hello!

Please fill the issue template for this repository.

Thanks!

**Comment by phogan-nvidia** [comment]
Was able to sort out the env and minikube now see's the GPU resources. 2 Issues were:

1. docker was not configured to use 'nvidia-docker2' by default. Installation was correct, however needed to update /etc/docker/daemon.json to be

root@nv1:~# cd /etc/docker
root@nv1:/etc/docker# ls
daemon.json  daemon.json-mine  key.json
root@nv1:/etc/docker# more daemon.json
{
    "runtimes": {
        "nvidia": {
            "path": "nvidia-container-runtime",
            "runtimeArgs": []
        }
    },
    "storage-driver": "overlay2",
    "default-runtime": "nvidia"
}

2. was using v1.10 rather than v1.11 of the Daemonset
