### ISSUE TITLE
Specifying a driver version

### ISSUE THREAD

**Issue by ranginuitrot** [NVIDIA/k8s-device-plugin#97]
### 1. Issue or feature description

I want to use CUDA 10, but the device driver version in 1.11 uses 396.26. Where's the best place to override this to use the latest device driver (or at least >=410.48)?

### 2. Steps to reproduce the issue

Install DaemonSet v1.11 on k8s cluster. `nvidia-smi` shows 396.26, which doesn't support CUDA 10.

**Comment by RenaudWasTaken** [comment]
Hello!

You don't need to do that :)
Just install the NVIDIA Driver on the machine and it will be exposed correctly inside your container :)

**Comment by ranginuitrot** [comment]
Sounds good. To the AMI! :)
