### ISSUE TITLE
Enabling MPS fails on K3S

### ISSUE THREAD

**Issue by santurini** [NVIDIA/k8s-device-plugin#983]
I am following @elezar's [guide](https://docs.google.com/document/d/1H-ddA11laPQf_1olwXRjEDbzNihxprjPr74pZ4Vdf2M/edit#heading=h.9odbb6smrel8) to enable MPS on my cluster using K3S.

The cluster is self-hosted on one node with 8 x NVIDIA RTX 3090 that serves both as master and worker node.
I already checked this similar issue #712 without finding a solution.

After installing gpu-operator like this:
```
helm install \
      -n gpu-operator \
      --generate-name \
      --create-namespace \
      --set devicePlugin.enabled=false \
      --set gfd.enabled=false \
      nvidia/gpu-operator
``` 

I create the configuration file:
```
cat << EOF > /tmp/dp-mps-10.yaml
version: v1
sharing:
  mps:
    resources:
    - name: nvidia.com/gpu
      replicas: 10
EOF
```

And finally install the device plugin:
```
helm upgrade -i nvdp nvdp/nvidia-device-plugin \
    --version=0.15.0 \
    --namespace nvidia-device-plugin \
    --create-namespace \
    --set gfd.enabled=true \
    --set config.default=mps10 \
    --set-file config.map.mps10=/tmp/dp-mps-10.yaml
```

But I am not able to get the correct node labels as it fails with this error:
```
Back-off restarting failed container nvidia-device-plugin-ctr in pod nvdp-nvidia-device-plugin-xg86f_nvidia-device-plugin(94addf08-c2ed-402a-991b-ba0041dce80f)
```

**Comment by dtwork2022** [comment]
I'm having the same problem but on k8s. The `nvidia.com/mps.capable=false` labels persists even after restarting gfd, DevicePluginCDIDevices after applying mps sharing configmap. I even rebooted the node and attempted to overwrite the mps.cable=true but it gets reverted back to false. 

I'm using Nvidia L40S, does it not support MPS ?
